### ISSUE TITLE
log "healthAuthorityId" in publish logs

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#1011]
this will help correlate failures back to the entity that is attempting to upload TEKs

**Comment by jeremyfaller** [comment]
Any particular error paths you want handled beyond the entry? Anything that would have made your life easier?

**Comment by mikehelmick** [comment]
A couple of points that come to mind

- https://github.com/google/exposure-notifications-server/blob/main/internal/publish/publish.go#L279

- https://github.com/google/exposure-notifications-server/blob/main/internal/publish/publish.go#L327

- https://github.com/google/exposure-notifications-server/blob/main/internal/publish/publish.go#L352
