### ISSUE TITLE
promote and deploy scripts might fail because of missing optional services

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#1028]
The deploy and promote scripts might fail in case an optional service such as "debugger" was not provisioned as the default behaviour is SERVICES=ALL
The workaround is to specify services names manually in deploy and promote steps.

**Comment by mikehelmick** [comment]
I'll let @sethvargo comment, but II think this may be working as intended if not all services are enabled.

**Comment by sethvargo** [comment]
Hi @sherifkozman - I think you may be on an outdated version. The scripts haven't used `SERVICES` [since Sept 1](https://github.com/google/exposure-notifications-server/commit/67d574984d2200be48e0944f0a318048e855bb8d#diff-2cd5a769047cc97c38be7c1d885ea647). But yes, this is WAI.

**Comment by sherifkozman** [comment]
@sethvargo i am on v0.9.2 and I was referring to deploy and promote not build unless I got the wrong.

**Comment by sethvargo** [comment]
None of the scripts accept `SERVICES` anymore.
