### ISSUE TITLE
gcloud run deploy error --no-traffic error

### ISSUE THREAD

**Issue by grpandurangi** [google/exposure-notifications-server#1047]
Getting below error when we run /scripts/deploy script. 

```
Step #4 - "deploy-exposure": Status: Image is up to date for gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine
Step #4 - "deploy-exposure": gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine
Step #5 - "deploy-federationin": Digest: sha256:156cf9e9b940bfbcb3eff148ed1683b2f4610560a4d36e04eb1d1e3ed819c716
Step #5 - "deploy-federationin": Status: Image is up to date for gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine
Step #5 - "deploy-federationin": gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine
Step #8 - "deploy-key-rotation": Digest: sha256:156cf9e9b940bfbcb3eff148ed1683b2f4610560a4d36e04eb1d1e3ed819c716
Step #8 - "deploy-key-rotation": Status: Image is up to date for gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine
Step #8 - "deploy-key-rotation": gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine
Step #5 - "deploy-federationin": Deploying container to Cloud Run service [federationin] in project [true-truck-291212] region [us-central1]
Step #2 - "deploy-debugger": Deploying container to Cloud Run service [debugger] in project [true-truck-291212] region [us-central1]
Step #2 - "deploy-debugger": Deploying new service...
Step #2 - "deploy-debugger": failed
Step #2 - "deploy-debugger": Deployment failed
Step #2 - "deploy-debugger": ERROR: (gcloud.run.deploy) --no-traffic not supported when creating a new service.
Finished Step #2 - "deploy-debugger"
ERROR
ERROR: build step 2 "gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine" failed: step exited with non-zero status: 1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR: (gcloud.builds.submit) build 50b87e2b-1fa7-44dd-873f-9f42e93465c2 completed with status "FAILURE"
```

**Comment by sethvargo** [comment]
Hi @grpandurangi 

This is expected. You need to deploy the services the first time using Terraform as we mentioned on the call. Then you can use the deployment and promotion scripts.

**Comment by grpandurangi** [comment]
Thank you for your response Seth.

Terraform was successful and was able to provision the resources. After
that tried the perform build, deploy and promote. Build failed due to
save-cache.
After commenting that it was successful. However, deploy is failing with
error "--no-traffic not supported when creating a new service."

Regards,
Gururaj

**Comment by grpandurangi** [comment]
*Hi Seth,*


*Below is the error: *



*Step #2 - "save-cache": Already have image (with digest):
us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1
<http://us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1>*

*Step #9 - "build-export": Already have image: golang:1.15.2*

*Step #19 - "build-key-rotation": Already have image: golang:1.15.2*

*Step #15 - "build-federationout": Already have image: golang:1.15.2*

*Step #17 - "build-generate": Already have image: golang:1.15.2*

*Step #11 - "build-exposure": Already have image: golang:1.15.2*

*Step #3 - "build-cleanup-export": Already have image: golang:1.15.2*

*Step #23 - "build-jwks": Already have image: golang:1.15.2*

*Step #13 - "build-federationin": Already have image: golang:1.15.2*

*Step #7 - "build-debugger": Already have image: golang:1.15.2*

*Step #21 - "build-migrate": Already have image: golang:1.15.2*

*Step #5 - "build-cleanup-exposure": Already have image: golang:1.15.2*

*Step #2 - "save-cache": failed to walk files: failed to write tar:
googleapi: Error 404: Not Found, notFound: failed to close tar writer:
googleapi: Error 404: Not Found, notFound: failed to close gzip writer:
googleapi: Error 404: Not Found, notFound: failed to close gcs writer:
googleapi: Error 404: Not Found, notFound*

*Step #2 - "save-cache": *

*Finished Step #2 - "save-cache"*

*ERROR*

*ERROR: build step 2 "us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1
<http://us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1>" failed:
step exited with non-zero status: 1*

*Finished Step #5 - "build-cleanup-exposure"*

*Finished Step #17 - "build-generate"*

*Finished Step #7 - "build-debugger"*

*Finished Step #3 - "build-cleanup-export"*



Regards,

Gururaj

**Comment by sethvargo** [comment]
@grpandurangi did you create the cache bucket? Terraform normally does this. If not, it's `$PROJECT_ID-cloudbuild-cache`, replacing `$PROJECT_ID` with your project ID.

**Comment by grpandurangi** [comment]
Seth,

I tried several times . Only after disabling this below code, terraform
gets completed:

# - id: 'save-cache'
#   name: 'us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1'
#   args:
#   - '-bucket=${PROJECT_ID}-cloudbuild-cache'
#   - '-cache=go-{{ hashGlob "go.mod" }}'
#   - '-dir=/go/pkg'
#   waitFor:
#   - 'download-modules'

Also, TF creates the cache storage bucket.
[image: image.png]

**Comment by sethvargo** [comment]
Can you add `- '-debug'` as an argument?

**Comment by grpandurangi** [comment]
I dont see the issue anymore.
