### ISSUE TITLE
use uint32 for things that are never negative

### ISSUE THREAD

**Issue by laurentsimon** [google/exposure-notifications-server#110]
in [exposure.go](https://github.com/google/exposure-notifications-server/blob/master/internal/model/exposure.go#L43), interval_number and intervalCount are defined as signed integers but they cannot take negative values.

**Comment by radisef347** [comment]
![alt text](https://cdni.pornpics.com/1280/7/51/81056079/81056079_141_f080.jpg)

**Comment by mikehelmick** [comment]
There is extensive model validation around exposures now, ensuring proper values.

/close
