### ISSUE TITLE
Is there a way to reset the key server

### ISSUE THREAD

**Issue by slagise** [google/exposure-notifications-server#1105]
### Question
 
Is there a way to reset the exports? I tried deleting the archives but the new export index file had the records of the older deleted archives. Is there a way to reset the whole export server? If not, what is the best way to handle this scenario. We recently had to changed the public key without setting the older one to expire, and the matching isn't working properly. I don't mind losing the old archives as we are still not on prod.

**Comment by mikehelmick** [comment]
If you delete the record from the `exportbatch` and `exportfile` tables - the export job should re-create them, signed with the new private key.

**Comment by mikehelmick** [comment]
/assign
/close

Please reopen if this doesn't solve the issue for you.
