### ISSUE TITLE
Performance test is flaky

### ISSUE THREAD

**Issue by chaodaiG** [google/exposure-notifications-server#1132]
### TL;DR

Performance test has been failing intermittently, with error:

```
helpers.go:397: did not return ok after 30 retries: retryable: Want exported keys: 1400000, got: 1331890
```

It doesn't fail every time

**Expected behavior**

Performance test passes consistently

**Observed behavior**

### Reproduction

See https://k8s-testgrid.appspot.com/googleoss-en-server#performance

**Comment by chaodaiG** [comment]
@MushuEE , interested in taking this?

**Comment by sethvargo** [comment]
From those numbers, it looks like we either need to tune the parameters or just wait longer.

**Comment by mikehelmick** [comment]
I recently made changes to export that would negatively imapct performance

**Comment by chaodaiG** [comment]
> I recently made changes to export that would negatively imapct performance

So this might be the cause for this flakiness. And the mako graph does show the performance degradation, note the moving average change around Oct 30th:

![Screen Shot 2020-11-02 at 8 20 32 AM](https://user-images.githubusercontent.com/45011425/97891968-4aeb7c00-1ce4-11eb-8900-29352c999dcc.png)

Link for the dashboard:
https://mako.dev/benchmark?benchmark_key=4790091207671808

**Comment by mikehelmick** [comment]
we need to adjust expectations - the generated data is persisted to the DB, so there are now database write transactions in the critical path

**Comment by MushuEE** [comment]
> we need to adjust expectations 

If we have acceptable limits, I don't mind updating to enforce. Both increasing the number of retry and 
```
	exportConfig := &export.Config{
		CreateTimeout:  30 * time.Second,
		WorkerTimeout:  30 * time.Second,
		MinRecords:     1,
		PaddingRange:   1,
		MaxRecords:     25000,
		TruncateWindow: 1 * time.Second,
		MinWindowAge:   1 * time.Second,
		TTL:            336 * time.Hour,
	}
```
Increasing MaxRecords seemed to help when seeing similar behavior previously. 
/assign
