### ISSUE TITLE
Exportimporter leaves importfiles OPEN or PENDING

### ISSUE THREAD

**Issue by bschlaman** [google/exposure-notifications-server#1134]
### TL;DR
If an importfile is unable to be ingested by exportimporter (due to incorrect formatting of export url, etc), it sometimes remains in "PENDING" status instead of failing.

**Expected behavior**
Import should fail after X number of tries.

**Observed behavior**
Importfile left in PENDING status.

@mikehelmick

**Comment by mikehelmick** [comment]
/assign

my plan is to retry a file as long as it appears in the index.txt file - when it drops out of there, we'll move it to failed.

will also add a retry count, so an operator could see this

**Comment by jeremyfaller** [comment]
yoink
