### ISSUE TITLE
Return JSON response bodies on Chaff requests

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#1155]
### TL;DR

The go-chaff library already supports this
  https://github.com/mikehelmick/go-chaff/blob/main/json.go

Use this to respond w/ properly formed JSON based on the request being chaffed - for our APIs, this really just means having a `padding` key in the JSON object.

REMEMBER - the size of the random data will need to be reduced as base 64 encoding will cause ~33% size increase.

/priority important-soon
/kind enhancement

**Comment by jeremyfaller** [comment]
This requires changes to the chaff library, and the person who does it should make sure to do both.

Yoink.

**Comment by sethvargo** [comment]
Do you know which changes need to be made?
