### ISSUE TITLE
How can I update a SVG file based on a diagram file?

### ISSUE THREAD

**Issue by alexgarzao** [google/exposure-notifications-server#1156]
Hello! I'm using this project to learn more about architecture, golang, gRPC, protobuf, and so on.

There are a lot of amazing diagrams [here](https://github.com/google/exposure-notifications-server/tree/main/docs/diagrams). It seems that was used something like [that](https://github.com/blushft/go-diagrams), but I'm not sure about that.

When is necessary to change a diagram file, how you update the SVG file?

**Comment by mikehelmick** [comment]
the .diagram files are turned into SCV with a special version of https://graphviz.org/
The version we are using is internal to Google only.

/close
