### ISSUE TITLE
Migrate key server to use gorm

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-server#1157]
It looks like in the key server we are using github.com/jackc/pgx directly, instead of its database/sql compatible layer. There's no way to plug-in the OpenCensus SQL instrumentation code (https://pkg.go.dev/contrib.go.opencensus.io/integrations/ocsql/).

We should consider moving to gorm to allow adding OpenCensus instrumentation code.

**Comment by mikehelmick** [comment]
I view this as too risky a change at this point

**Comment by sethvargo** [comment]
I explored this recently and completely agree with Mike. The change is incredibly invasive and error-prone.

**Comment by mikehelmick** [comment]
Going to close this for now

/close
