### ISSUE TITLE
Allow export-analyzer to ingest multiple files

### ISSUE THREAD

**Issue by bschlaman** [google/exposure-notifications-server#1192]
### TL;DR
Currently, export-analyzer can analyze one file at a time.  When having to analyze all exports of a key server, it would save a ton of time to call the tool once as opposed to once per zip.

### Design

**Proposal**
Create a new flag like "--files" for a comma separated list, or "--zips-location" to point to a directory wherein the zips reside.  Then the tool would ingest all files and output all at once.

**Comment by mikehelmick** [comment]
@bschlaman - if there is a specific use case that we can help solve as well, let us know
