### ISSUE TITLE
Integration tests - test large / split batches

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#1202]
The integration tests currently don't have coverage over large batches / split batches.

**Comment by sethvargo** [comment]
@chaodaiG do you have any bandwidth to work on this?

**Comment by chaodaiG** [comment]
I'll give it a stab. By looking at the title, this means testing exporting batches from various time points, is this correct?

/assign

**Comment by mikehelmick** [comment]
for large: I think that can be a unit test - but it means injecting a bunch of data and generating an export

for splitting: It means having enough TEKs that it causes the batch to be split into 2 files (Which can be made artificially low through settings)
