### ISSUE TITLE
Creating new verification key error

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#1313]
### TL;DR
When adding a new Public verification key to an issues the following error occurs
"Error parsing new health authority key: unable to decode PEM block containing PUBLIC KEY"

**Expected behavior**
When copying the Key values created by the verification server including kid and public key, key should be added to issuer/

**Release version**
v0.20.0

**Comment by sethvargo** [comment]
Hi @sherifkozman 

Sorry, I'm not sure I follow. Can you describe the steps you took, where you copied the key, where you pasted the key, and what you expected to happen? There are many kinds of "keys" in the system.

**Comment by mikehelmick** [comment]
Can you share the exact data that fails?

The preferred method for verification key sharing is to use the JWKS discovery.

**Comment by sherifkozman** [comment]
From the Realm Settings over the Verification Server we copy the Verification certificate Key settings.
Those values are copied into the exposure key admin console manually into the verification keys
upon adding the Pasted key details the error occur.

@mikehelmick I would have used the JWKS method but there wasnt much info on which values to set in the documentation, specifically how to source the JWKS URI

**Comment by mikehelmick** [comment]
See the "view public key discovery" link on the verification server's signing key page

![image](https://user-images.githubusercontent.com/92319/106337608-7976e580-6246-11eb-9fc2-147b3f8494cb.png)

Any additional details you can provide on the error would be helpful

**Comment by sherifkozman** [comment]
@mikehelmick I used the URI from the public discovery link as advised.
I shared all steps we encountered but happy to share more if there is other places to look? would the error reflect in Logging ?

**Comment by mikehelmick** [comment]
yes, the error would show up in your logs.

without seeing the actual public key data - I can't possibly attempt to reproduce this.

**Comment by mikehelmick** [comment]
This does not impact v0.20.0, but is broken at head
