### ISSUE TITLE
I realize I'm a public key, can someone please please give me a brief summary of what I'm capable of and how to produce it? Tia. Also I need a run down on tokens, creating and using. Thanks. 

### ISSUE THREAD

**Issue by ryanwolcott321** [google/exposure-notifications-server#1318]

**Comment by sethvargo** [comment]
Hi @ryanwolcott321 

Thank you for opening an issue. This is the [Exposure Notifications project](g.co/ens) repository. Do you have a specific question about exposure notifications?

**Comment by mikehelmick** [comment]
There are several places where asymmetric signing is used in this system. Which public key are you referring to.

The only tokens in this system are “revisionTokens” - please see the API documentation
   https://github.com/google/exposure-notifications-server/blob/716d93c62c2a3f0aa6da43ce79f21f57b7f91732/pkg/api/v1/exposure_types.go#L90

They are used by mobile clients - but created and validated on the server only.

**Comment by sethvargo** [comment]
Hi @ryanwolcott321 - did you have any follow up questions?
