### ISSUE TITLE
KMS keys can be in "PENDING_GENERATION" state during rotation

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-server#1328]
While rare, we currently have a race condition when rotating keys. We create a new key via the API, but that does not guarantee the key _material_ is ready yet. For example, we have this error in our logs:

```text
failed to fetch public key: rpc error: code = FailedPrecondition desc = [redacted] is not enabled, current state is: PENDING_GENERATION.
```

Reading the KMS API, key version generation happens in the background.

### Options

1. Update the key server KMS package to poll for the `READY` state when creating a new key version, and only return when it's ready (expiration via context).

1. Add the polling to the verification server, specifically in the rotation job.

**Comment by mikehelmick** [comment]
working on this

**Comment by sethvargo** [comment]
Oh whoops - I was working on this and just saw your comment.
