### ISSUE TITLE
v1alpha API fails with new mux handler

### ISSUE THREAD

**Issue by bschlaman** [google/exposure-notifications-server#1348]
### TL;DR
Calls to exposure service /xxx are not handled by HandleV1Alpha1

**Expected behavior**
Calls like /publish should invoke the v1alpha handler

**Observed behavior**
Get a 404 response

### Reproduction
Hit key server exposure service with /xxx endpoint

**Additional information**
mux.NewRouter() matches "/" exactly, unlike http.NewServeMux() which is a catch-all

**Comment by mikehelmick** [comment]
Does this impact a production deployment?

**Comment by mikehelmick** [comment]
We're planning to make Mux routes more strict, not less strict (i.e. requiring POST method)

**Comment by sethvargo** [comment]
Also, this particular mux hasn't changed in a very long time...

**Comment by bschlaman** [comment]
This is due to the v0.21 switch to using gorilla/mux.  It handles path matching differently than the http.ServeMux - so a call to /publish will return a 404 where it previously would have been handled by v1alpha

**Comment by bschlaman** [comment]
The v1alpha path "/" will still work, but I believe some jurisdictions might be using weird paths

**Comment by bschlaman** [comment]
Scratch that - I don't see any evidence of paths other than "/" being used for v1alpha in production; this might be a case of a developers testing config being different from prod
