### ISSUE TITLE
Add e2e tests for key server

### ISSUE THREAD

**Issue by mariliamelo** [google/exposure-notifications-server#1356]
### TL;DR
Add end to end tests on the Key server to verify all the core functionalities like uploading new keys, verifying the uploaded keys are available in export.

### Design

**Alternatives considered**
The current End to End test available on the verification server [link](https://github.com/google/exposure-notifications-verification-server/blob/main/internal/clients/e2e.go) tests uploading keys to the configured key server.

**Comment by sethvargo** [comment]
Like this? https://github.com/google/exposure-notifications-server/blob/main/internal/e2e/e2e_test.go

**Comment by mikehelmick** [comment]
I was thinking more of a deployable one like we have in verification.

The answer may be to make the verification one check for the keys that it uploads... later.

**Comment by mariliamelo** [comment]
Seth and Mike, what have you decided about the e2e tests for the key server? Do we need a new e2e test or are we going to just use the one from verification?

**Comment by sethvargo** [comment]
I think we need to do this in the verification server, but I don't think we've decided on how yet.
