### ISSUE TITLE
Write client/server interop spec

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#138]
/cc @crwilcox @gurayAlsac @peetsasaki

**Comment by augard** [comment]
Currently there is no guide how integrated server with app? Or any other doc that will help integrate app with server.

**Comment by gurayAlsac** [comment]
There isn't a formal spec and different apps or servers may have different needs. But we have made a sample reference app available that integrates with this server:
https://github.com/google/exposure-notifications-android

The gist of it is that this server makes available an index of available export files to fetch, which the app periodically checks. See https://github.com/google/exposure-notifications-android/blob/master/app/src/main/java/com/google/android/apps/exposurenotification/network/DiagnosisKeyDownloader.java
