### ISSUE TITLE
Update status code for error generated from user requests

### ISSUE THREAD

**Issue by mariliamelo** [google/exposure-notifications-server#1412]
### TL;DR
We are returning 500s for errors originated in the user requests. This should be updated to 400s.

### Design
This is currently happening in at least 2 points:

https://github.com/google/exposure-notifications-server/blob/02a136a7cf2f70f3d9f79ab6da44a72bbd9637e5/internal/publish/model/exposure_model.go#L340

https://github.com/google/exposure-notifications-server/blob/02a136a7cf2f70f3d9f79ab6da44a72bbd9637e5/internal/revision/revision.go#L216

**Comment by mikehelmick** [comment]
For the revision token - if that fails we log an error, but don’t return an error code

https://github.com/google/exposure-notifications-server/blob/02a136a7cf2f70f3d9f79ab6da44a72bbd9637e5/internal/publish/publish.go#L454

**Comment by mikehelmick** [comment]
And for the first one - transform errors result in a bad request

https://github.com/google/exposure-notifications-server/blob/02a136a7cf2f70f3d9f79ab6da44a72bbd9637e5/internal/publish/publish.go#L358

**Comment by mikehelmick** [comment]
I don't see where the AdjustAndValidate ever comes back to a 500 - it is a 400.

**Comment by sethvargo** [comment]
I think it's the logging of the error (not necessarily a 500): https://github.com/google/exposure-notifications-server/blob/02a136a7cf2f70f3d9f79ab6da44a72bbd9637e5/internal/federationin/federationin.go#L399
