### ISSUE TITLE
denormalize signing key info in export tables

### ISSUE THREAD

**Issue by gurayAlsac** [google/exposure-notifications-server#147]
In a world where we might have multiple signatures on an export (whether from a key rolling, or an external authority cosigning on the exports) we would want to populate multiple SignatureInfo's on the export. Currently our ExportConfig and ExportBatch assume one signing key (and don't allow for additional info like key version or identifier).

**Comment by radisef347** [comment]
![alt text](https://cdni.pornpics.com/1280/7/51/81056079/81056079_141_f080.jpg)

**Comment by mikehelmick** [comment]
/close

This is fixed. Export config allows multiple signature infos to be configured.
