### ISSUE TITLE
Issue section removed for exposure-notifications-internals repo

### ISSUE THREAD

**Issue by rachyandco** [google/exposure-notifications-server#1477]
### Question
Why was the issue section for https://github.com/google/exposure-notifications-internals/ removed ?

We are specially interested in issue 27 which we believe should remain open: Here is a link to the webarchive https://web.archive.org/web/20210320232232/https://github.com/google/exposure-notifications-internals/issues/27

**Comment by sethvargo** [comment]
Hi @rachyandco 

Thank you for opening an issue. This repository is specific to the Exposure Notifications server implementation. For feedback about the overall Exposure Notifications project, please use the email address in the README.

**Comment by pdehaye** [comment]
For reference, that issue had been archived [here](https://web.archive.org/web/20210320232232/https://github.com/google/exposure-notifications-internals/issues/27) before deletion.
