### ISSUE TITLE
don't block startup on metric initialization

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#1541]
### TL;DR

in stackdriver.go - a server can fail to start if metrics can't be initialized.

During a scale up event, this is lots of write RPCs in a short amount of time that are effectively no-ops.

Things to investigate

* can we to a read pass to see if metrics exist before attempting to create
* should this be done in a go-routine or selectively done in a go-routine

**Comment by sethvargo** [comment]
https://github.com/google/exposure-notifications-server/pull/1542
