### ISSUE TITLE
Standardize API responses

### ISSUE THREAD

**Issue by squee1945** [google/exposure-notifications-server#197]
As discussed briefly in #195 
cc @sethvargo

**Comment by sethvargo** [comment]
Adding more context here. Right now, across the entire project, we have HTTP handlers that:

- Log an error that's wrapped/formatted
- Publish a metric (usually)
- Write a status (usually 200, even for failures)
- Return

The current problems are:

- If we forget to return, the handler continues on
- If we don't log, debugging is a challenge
- Sometimes we do use a non-200 status (e.g. for federation)

A potentially better architecture would be to reduce the in-function requirement to:

- Publish a metric
- Return an error or nil

```go
func handler(w http.ResponseWriter, r *http.Request) error {
  if !foo {
    return fmt.Errorf("not foo")
  }

  if err := thing(); err != nil {
    return fmt.Errorf("thing: %w", err)
  }

  if err := otherThing(); err != nil {
    return ErrorWithStatus(422, fmt.Errorf("thing: %w", err))
  }

  w.WriteHeader(200)
  w.Write([]byte("ok"))
}
```

Then, upstream in `ServerHTTP`:

```go
func ServerHTTP(w http.ResponseWriter, r *http.Request) {
  if err := handler(w, r); err != nil {
    logger.Debugf(err)

    var statusErr StatusError
    if errors.As(err, &statusErr) {
      http.Error(statusErr.Code(), statusErr.Text())
      return
    }

    w.WriteHeader(200)
  }
}
```

Not a totally flushed out design, but hopefully this describes my thinking a bit more

**Comment by radisef347** [comment]
![alt text](https://cdni.pornpics.com/1280/7/51/81056079/81056079_141_f080.jpg)

**Comment by sethvargo** [comment]
We could also roll up https://github.com/google/exposure-notifications-server/issues/350 here, to provide standardized debug responses vs production responses
