### ISSUE TITLE
implement optional export encryption

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#203]
/kind enhancement

**Comment by sethvargo** [comment]
Dropping my thoughts here from internal chat threads. Without additional information, I don't think we should tackle this just yet. It's unclear if PHAs are going to want symmetric or asymmetric keys, and I don't think this server implementation should be in the business of key management.

If we come up with a specification and PHAs agree, we can implement that spec.

**Comment by mikehelmick** [comment]
/close

We have decied not to move forward with this within the exposure notifications server.

If an app / server operator wanted to utilize encryption we would suggest using the export server here to write to storage and then encrypt those files with a separate process before placing them on the CDN.
