### ISSUE TITLE
cleanup: load test

### ISSUE THREAD

**Issue by crwilcox** [google/exposure-notifications-server#243]
Should verify how long a run takes at scale. Also verify it doesn't adversely impact table performance during cleanup.

**Comment by sethvargo** [comment]
@stati0n I think you mentioned you wanted to work on this.

**Comment by chaodaiG** [comment]
The first half was done in https://github.com/google/exposure-notifications-server/pull/713

Will need to figure out how to test this `Also verify it doesn't adversely impact table performance during cleanup.`

**Comment by stati0n** [comment]
@crwilcox is "table performance" in this case simultaneously inserting data while running cleanup?

**Comment by MushuEE** [comment]
@stati0n that is what I understand from syncing with @chaodaiG, I was going to try to repopulate the DB with a blob or docker image. Currently cleanup takes such a short time that it is hard to determine impact.

**Comment by MushuEE** [comment]
Finally have time to try and tackle this. 
Background for future me/others:

We use a postgres:12-alpine container to create the local integration/e2e test database. This is then populated in the test.

Plan is to pre-populate the database via either a standalone script or the test (I think I might want a standalone script to make the process more flexible and re-usable -if we want to increase / decrease database size-). Then store that blob backup either in source or gcs.  At the beginning of the tests we will restore from backup to pre-populate the db quickly. The current method of loading keys takes some time (~20m). This will hopefully both speed up the tests along with allowing much more data to be injected, enabling us to better gauge the cleanup impact.

Helpful commands
```
docker exec -it <name> pg_dump "dbname=en-server user=my-username password=abcd1234" > backup.sql
docker exec -it <name> psql "dbname=en-server user=my-username password=abcd1234" -c '\z'
```

**Comment by MushuEE** [comment]
@chaodaiG I am not sure what the next step to take here is. I was not able to go far past 100k Publishers and cleanup time seemed to never be impacted. If we need many more publishers I might need to expand the memory space of the postgress because I start getting failures at high numbers and my only idea is there could be a space issue with say 200k Publishers

**Comment by chaodaiG** [comment]
I think this either means the performance of cleanup is very great, or there were not enough exports generated. Could you try to log how many exports(exported files) were generated for 100k publishes?

**Comment by MushuEE** [comment]
Sure, will do

**Comment by MushuEE** [comment]
I believe this is verified. I ran a number of tests with up to 400,000 publishers or 5.6mil keys. This required me to change the export config timeout and max records:
```
	// Export
	exportConfig := &export.Config{
		CreateTimeout:  30 * time.Second,
		WorkerTimeout:  30 * time.Second,
		MinRecords:     1,
		PaddingRange:   1,
		MaxRecords:     25000,
		TruncateWindow: 1 * time.Second,
		MinWindowAge:   1 * time.Second,
		TTL:            336 * time.Hour,
	}
```
But the clean up time was not impacted much, only varying a slightly between runs of 100k, 200k, and 400k publishers being exported. The previous changes reduced the load time and it does not take more than 5 minutes for the largest tests.
![image](https://user-images.githubusercontent.com/7189267/96481620-6dfc3300-11f0-11eb-8c08-67d5c25bfceb.png)
