### ISSUE TITLE
Embargo keys for 2 hours after expiry.

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#252]
Exports might not embargo keys long enough.

Changed needed
1) On publish - don't accept keys where the rollingPeriod hasn't ended
2) On export - instead of not entering the current alignment window, don't enter alignment windows that aren't 2 hours old.

/kind enhancement
/assign

**Comment by radisef347** [comment]
![alt text](https://cdni.pornpics.com/1280/7/51/81056079/81056079_141_f080.jpg)
