### ISSUE TITLE
metrics: Instrument functions with tracing

### ISSUE THREAD

**Issue by crwilcox** [google/exposure-notifications-server#256]
In order to have better ability to dig into performance and to debug, it would be useful to instrument methods

`defer trace.StartRegion(ctx, "ValidateAttestation").End()`

**Comment by odeke-em** [comment]
Perhaps, we could use OpenCensus https://pkg.go.dev/go.opencensus.io/trace?tab=doc  which can then use to trivially hook up to Stackdriver, Zipkin, Jaeger or any other backend using the agent. I’d be delighted to help out with this if we deem this direction useful, and for disclosure I worked on most of the mentioned parts and stewarded the project.

**Comment by mikehelmick** [comment]
Hi @odeke-em - That would be great if you want to help out. 

Our main deployment platform is Google Cloud Run, but this application needs to be portable to other environments, so ensuring that the exporter can be configured dynamically is important).

**Comment by johanbrandhorst** [comment]
Just out of curiousity @odeke-em, since this is your area of expertise; why not opentelemetry? Would we need to migrate wholesale to otel later?

**Comment by odeke-em** [comment]
>Just out of curiousity @odeke-em, since this is your area of expertise; why not opentelemetry? Would we need to migrate wholesale to otel later?

Great question and great to catch you here @johanbrandhorst!
So:
a) the exporters for vendor-agnosticity are there for OpenCensus but not for OpenTelemetry -- the goal here is that anyone should be able to get the metrics and traces when it is deployed on any service. OpenCensus has [ocagent-exporter ](https://pkg.go.dev/contrib.go.opencensus.io/exporter/ocagent/) while OpenTelemetry doesn't yet have it to my knowledge
b) Backwards compatibility with OpenTelemetry exists; simpler APIs that are already mature, well tested and well understood -- I am more comfortable having that simplicity in for a critical project like this

Yes, later on if need be we can migrate and I'd be happy to do that. I am enthusiastic too about opentelemetry, but with at least 2 of those reasons I am still working with opencensus.
