### ISSUE TITLE
Allow AuthorizedApp to accept iOS and Android

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#269]
Allow for AuthorizedApp to dual home android and ios in the same row

(same bundle ID / app package name)

/kind enhancement

**Comment by mikehelmick** [comment]
/assign

Fixing this in tandem with #253

**Comment by mikehelmick** [comment]
/assign @sethvargo 

fixed, correct?

**Comment by sethvargo** [comment]
Gonna propose one more change to clarify which columns are for android and which are ios.
