### ISSUE TITLE
google_cloudbuild_trigger won't work for everyone

### ISSUE THREAD

**Issue by danawillow** [google/exposure-notifications-server#272]
The google_cloudbuild_trigger terraform resources in https://github.com/google/exposure-notifications-server/blob/master/terraform/main.tf create [GitHub app triggers](https://cloud.google.com/cloud-build/docs/automating-builds/create-github-app-triggers) which rebuild and push all the containers to GCR each time master is updated on this repo.

This resource won't work when running from an empty project- you have to first authorize the cloud build app with your github account, and connect it to the project you're running from, which can only be done in the UI. It also requires certain permissions on the repo, so most people will probably not be able to run it.

We have a few options:
1. Don't use cloud build triggers at all in Terraform, and build/deploy the containers separately. In this case we could still do it the first time with Terraform (basically with a basic script that calls out to `ko` a bunch of times) - we just wouldn't get new deployments automatically.
2. Use cloud build triggers, but have a dev/prod flag that turns on whether or not the trigger resource runs. In this case we would add the manual step to our docs as something to be done before running Terraform, and make the GitHub repo into variables so people can connect to their forks if they don't have permission to connect to this one.

Thoughts / other ideas?

cc @ndmckinley @sethvargo

**Comment by ndmckinley** [comment]
I'm inclined towards option 2 - I am in favor of minimizing flags, but also feel that up-to-date-ness is important enough to be worth one.

**Comment by sethvargo** [comment]
Prefer 2 as well
