### ISSUE TITLE
Community contributions assistance

### ISSUE THREAD

**Issue by johanbrandhorst** [google/exposure-notifications-server#280]
**Is your feature request related to a problem? Please describe.**
I'm a member of the public with expertise in this area and I'd like to help the project. I don't think I'm alone.

**Describe the solution you'd like**
* Github issue labels to guide project beginners to meaningful contributions (help-wanted/good-first-issue/etc).
* Some public discussion board where beginners can reach out to other contributors for quick feedback/assignment of work (Slack/Google groups/etc).

**Describe alternatives you've considered**
Trying to dive right into the issues as they are.

**Additional context**
This is perhaps the most meaningful open source contribution I could ever make. Please let me help you.

**Comment by sethvargo** [comment]
Hi @johanbrandhorst 

Thank you for opening an issue.

- We have a [good-first-issue label](https://github.com/google/exposure-notifications-server/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fgood-first-issue), and as a general rule, we always welcome more test coverage.

- You can use the email address [at the bottom of the README](https://github.com/google/exposure-notifications-server#issues-and-questions) to reach the team. We do not have any public real-time discussion forums like Slack at present.

Does that help?

**Comment by johanbrandhorst** [comment]
Great, not sure how I missed that label, that is very helpful. I gather that if I want to contribute on an issue that I should leave a comment on it to say so, to avoid duplicate effort?

**Comment by sethvargo** [comment]
Well, I just went through and labeled a bunch of things 😄. Yea, please drop a note.

**Comment by mikehelmick** [comment]
I tagged a few more issues.

As Seth mentions - we don't have realtime collaboration tools at the moment, and I don't think we'll be creating one in the near future. The email list in the README will reach the team at Google working on this project all at once. 


/close
