### ISSUE TITLE
run VACUUM on postgresql database

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#289]
**Is your feature request related to a problem? Please describe.**

The VACUUM command should be run periodically to ensure that deleted keys are removed from underlying storage and new keys aren't kept consecutively.

```VACUUM FULL VERBOSE```

**Describe the solution you'd like**

New job in `/cmd/vacuum`

Added to terraform config + cloud scheduler to run it.

/kind enhancement
/priority important-soon

**Comment by jba** [comment]
I suggest you look into autovacuum. It makes manual vacuuming unnecessary.

**Comment by mikehelmick** [comment]
looks like it is on by default

https://www.postgresql.org/docs/9.6/runtime-config-autovacuum.html#GUC-AUTOVACUUM

**Comment by sethvargo** [comment]
Is it on by default in Cloud SQL? https://cloud.google.com/sql/docs/postgres/flags

**Comment by mikehelmick** [comment]
I think we want to modify our DDL to enable this at the table level, at minimum on the exposure table.
