### ISSUE TITLE
Fast empty batch processing leads to rate limiting on Cloud Storage.

### ISSUE THREAD

**Issue by squee1945** [google/exposure-notifications-server#305]
When a single worker is rapidly moving through empty batches, the index file is written for each one. Re-writing an index file on an empty batch is desirable because it facilitates self-healing, but it in unnecessary to re-write the same index file multiple times within the scope of of single worker invocation.

**Comment by mikehelmick** [comment]
Do we need to write anything at all on an empty batch?

**Comment by gurayAlsac** [comment]
It's better the client get a 200 on an empty index and know there was
nothing to retrieve than get a 404 and wonder.

**Comment by squee1945** [comment]
Yes, the empty batch can get the empty index file out as soon as the ExportConfig is created, which helps the client. I also like it because it is good for general self-healing.
