### ISSUE TITLE
Consider renaming APIConfig

### ISSUE THREAD

**Issue by crwilcox** [google/exposure-notifications-server#315]
Due to it having Config in the name PR #313 has to name a config APIConfigConfig. 
Consider renaming this to perhaps `APIAccess` or `Authorization`. Getting Config out of the name could help.

**Comment by sethvargo** [comment]
My vote would be for `AuthorizedApp`

**Comment by radisef347** [comment]
![alt text](https://images.pornpics.com/1280/201909/07/8005161/8005161_020_3b87.jpg)
