### ISSUE TITLE
Error trying to run locally

### ISSUE THREAD

**Issue by sebagomez** [google/exposure-notifications-server#316]
When I run the `./scripts/dev` with the `dbstart` parameter, the container starts and stops immediately.

After getting the log I see the following message inside the container 

> FATAL: private key file "/var/lib/postgresql/server.key" must be owned by the database user or root

This is what I see if I bash into the container:
![image](https://user-images.githubusercontent.com/1637983/82128994-07cd3900-9796-11ea-82b6-487f65718392.png)

How can I change the owner?

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 using WSL2 Ubuntu 18.04

**Additional context**

**Comment by sethvargo** [comment]
Hi @sebagomez 

Thank you for opening an issue. We've tested the install script to work with Mac and Ubuntu, but I we haven't tried Windows with WSL. My best guess is that [this line](https://github.com/google/exposure-notifications-server/blob/d79bd811c1a1f7a7bd720e81442756bcfe9f64af/scripts/dev#L80-L82) is returning false on WSL, which doesn't modify the file permissions. It would be helpful to know the output of `uname -s` on your system.

**Comment by sebagomez** [comment]
Thanks @sethvargo for getting back to me so quickly.
`Linux` is what's returned by the command `uname -s` 

![image](https://user-images.githubusercontent.com/1637983/82131066-be85e500-97a7-11ea-82fe-ab49152c3a3a.png)

**Comment by sethvargo** [comment]
The startup script generates a TLS keypair and saves it in `./local`. The certificates need to be owned by the postgres (or root) user. I'm not very familiar with how filesystem permissions are mapped on WSL.

**Comment by sebagomez** [comment]
Yes, it is definitely a WSL2 thing... changing the  owner to root does nothing :(
I worked this around by disabling SSL on the Postgres connection. Thanks

**Comment by sethvargo** [comment]
Definitely don't disable SSL on Postgres in production. Since development is all on localhost, it's probably fine. I'll try and spin up a windows VM and test this out, but there are higher-priority things to resolve first.

**Comment by sebagomez** [comment]
I understand, but don't worry, it'll be secured with ssl in production.
Thanks

**Comment by bitcrazed** [comment]
@sebagomez I notice that you're storing your files under `/mnt/c/...` 

> ⚠ Note that the Linux DAC and Windows ACL security models are quite different. While WSL does it's best to synthesize DAC permissions from one's effective Windows ACLs, it can only do so much.
 
I am guessing that [the permission and ownership operations on your certs](https://github.com/google/exposure-notifications-server/blob/d79bd811c1a1f7a7bd720e81442756bcfe9f64af/scripts/dev#L78-L82) are not being set with adequate fidelity on files in your Windows filesystem.

I recommend moving your working files under your distro's ~/ folder (or similar).

The general rule of thumb with WSL2 is to store your files closest to the environment you're planning to host them in production. Thus, if you're planning on hosting your service in Linux, store your files INSIDE your distro's filesystem - this way your code, tests, and outputs etc. will all be running atop a real Linux environment.

**Comment by sebagomez** [comment]
Awesome Rich, that's was it, thanks!
Will keep that rule in mind.

Thank you all!
