### ISSUE TITLE
Documentation for how to run locally for testing purposes using minikube

### ISSUE THREAD

**Issue by will-weiss** [google/exposure-notifications-server#333]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I want to be able to run the project locally, but don't know where to begin.

**Describe the solution you'd like**
I'd love to see documentation with clear steps I can follow that would allow me to run all associated services within a local kubernetes cluster using minikube.

**Describe alternatives you've considered**
I considered having documentation describing how to get this set up locally using go running in the shell with additional steps for how to set up any associated services and which environment variables to set, but believe that this would involve more steps and be more error-prone, than using kubernetes.

**Additional context**

**Comment by mikehelmick** [comment]
/assign

Hello - thanks for the issue.

The quickest way to get up and running is with the script in `./scripts/dev`

It contains methods for starting a local postgresql Database (via docker), generating connection information.

Local servers can be run via

`go run ./cmd/exposure`

(to start the exposure publishing server).

Our target runtime during development has been the combination of Google’s Cloud SQL, Cloud Run, Cloud Storage, Secret Manager and KMS.

That being said, I have tested things out on kubernetes and should be able to provide a complete set of YAML files to deployment to Kubernetes + Knative. While Knative isn’t required, the severs were written to be serverless / autoscaled.

**Comment by crwilcox** [comment]
Adding on to what @mikehelmick has said. Further infrormation about onboarding/contributing can be found at https://github.com/google/exposure-notifications-server/blob/master/CONTRIBUTING.md. If anything in this document is unclear please feel free to open an issue so we can improve it for others.

**Comment by mikehelmick** [comment]
Adding a comment since this got marked as stale.

I still hope to get to this, but it is not at the top of the priority list yet.

**Comment by sethvargo** [comment]
@mikehelmick you can remove the label (using the label picker) and add kind/enhancement. It _shouldn't_ mark enhancements as stale.
