### ISSUE TITLE
Move off of gcr.io/cloud-builders/gcloud

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-server#357]
It's deprecated:

```
***** DEPRECATION NOTICE *****

This image is deprecated and will no longer be updated.
This recent version of the image will continue to exist.

In place of this image, please use one of the following
images from https://hub.docker.com/r/google/cloud-sdk/:

google/cloud-sdk
google/cloud-sdk:slim
google/cloud-sdk:alpine

Please note that these images support pinned versions
as well.

***** DEPRECATION NOTICE *****
```

**Comment by steren** [comment]
I asked for clarification internally.

gcr.io/cloud-builders/gcloud is used extensively all over the GCP docs. I doubt it's really deprecated (especially in favor of an image hosted on Dockerhub).

My guess is that the deprecation notice is deprecated :)

Please hold until we learn more from the Cloud Build team.

**Comment by mikehelmick** [comment]
@ImJasonH Can you provide any insight?

**Comment by ImJasonH** [comment]
The deprecation message should link to a bug or doc with more motivation, and should recommend gcr.io/google.com/cloudsdktool/cloud-sdk

The issue is https://github.com/GoogleCloudPlatform/cloud-builders/issues/638

cc @bendory

**Comment by bendory** [comment]
Yes -- you'll get that notice if you look in the repo (or build from `:latest`; the hosted service is not yet showing that deprecation notice to users, so I haven't yet done a full cleanup sweep.

**Comment by sethvargo** [comment]
The deprecation message says to use `google/cloud-sdk`, but @ImJasonH you're suggesting `gcr.io/google.com/cloudsdktool/cloud-sdk` instead?

**Comment by ImJasonH** [comment]
As @bendory said, the image you're using isn't rolled out to GCB yet, so users shouldn't be seeing this message at all today. I believe the intention is that the error message will be changed before it is rolled out.

**Comment by bendory** [comment]
Yes -- and indeed, this is already updated here in the repo.
Reference: https://github.com/GoogleCloudPlatform/cloud-builders/pull/674
