### ISSUE TITLE
Docs: draft deploy instructions

### ISSUE THREAD

**Issue by steren** [google/exposure-notifications-server#359]
The end of the [deploy instructions](https://github.com/google/exposure-notifications-server/blob/master/docs/deploying.md) are very raw, I am not sure I understand them:

![image](https://user-images.githubusercontent.com/360895/82282262-4276d300-9948-11ea-97e3-9ff1701e2286.png)

CC @llatif

**Comment by llatif** [comment]
This is being addressed in #362, cheers

**Comment by crwilcox** [comment]
Thanks @steren these were added to bridge a gap. As @llatif stated they are being touched up :)

**Comment by llatif** [comment]
Closing this as #362 as now been merged.
