### ISSUE TITLE
Potential issue with using `--no-traffic` in first deployments

### ISSUE THREAD

**Issue by steren** [google/exposure-notifications-server#360]
I see that [`builders/deploy.yaml` is deploying to Cloud Run with the `--no-traffic` flag](https://github.com/google/exposure-notifications-server/blob/56c1484ced445579b3fc603affb0496e2642579a/builders/deploy.yaml#L57).

The `--no-traffic` flag cannot be used when creating a new service, traffic will always reach the first revision. If used, the command errors out with the message:
```
Deployment failed
ERROR: (gcloud.run.deploy) --no-traffic not supported when creating a new service.
```

Is this script expected to be used to create the services? If so, I guess it would fail.

Stepping back, what is the rationale for using `--no-traffic`? 
Is the idea that traffic should be manually routed?

**Comment by mikehelmick** [comment]
I *think* that is being used for c/i only at the moment

**Comment by mikehelmick** [comment]
/assign @sethvargo 

The work in progress will make this clear.

Terraform for initial setup and this will be part of incremental, but not first, deploy
