### ISSUE TITLE
Questions about CDN and Notification in Google Cloud Hosted Solution

### ISSUE THREAD

**Issue by yuliumitre** [google/exposure-notifications-server#365]
I used terraform to deploy the whole solution to google cloud.  Does the current deployment include creating Cloud CDN for the client to download the key file? Where does the notification piece from the functional spec image sit at current stage? 

I guess my basic question is how the client gets the files after the scheduler is kicked off.  

Thanks a lot for any help.

**Comment by sethvargo** [comment]
Hi @yuliumitre 

Thank you for opening an issue. At present the Terraform configuration does not set up or configure Cloud CDN. We're still thinking through how to automate that process, since it requires you to own and validate a domain.

**Comment by yuliumitre** [comment]
Thanks for your quick response. 

We are working on a pilot APP now. What would be a best way for the client to get those key files?

**Comment by sethvargo** [comment]
They are in Google Cloud Storage. For local testing, that's probably fine, but would be expensive for production. That's where you'd want the CDN.

**Comment by yuliumitre** [comment]
@sethvargo Gotcha. Is there a plan to provide an API to allow the client to call to download those files from Cloud storage any time soon? Assume this is one of the two fundamental functionalities of the EN key server :-).

**Comment by sethvargo** [comment]
Hi @yuliumitre I believe that would be an API on the _client_, not the server. @mikehelmick for thoughts.

**Comment by yuliumitre** [comment]
I am thinking that if the server provide a list of URLs to the client for them to download based on the last time they request the files?

**Comment by gurayAlsac** [comment]
At the moment the server publishes an index.txt of all of the available downloads for the last 2 weeks (configurable). We recommend apps maintain the state of which URLs they've already downloaded - 
 a simple timestamp "high water mark" and URLs on exports including a timestamp would be easy. Soon the sample app will also reflect this behavior:
https://github.com/google/exposure-notifications-android

**Comment by yuliumitre** [comment]
Thanks for answering my questions.

**Comment by mikehelmick** [comment]
/close

Please reopen if we can be of further assistance.

**Comment by gurayAlsac** [comment]
Sample app code has been updated. You can see how its managing the index.txt and downloading the export files in https://github.com/google/exposure-notifications-android/blob/master/app/src/main/java/com/google/android/apps/exposurenotification/network/DiagnosisKeyDownloader.java
