### ISSUE TITLE
Question about export-config

### ISSUE THREAD

**Issue by yuliumitre** [google/exposure-notifications-server#382]
I am wondering who is supposed to add export-config.  It seems like the export worker and create-batch are relying on the export-config to generate key files. I saw there is a tool to create the export-config and it will be nice to add some documentation to explain this export flow.  Thanks in advance.

**Comment by mikehelmick** [comment]
/kind question
/assign

Configuing the export config is up to the operator.

It involves two steps - creating signature info objects for defining the signers for an export and then scheuling the export in export config.

We’ll work to get this process documented in the next couple days.

**Comment by yuliumitre** [comment]
@mikehelmick Thanks for your reply. We are working on a pilot app for our state and would like to use your reference server. For now, we just want the happy path of exporting to work. Would appreciate it if you guys could provide some explanation about this process at your earliest convenience.

**Comment by mikehelmick** [comment]
@yuliumitre - if you’re working on the official pilot app for your state, email us using the alias in the main README.md file and we can make sure that you’re getting the right level of support.

**Comment by mikehelmick** [comment]
After PR #435 - there is one more PR to go to make the system configurable via UI
