### ISSUE TITLE
When should Terraform stop?

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-server#386]
For discussion and thoughts @danawillow @ndmckinley @mikehelmick 

Right now, Terraform configures an empty GCP project with all the things required to run an EN server. It _also_ does the initial provisioning and deployment of the Cloud Run services.

However, we need to build, deploy, promote, scale-up/scale-down those Cloud Run services outside of Terraform. In GH-385, I found that Terraform gets reaaaalll unhappy when someone updates a Cloud Run revision outside of Terraform. It actually goes into an unconvergable state.

- Should Terraform build and deploy the Cloud Run services, or should it stop at setting up all the things and maybe spit out a gcloud command?
- If Terraform should manage all those services, how can we easily force it to re-build and deploy those containers?

**Comment by mikehelmick** [comment]
I would be happy with always deploying by modifying terraform configs, but it has to be able to build/deploy after first deploy.

**Comment by sethvargo** [comment]
I think the current challenge is that Terraform has no visibility into building images. We shell out to gcloud and submit a build to Cloud Build. In an _ideal world_:

- Terraform submits build to Cloud Build
- Cloud Build returns the image SHA
- The Cloud Run service depends on image SHA (thus creating a dependency)

But support for submitting/receiving build information from Cloud Build doesn't exist in Terraform (mostly because `gcloud builds submit` is actually 40 API calls to 5 different services). In lieu of that, I'm kinda leaning towards:

- Use Terraform for all the things + initial Cloud Run deployment
- Add `ignore_changes` to everything on Cloud Run services

**Comment by danawillow** [comment]
I think if you need to update the cloud run services outside of Terraform, it's going to be error-prone to try to use Terraform for them at all. We already do the initial deploy inside of cloud build; it wouldn't be too absurd to also create the services at that time with gcloud.

Would support for a Build resource/data source (https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds) help at all?

**Comment by sethvargo** [comment]
The problem is that we need information in the build output, like information from gcr

**Comment by krazykid** [comment]
I'm pretty new to TF and GCP, but have had pretty much a crash course on it in the last month and half. I was just wondering why not:
* Have TF create a Cloud Trigger which does:
  * Build
  * Deploy containers to Cloud Run (not shift traffic) via `gcloud run deploy ...` in the `cloudbuild.yaml` file
* Pull trigger (either through TF or hand)
* `terraform apply` the second half of deployment that handles manages the IAM permissions, etc. on the newly formed Cloud Run services

This way you still get CD with new pushes to github. 

Thanks for indulging my question.

**Comment by sethvargo** [comment]
Hi @krazykid 

We actually originally had a Cloud Build Trigger. There have been a few cases where we don't want continuous delivery (e.g. database migrations where we want to plan ahead).

**Comment by krazykid** [comment]
Thanks @sethvargo. Kind of a bummer that the trigger went away, but I get it. Could you have had the `cloudbuild.yaml` file handle the DB migration too? Just curious.
