### ISSUE TITLE
Where are the CI/CD tests run?

### ISSUE THREAD

**Issue by johanbrandhorst** [google/exposure-notifications-server#423]
Some of the issues are around testing, especially integration testing, and speeding up pipelines, but it's not clear to me where any CI/CD testing is run at the moment, and knowing more about the test environment is essential to being able to write appropriate tests, especially integration tests. I'd also be interested in contributing caching improvements to pipelines, since #422 implies that this is a bottleneck.

**Comment by johanbrandhorst** [comment]
Implementing https://github.com/google/exposure-notifications-server/pull/424 leads me to believe these are being run internally at Google at the moment. I'd love to help migrate this to something more accessible like CircleCI or Github actions or anything that could help bring more transparency.

**Comment by mikehelmick** [comment]
For CI we are using a Google hosted installation of [prow](https://github.com/kubernetes/test-infra/tree/master/prow)

At the moment, I could considering moving this a low priority item. We can examine opening up the output logs beyond Googlers if that's a concern.

**Comment by johanbrandhorst** [comment]
That would be great, but it would also be great to have visibility of the CI configuration. I couldn't find anything like a job definition file in the repo, except a Makefile and Dockerfile in https://github.com/google/exposure-notifications-server/tree/master/.prow/images/exposure-notifications-test which doesn't seem to actually run anything. Am I missing something?

**Comment by sethvargo** [comment]
You can run the tests locally with `./scripts/presubmit.sh`. That’s what CI runs. We have plans to move to a public instance of prow, but as Mike said, it’s lower priority than some other items.

**Comment by sethvargo** [comment]
Hey @johanbrandhorst - I'm going to close this out. We have threads running internally about moving to the public prow instance, but with GH-428, it should be super trivial to run `go test ./...` and the tests will setup any requirements. Let us know if you have any other questions and thanks for your contribution!

**Comment by johanbrandhorst** [comment]
Sure thing, the `scripts/presubmit.sh` was really all I needed, thanks!
