### ISSUE TITLE
Question about the key data file limits

### ISSUE THREAD

**Issue by LukasMasuch** [google/exposure-notifications-server#425]
With the most recent update of the exposure notification API, new limits got added for how many key data files can be checked for exposure matches. The daily limit is [15 for iOS](https://developer.apple.com/documentation/exposurenotification/enmanager/3586331-detectexposures) and [20 for Android](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf). The documentation of this reference server states that `the batch file generation should be per-region, incremental feeds of new data`. This new limit with the proposed periodically-generated and regional-separated files results in some complications. 

Let's take the following scenario as an example: It's 8pm and a user has switch on his smartphone for the first time since exactly two days. The batch creation is configured to generate a new key data file every 2 hours. This would result in 24 key data files that the client would need to check for exposure (= more than the daily limit). In case the user has also visited another country/region a few days ago, there would be an additional 24 key data files for the visited region.

Of course, there are some workarounds for this problem. For example, a longer period interval, daily aggregated key data files, key data files combining regional data, etc. But there will still be lots of corner cases where there are more key data files per day than the client limit would allow. Especially in the context of interoperability between regions. Do you already have recommendations or plans for the batch creation process to keep the number of packages within the new client limits?

**Comment by mikehelmick** [comment]
/assign @gurayAlsac 

The process of performing the file import and key matching is fairly CPU intensive. I believe the suggestion is to perform this operation while the phone is charging + on wifi if possible (i.e. nightly charging).

Our suggestion would be longer windows 6,12,24 hours and larger regions, likely country level. 

As for region interpretability. The federation API as specified in this project allows for servers to exchange keys in the background, an individual app would only ever have to pull keys for a single region.

Exactly how this federation would be put into place is still a point of ongoing discussion and we'll update the documentation when we have a solid recommendation.

**Comment by gurayAlsac** [comment]
Also note that the server needn't only provide export files at a single constant cadence. For example, it could provide files spanning multiple hours, days and even weeks all at the same time to offer client apps flexibility. In the case of a device that has been off for a while or has just newly begun to participate in the protocol, it may elect to consume these larger time span files to "catch up" without hitting quota limits.

**Comment by mikehelmick** [comment]
/close

please reopen if you feel this is still unanswered
