### ISSUE TITLE
Cloud run deployment shouldnt invoke --no-traffic for creating new services

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#430]
**Describe the bug**
./scripts/deploy fails in creating Google Cloud Run services 

Error : `ERROR: (gcloud.run.deploy) --no-traffic not supported when creating a new service.`

No Traffic options assumes at least one service version is deployed : https://cloud.google.com/sdk/gcloud/reference/run/deploy#--no-traffic

![Screenshot 2020-05-24 18 30 06](https://user-images.githubusercontent.com/666788/82770268-c7506980-9dec-11ea-80d8-15306557b4d5.png)

**Comment by mikehelmick** [comment]
Hi - did you use the terraform config to initialize the project first?

**Comment by sherifkozman** [comment]
The Terraform setup works pretty fine, but the README doesnt indicate that Terraform is a pre-requisite to use the setup scripts as they indicate possibility of using a custom DB connection to reliant over GCP Cloud SQL.

The README wording indicates that setup scripts can be used to build, run , deploy services on its own (excluding the data persistence layer(

**Comment by sherifkozman** [comment]
The wording may not be clear but it hints at using Terraform first. Please disregard the issue.
