### ISSUE TITLE
Exposure Key TTL is Too Short/Should be Handled by Clients Not Server

### ISSUE THREAD

**Issue by apmarshall** [google/exposure-notifications-server#433]
Caveat: I’m a golang novice and am not an epidemiologist, so perhaps this issue will be nonsensical. If so, I apologize.

After reading through this out of curiosity, I noticed something that doesn’t quite make sense to me. Currently, exposure keys effectively “expire” after a certain amount of time (default 336h/14 days), so whenever the cleanup routine is run keys older than that will be removed from the database. My understanding is that those keys only reflect people who are positive for the virus, thus creating a database that my phone can check against to see if I’ve been in contact with any of them.

I’m wondering if the 14-day rule should be a “client” concern and not a server concern. To explain: as far as I understand it, the incubation period for COVID-19 is believed to be no longer than 14 days, so if I’m more than 14 days out from being exposed to someone who was positive, I’m in the clear. However, that doesn’t necessarily work the other way around. If I’m positive for the virus, presumably there are a certain number of days for which I’m shedding the virus and therefore an exposure risk to anyone who encounters me. That number is probably variable from person to person, so let’s call the last day that I’m shedding the virus *f* (for final). So after day *f* I’m no longer a potential vector for transmission and after day *f + 14* no one who has encountered me is at any risk (from me). But we don’t necessarily know what *f* is, which means removing my key from the database after 14 days is almost certainly too soon: I was probably still a potential transmitter for some number of days after my first report. That said, for an individual client on someone’s phone, it would be safe to ignore my key if the last time they encountered me was more than 14 days ago.

I understand we don’t want the database to grow exponentially, so there needs to be some way of removing keys that are no longer relevant. There’s two ways I see to do this. The easy way would be to just change the default TTL to 14 + whatever the longest expected duration of someone shedding the virus is. The harder but probably more epidemiologically correct way would be to offer a “removal” mechanism parallel to the publishing process whereby I can certify that I am no longer positive and have my key marked as “deprecated” and set to be removed 14 days later. This should also probably result in the key being treated differently by the clients (ie, they only care about this key if their exposure was prior to the deprecation date, not after it).

Hope that’s helpful, thanks for all the work on this.

**Comment by sethvargo** [comment]
Hi @apmarshall - thank you for the feedback. 14 days is the current guidance from epidemiologists, but we designed the system to be configurable. If guidance should change, we can increase or decrease that number.

/kind question

**Comment by mikehelmick** [comment]
14 days is a hard number in the device (iOS + Android) APIs. They will ignore keys that are older than 14 days when matching is requested.

Reference: [Android API documentation v1.3.2](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf)

Our system allows for configurable storage, if an operator wanted to retain that information for longer, but after a key has aged bast the 14 day mark it can't be used for matching.

**Comment by apmarshall** [comment]
On further reading, I may have figured out how this works and found the answer to my own question. Correct me if I’m wrong:

Devices refresh their exposure keys at regular intervals. So a given device may be represented by multiple exposure keys in the database. This means that a given key doesn’t just represent a device, it represents that device at that time (interval). Therefore, deleting the key isn’t the same thing as marking a device “clean,” it’s more akin to saying “this contact window with this device is now too old to trigger notification.” Do I have that right? 

So presumably (and maybe this is based on client implementations?) an individual who had been verified as positive will continue submitting exposure keys to the database for as long as they are “positive,” thereby updating the time intervals during which contact with them might be an “exposure event.” Assuming I’m understanding how this is supposed to work correctly, now, then the 14-day window makes sense, as each key is a little more specific (device + time) than I initially understood (just device).

**Comment by mikehelmick** [comment]
Devices get new temporary exposure keys every day.

This reference server doesn't have a protocol implemented for continuously updating keys after the initial diagnosis. That's not to say that is prohibited in this model, but we haven't yet accounted for it.

/close

Feel free to reopen if you feel something has gone unanswered here. Thanks!
