### ISSUE TITLE
non-logs-based metrics

### ISSUE THREAD

**Issue by beggers** [google/exposure-notifications-server#437]
In GCP, and probably in some OSS solutions, logs-based metrics can be used solely to count the number of log lines matching a search. This doesn't work for things like latency distributions. We should use a real metrics framework like Prometheus.

**Comment by sethvargo** [comment]
We should probably use an abstraction here like https://github.com/armon/go-metrics and then have a default configuration for something like statsd or prometheus.

**Comment by beggers** [comment]
Agreed.

**Comment by mikehelmick** [comment]
There's already an abstraction for metrics, but going to a more common thing is 👍

**Comment by johanbrandhorst** [comment]
OpenCensus supports exposing Prometheus metrics, there's no need to add anything else. The existing tools already expose HTTP and gRPC metrics out of the box. I suggest reading up on OpenCensus.

cc @odeke-em
