### ISSUE TITLE
feat: Implement a storage backend for Azure Blob Storage

### ISSUE THREAD

**Issue by crwilcox** [google/exposure-notifications-server#459]
While there hasn't been an ask yet, it is possible folks will want to store on other cloud providers. 

https://github.com/google/exposure-notifications-server/tree/master/internal/storage contains a Google Cloud Storage and a Local File Storage implementation. It should be straightforward to implement the interface for Azure.

The interface is
```
type Blobstore interface {
	// CreateObject creates or overwrites an object in the storage system.
	CreateObject(ctx context.Context, bucket, objectName string, contents []byte) error

	// DeleteObject deltes an object or does nothing if the object doesn't exist.
	DeleteObject(ctx context.Context, bucket, objectName string) error
}
```

**Comment by mikehelmick** [comment]
@asutosh97 - pr #519 has this 

/assign @sethvargo
