### ISSUE TITLE
feat: Implement a storage backend for AWS S3

### ISSUE THREAD

**Issue by crwilcox** [google/exposure-notifications-server#460]
While there hasn't been an ask yet, it is possible folks will want to store on other cloud providers. 

https://github.com/google/exposure-notifications-server/tree/master/internal/storage contains a Google Cloud Storage and a Local File Storage implementation. It should be straightforward to implement the interface for AWS.

The interface is
```
type Blobstore interface {
	// CreateObject creates or overwrites an object in the storage system.
	CreateObject(ctx context.Context, bucket, objectName string, contents []byte) error

	// DeleteObject deltes an object or does nothing if the object doesn't exist.
	DeleteObject(ctx context.Context, bucket, objectName string) error
}
```

related to #459

**Comment by asutosh97** [comment]
@sethvargo shall i pick this up?
