### ISSUE TITLE
protoc-gen-go is deprecated?

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-server#466]
Build output:

```text
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
 A future release of golang/protobuf will delete this package,
 which has long been excluded from the compatibility promise.
```

We need to investigate why and what to do.

**Comment by mikehelmick** [comment]
This is due to the recent inclusion of open census as an exporter

```
exposure-notifications-server on 🌱 imports [$!] via 🐹 v1.14.2 
✦ ❯ go mod why github.com/golang/protobuf/protoc-gen-go/generator
# github.com/golang/protobuf/protoc-gen-go/generator
github.com/google/exposure-notifications-server/internal/observability
contrib.go.opencensus.io/exporter/ocagent
github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1
github.com/grpc-ecosystem/grpc-gateway/runtime
github.com/golang/protobuf/protoc-gen-go/generator
```

<remove oca contrib exporter from internal/observability>

```
exposure-notifications-server on 🌱 imports [$!] via 🐹 v1.14.2 
✦ ❯ go mod tidy

exposure-notifications-server on 🌱 imports [$!] via 🐹 v1.14.2 
✦ ❯ go mod verify
all modules verified

exposure-notifications-server on 🌱 imports [$!] via 🐹 v1.14.2 took 1m29s 
✦ ❯ go mod why github.com/golang/protobuf/protoc-gen-go/generator
# github.com/golang/protobuf/protoc-gen-go/generator
(main module does not need package github.com/golang/protobuf/protoc-gen-go/generator)

exposure-notifications-server on 🌱 imports [$!] via 🐹 v1.14.2 
✦ ❯ 
```

**Comment by mikehelmick** [comment]
@odeke-em - Any thoughts?

**Comment by odeke-em** [comment]
Thanks for bringing it to my notice, and apologies for the inconvenience!
Is this issue a blocker or preventing builds from passing? If so, we can
remove ocagent and in the background I’ll go work on re-generation of it.
If not, I’ll still work on re-generation of the libraries. That deprecation
seems recent (aka past 7 months or so) compared to when we last generated
opencensus-proto.

**Comment by mikehelmick** [comment]
Filed an issue here
https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/82

I put up
https://github.com/google/exposure-notifications-server/pull/467

to temporarily remove this from the code. If you could work on getting this fixed and restoring, that would be awesome.

**Comment by odeke-em** [comment]
Thanks for the file! I've sent a PR fixing it to the ocagent-exporter repository per https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/83. The issue was that the grpc-gateway dependency version was old and needed an update.
