### ISSUE TITLE
Move to per-service database credentials and POLP

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-server#471]
Right now, we share a single database login that basically has `root` on the database with all the services. We should:

1. Define the minimal set of database interactions for each service
1. Create a unique user and cert for each service
1. Grant services access to only those credentials
1. Provision the schema permissions using [the Postgres provider](https://www.terraform.io/docs/providers/postgresql/r/postgresql_grant.html)

**Comment by mikehelmick** [comment]
if we do this, we'll need to issue a cert for the admin console that can write to all the config tables
