### ISSUE TITLE
Optimal EXPORT_FILE_MAX_RECORDS in production

### ISSUE THREAD

**Issue by varshithr** [google/exposure-notifications-server#481]
### Question
Hey guys,
Considering Android and iOS deployments, what's the optimal size(number of keys) per batch size in a production environment?

**Comment by gurayAlsac** [comment]
The short answer is that it depends. :) We recommend instrumenting apps to see how they are handling the export files and adjusting accordingly. If you are doing a single daily export and the apps wait overnight to download and process it, you can probably have larger files. Our loose upper bound recommendation in the [file format spec](https://www.google.com/covid19/exposurenotifications/pdfs/Exposure-Key-File-Format-and-Verification.pdf) has been about 750K keys, which is [aligned with Apple's](https://developer.apple.com/documentation/exposurenotification/setting_up_an_exposure_notification_server#3591262). More frequent exports might want to reduce the size.

**Comment by varshithr** [comment]
Thank you @gurayAlsac 
You have been of great help :)
