### ISSUE TITLE
VerifySafetyNet not called for DualPlatform devices

### ISSUE THREAD

**Issue by alpe** [google/exposure-notifications-server#482]
### TL;DR
DualPlatform devices are treated as IOS only due to the `else` in 
https://github.com/google/exposure-notifications-server/blob/master/internal/publish/publish.go#L140

**Expected behavior**
I assume to be correct you want to verify against both OS platforms.

**Observed behavior**
Just reading the code. Unfortunately setup complexity is a bit too high to provide a unit test.

### Reproduction
- 
**Screenshots**
- 

**Environment**
-

**Additional information**
-

**Comment by mikehelmick** [comment]
Thanks for the bug report - I have a fix out for review.
