### ISSUE TITLE
Multiple Apps handling within database

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#489]
### Question
The Sample tool hints at the possibility of configuring multiple mobile apps within the same server environment.
Can apps using the same server and different bundle ID utlize checking exposure keys intersections in the same database.
Are keys/data isolated per app on the database/server level ?

**Comment by sethvargo** [comment]
Hi @sherifkozman - thank you for asking a question. The server is designed to be multi-tenant and can work with multiple applications simultaneously. It can also support dual apps for both iOS and Android as a single config, provided they use the same application bundle ID.

**Comment by mikehelmick** [comment]
Keys are stored in the same database.

Keys are associated with one or more regions, and exports can get data from one or more regions.

One could imagine where there are mobile apps for every US state, all writing to their state's region, i.e "CT", "NY", "PA" and an export file that pulls in all 50 states for a country wide export.

It is also possible to have the uploads and exports to be totally disjointed (true multi-tenant)

**Comment by sherifkozman** [comment]
@sethvargo @mikehelmick Thanks for the response. I guess my question would be then : 
What is the default behaviour of exposure notification if multiple application/bundle_IDs are configured within the same deployment.
i.e 
1st app : com.app.state1 (Region NY)
2nd app : com.app.state2 (Region CA)
What would be the expected default behaviour if a user from app1 reported postive crosspath with user from app2

Is there any configs to change the EN behaviour or it is yet to be determined?

**Comment by gurayAlsac** [comment]
As Mike was saying, this behavior is configurable. You can either generate exports for a region containing only keys from that region, or broadcast all keys from all regions to all regions. See the OutputRegion and InputRegion parameters of ExportConfig in https://github.com/google/exposure-notifications-server/blob/5647421d17c89205f2a1f1aa73288f3cc78b4fa8/internal/export/model/export_model.go#L39

In your example, if `InputRegion = ['NY','CA']` and `OutputRegion = ['US']`, and app1 and app2 both download exports for 'US' region, then if userA uploads a positive verification via app1 to the backend, and userB's app2 downloads US exports from the same backend, userB would eventually get notified of an exposure if they observed any of userA's keys.

A shared backend is one way in which apps for different regions could interoperate. Apps could also use different backends and have those backends explicitly share data with each other. See for example the federationin/federationout servers in this repo.

**Comment by sherifkozman** [comment]
Great aproach, thanks for the clarification folks.
