### ISSUE TITLE
External Federated ingest/upload

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#491]
### Question
There are mentions within the functionl componeses and server cloud run deployments about federated ingest of data through third parties.
What kind of ingest is expected to be as a sample use case, given that all ingest workflow between client-server should be follow a specific flow such as verification of App ID ?=

**Comment by mikehelmick** [comment]
Let me know if this isn't exactly the answer that you're looking for.

The idea behind federation is to cover 2 scenarios

1. Multiple apps / servers covering the same geographic area
2. Travellers across geographies.

We've kept things fairly loose as there are lots of different scenarios our partners have considered as they go about this.

For 1 - imagine that Washington and Oregon are each operating their own server, but we want share keys across the states. If both severs are using a region of "US" they can share keys via federation.

For 2 -  The idea would be that you would allow for collection of other regions that a person has travelled to and federate that date to the home country/region.

**Comment by sherifkozman** [comment]
Thanks for the clarification, i guess i was thrown off by the term "Ingestion of keys from other parties" within the documentation here : https://github.com/google/exposure-notifications-server/blob/master/docs/server_deployment_options.md
