### ISSUE TITLE
OpenAPI/Swagger Specs for API endpoints

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#495]
### Question
Is there any OpenAPI/Swagger specs available for the services enpoints.
To enhance security deployment for public facing services we are testing exposing them through Cloud endpoints with additional authenticaion layer. Cloud endpoints require OpenAPI specs to define the different endpoints
thanks

**Comment by mikehelmick** [comment]
/kind enhancement

Not at this time, but something we can add.

This codebase intentionally doesn’t include authententication as we don’t provide any kind of account / identity managment or integration.

Also take a look at #349 - We are in the process of rolling out diagnisis verification through signed JWTs which would provide authentication, but is handled within the server.

**Comment by sherifkozman** [comment]
Great, I will keep an eye on that as well.

I understand the reason behind not implementing authentication this is why we were exploring cloud endpoints as an external implementation that isn’t coupled with the server, hence the openapi spec.

**Comment by sethvargo** [comment]
Hi @sherifkozman are you looped into the plans re: #493. The longer-term plan is to allow PHAs to employ their own authentication requirements via a token verification system.

**Comment by sherifkozman** [comment]
@sethvargo i wasnt but @mikehelmick looped me onto #349 , i took a look at #493 however requesting OpenAPI specs was in relation to API management and endpoint security, monitoring through cloud endpoints which doesnt conflict with the token verification system proposal.

Thanks for keeping me looped in as we are testing the deployment in different modes so we can enable more HAs to be able to deploy it in various environment configurations.

**Comment by mikehelmick** [comment]
Not quite swagger - but we have this in a common package now that can be imported into other codebases.

**Comment by sherifkozman** [comment]
Thanks @mikehelmick thats useful for devs who will be willing to build on top of the work done.
My main interest in OpenAPI spec or swagger was in relation defining and  running Cloud endpoints on top of the Cloud run services to enable more control over the exposure Cloud Run Service.
This would enable an HA to add an additional layer for API control and monitoring either with Cloud run or within an GKE deployment.

**Comment by lmartensson** [comment]
Thanks @mikehelmick - is there any progress on the API specification Sherif is requesting?
I just spent well over an hour trying to dig through the code and help one of our app developers figure out what endpoints he can call, but I'm really not doing too well.

**Comment by mikehelmick** [comment]
Hi - no progress to report. 

We do have our documentation that talks about how to call the publish API: https://google.github.io/exposure-notifications-server/
This includes the sample App with an integration to the API.

If someone wants to contribute this, we would be happy to review it.

**Comment by mattThousand** [comment]
@mikehelmick we are using the Apple iOS sample code as reference for our iOS client implementation. Does this server contain endpoints for the following requests "out of the box" or would they need to be added?

```- postDiagnosisKeys(diagnosisKeys: [ENTemporaryExposureKey]) 
- getDiagnosisKeyFileURLs(startingAt index: Int) 
- downloadDiagnosisKeyFile(at remoteURL: URL)
- deleteDiagnosisKeyFile(at localURL: URL)
- getExposureConfiguration()```

thanks for your work on this!

**Comment by mikehelmick** [comment]
I'm not familiar w/ the iOS device side APIs.

Assuming it works similar to the Android counterparts, the actual URL for both publishing and downloading is up to the developer.

The various OS implementations are responsible for verifying the signature of the requested key files and if it matches will run the key matching algorithm.

The actual URLs for the upload/download pieces need to be provided by your sever operator (which may be you depending on jurisdiction)

**Comment by mattThousand** [comment]
@mikehelmick just to confirm, only the publishing/downloading urls are provided "out of the box" (i.e. fetching the exposure configuration is not)

**Comment by mikehelmick** [comment]
I'm going to say "correct" - because I don't know what the exposure configuration. I'm guessing that communicated w/ an apple server?

**Comment by sherifkozman** [comment]
@mikehelmick I will echo @mattThousand here and his question. In the current exposure notification server deployment there are 6 running services , only 2 with public endpoints (exposure and federationout)
@mattThousand was trying to figure if one would be used for submitting exposure keys and the other would be used to download the index of the server key exposure files through GCS or did we miss anything?

**Comment by mikehelmick** [comment]
Ah - thanks, I missed that in the question

The exposure service is used to upload keys from the device.
The export files (including the index) are only available on the GCS bucket (ideally fronted by Cloud CDN)

@llatif @crwilcox - can we double check docs?

**Comment by sherifkozman** [comment]
@mikehelmick ok so the index file is hosted and updated over the GCS bucket along with the exposure keys. if i got that correctly then its worth checking the docs to clarify that a bit more over the docs.
Thanks

**Comment by mattThousand** [comment]
@mikehelmick can you offer any guidance on requesting the `index` file for individual regions? Is there a query parameter that should be passed in the network request? Or is the idea that a mobile client will always request the `index` file for "all" regions?

**Comment by mikehelmick** [comment]
Currnetly that’s an agreement between the app and server operator. I think in most cases, it will be a single index file for a region / for an app.

I filed #608 last week to enhance this.
