### ISSUE TITLE
Federated learning (privacy preserving) for better risk assessment 

### ISSUE THREAD

**Issue by mkwiecinski** [google/exposure-notifications-server#496]
Risk assessment is currently availabile in API as a deterministic function of 4 parameters (all with low variability). If more data were available in API (eg continuous BT signal strength) one could employ (privacy preserving) federated machine learning, managed on the server side, for better (AI-based) risk assessment.

I understand the concept of privacy preserving federated learning might not be possible to achieve in absolute terms, although I have not done such assessment myself. Looking for individuals who considered feasibility of this approach.

Side question: have Google already considered that?

**Comment by mikehelmick** [comment]
/kind question

Yes that has been discussed, but I have no details to share.
The current decentralized approach will deliver results while maintaining user privacy.
