### ISSUE TITLE
Questions about the federation API

### ISSUE THREAD

**Issue by LukasMasuch** [google/exposure-notifications-server#529]
I had a closer look on the federation API and have a few open questions. I really like a lot of aspects of the current implementation, but assume that its still an initial version and some of the questions might not have a proper answer yet. 

1) What is the purpose of the `fetchType` property in the `FederationFetchRequest` message?
2) Why are the regions as well as the transmission risk separated from the keys in the `FederationFetchResponse`? In case there is no significant benefit, I assume that the following protobuf format might simplify a few aspects:
	```protobuf
	message FederationFetchResponse {
		repeated ExposureKey keys = 1;
		bool partialResponse = 2; 
		string nextFetchToken = 3;
		int64 fetchResponseKeyTimestamp = 4;
	}

	message ExposureKey {
		bytes exposureKey = 1;
		int32 intervalNumber = 2;
		int32 intervalCount = 3;
		int32 transmissionRisk = 1;
		repeated string regionIdentifiers = 2;
	}
	```
3) The federation format uses the property names `interval_number` and `interval_count`, while the export format uses `rolling_start_interval_number` and `rolling_period`. Is there a specific reason for the naming difference?
4) The `transmissionRisk` is currently exchanged between the backends without applying any changes. However, based on the current documentation the `transmissionRisk` can be freely defined by the health authority of every country. So, I assume that there might be diverging definitions between different countries. Is this something that is planned to be addressed within the federation API (e.g. configure `transmissionRisk` mappings)?
5) Is a more official technical specification planned for the federation API within the next few days or weeks (similar to the export format)?

**Comment by squee1945** [comment]
1. `fetchType` - this is unused and should be removed.
2. The original proto was designed to minimize on-the-wire transmission size. Given this is server-to-server, this is really a much smaller concern, though I'd have to look into current usage to know if we can change something here.
3. naming difference - only an oversight that needs to be cleaned up
4. `transmissionRisk` - I don't know much about this and will have to get back to you.
5. As above, I don't know the plan at the moment for a federation API, but it seems likely in order to get appropriate server-to-server operation.

**Comment by LukasMasuch** [comment]
@squee1945 Thanks for the fast response. This answers my questions for now :) 
2. Since the daily server-to-server transmission size is probably just a few MB, I would personally prefer to keep the federation data format very close to how it is stored in the database (this makes it a bit simpler).
5. Within the EU there is a bit of pressure to get all the national systems interoperable as soon as possible. In order to not have all backend implementation come up with their own federation API, I would really appreciated to have some documentation on that topic from Apple/Google as well.
