### ISSUE TITLE
Clarifying Deployment Instructions

### ISSUE THREAD

**Issue by crwilcox** [google/exposure-notifications-server#542]
While chatting I have heard that our instructions for deploying could be clearer. Specifically, it seems it is unclear what needs to be done while re-deploying. We should review the documentation and consider if there are ways to clarify things.

**Comment by sethvargo** [comment]
It's mostly [documented here](https://github.com/google/exposure-notifications-server/blob/master/docs/deploying.md#running-services). It'd be helpful to have more actionable feedback (where are people stuck, what errors are they getting, etc).

**Comment by crwilcox** [comment]
@sethvargo 💯 

I plan to walk through them with open eyes and see if there aren't places we could provide clarity

@sherifkozman can you provide specific ways in which you (and folks you work with) may have gotten lead astray or stuck?

**Comment by sherifkozman** [comment]
@sethvargo @crwilcox we managed to get things running quickly however working with a few HAs over the GCP deployment we found a few issues :

- Using terraform to provision initial infrastructure doesnt enable the required permissions for Cloud build to complete some of the required tasks.

- I believe there was a case where resources manager API needs to be enabled for new projects so deployment can be complete.

- Other HAs have mentioned they are unable to find enough on deployment eslewhere on other providers or what is required to manage the update/deployment equivilent of the /scripts folder on other environments.

I am happy to join on a call anytime to dicuss any of the topics

**Comment by sethvargo** [comment]
Hi @sherifkozman 

Thanks for the feedback.

> Using terraform to provision initial infrastructure doesnt enable the required permissions for Cloud build to complete some of the required tasks.

Do you know which permissions are missing? I just tried in a clean project yesterday and it ran successfully to completion (took 13min).

> I believe there was a case where resources manager API needs to be enabled for new projects so deployment can be complete.

Terraform enables the resource manager API. We do require that billing is configured on the project.

> Other HAs have mentioned they are unable to find enough on deployment eslewhere on other providers or what is required to manage the update/deployment equivilent of the /scripts folder on other environments.

We're currently focused on GCP because that's where our expertise are. Other cloud providers can be found here: https://www.terraform.io/docs/providers/index.html.

**Comment by sherifkozman** [comment]
Hey @sethvargo A new GCP project would have these permissions disabled by default 
https://console.cloud.google.com/cloud-build/settings/service-account

I believe a deployment will need Cloud Run, KMS , Service account enabled for Cloud build. I believe they would be impacted by the Resource Manager API being disabled by default as the deployment fails as being unable to "setIamPolicy" for services such as KMS Keys.

I have seen this behaviour in a couple of projects where terraform doesnt enable the resources manager API so things fall off from there.

**Comment by sethvargo** [comment]
Here's the [list of APIs we enable](https://github.com/google/exposure-notifications-server/blob/da68cc3cc512c8ae0cfdbcf11917564fed3dde5c/terraform/main.tf#L36-L47) - we could add `cloudresourcemanager.googleapis.com` to that list. Cloud Run and Cloud KMS are already in that list.

- Cloud Build is already given [permission to manage Cloud Run services](https://github.com/google/exposure-notifications-server/blob/da68cc3cc512c8ae0cfdbcf11917564fed3dde5c/terraform/main.tf#L107-L117) (including deploy)

- Cloud Build does _not_ need permission to use or access the KMS keys. That is and should continue to be restricted to the specific services.

Are these hypothetical issues or are your Terraform runs failing? If they are failing, can you please share the `terraform apply` output?

**Comment by sraybuck** [comment]
Hi all, I'm new to GCP and Terraform and while trying to get this working I consistently ran into errors when following the Terraform doc when I would use the optional settings like "create_generate_service = true" and [these](https://github.com/google/exposure-notifications-server/tree/master/terraform#local-development-and-testing-example-deployment) settings, which get put into a terraform.tfvars file. When I ran terraform apply I would get some variation of this error: 
```
google_sql_database_instance.db-inst: Creating...

Error: Error, failed to create instance en-koqlo: googleapi: Error 400: Value requested is not valid., invalidFlagValue

  on database.tf line 22, in resource "google_sql_database_instance" "db-inst":
  22: resource "google_sql_database_instance" "db-inst" {
```
which is less than helpful. From what I can tell, it seems like whenever there were variables in terraform.tfvars that overwrote variables in vars.tf or database.tf, I got a invalidFlagValue error and Terraform failed. I eventually got around it by just changing the values in database.tf but I consistently got that error when I followed the docs. 

The contents of terraform.tfvars that would cause the error looked like this:
```
project               = "project-name"
cloudsql_tier         = "db-custom-1-3840"
cloudsql_disk_size_gb = "16"
create_generate_service = true
```
and I got it to work after I gave up on the cloudsql_tier and create_generate_service options and changed the cloudsql_disk_size_gb option in database.tf

**Comment by sethvargo** [comment]
Hi @sraybuck 

Thank you for the feedback. The way to enable the generate service is a bit out of date. I updated it in GH-572. 

I believe the issue is with the `max_connections` flag. We bumped this value to 100,000, but that might exceed the possible value for a smaller db instance.

**Comment by sherifkozman** [comment]
@sethvargo bumping the max_connections = 10000 when setting db_tier to db-custom-1-3840 causing terraform to crash resulting in : 
Error, failed to update instance settings for : googleapi: Error 400: Value requested is not valid., invalidFlagValue

**Comment by sethvargo** [comment]
GH-576

**Comment by sethvargo** [comment]
Can you try removing lines 33-41 in database.tf and seeing what you get? That error is coming from the Cloud SQL API, and I agree it's not very informative.

**Comment by sherifkozman** [comment]
According to the CloudSQL documentation this flag is still in beta and by default Cloud SQL sets the max connections depending on the machine type.
I fixed it by setting a lower value
https://cloud.google.com/sql/docs/postgres/quotas
