### ISSUE TITLE
Evaluate holding current day's key

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#543]
Currently, a key that is still valid (rolling period + rolling period count covers the current time) causes a whole publish API request to fail.

As this has come up a couple of times, perhaps it is better to hold the still valid key until the end of the UTC day, but allow others to be sent out immediately. 

/assign

**Comment by crwilcox** [comment]
To be clear, this is to handle a still valid key being uploaded. Rather than rejecting the publish, we would embargo that key, not including it in any batches, until after it has expired + additional time to handle skew?

**Comment by mikehelmick** [comment]
Correct.
