### ISSUE TITLE
server_functional_requirements.md needs to be modified with current addition of HMAC in the payload

### ISSUE THREAD

**Issue by xyz23** [google/exposure-notifications-server#544]
### TL;DR

https://github.com/google/exposure-notifications-server/blob/master/docs/server_functional_requirements.md

Sample payload is missing HMAC in the request.

```json
{
  "temporaryExposureKeys": [
    {"key": "base64 KEY1", "rollingStartNumber": 12345, "rollingPeriod": 144, "transmissionRisk": 5},
    {"key": "base64 KEY2", "rollingStartNumber": 12489, "rollingPeriod": 10, "transmissionRisk": 6},
    {"key": "base64 KEYN", "rollingStartNumber": 12499, "rollingPeriod": 100, "transmissionRisk": 7}],
  "regions": ["US", "CA", "MX"],
  "appPackageName": "com.foo.app",
  "verificationPayload": "signature /code from  of verifying authority",
  "padding": "random string data..."
}
```

**Expected behavior**

Should have HMAC added in the sample payload

**Comment by sethvargo** [comment]
Hi @xyz23 - can you provide more information? What kind of HMAC are you expecting?

**Comment by mikehelmick** [comment]
/assign

The HMAC value isn't actually part of the request, the HMAC key is.

I'll get it updated and link to the PHA verification certificate design
