### ISSUE TITLE
Docs: change to "Diagnosis Key Server"

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#556]
In all docs, this sever should be referred to as the "Diagnosis Key Server" to match language with the rest of the ecosystem.

/assign @crwilcox @llatif

**Comment by mikehelmick** [comment]
sounds like we want this to just be "key server" or "exposure notifications key server"

**Comment by crwilcox** [comment]
10 mentions of 'key' in our docs currently. https://github.com/google/exposure-notifications-server/search?q=extension%3Amd+key&unscoped_q=extension%3Amd+key

PR incoming for a few mentions of 'tracing key'
