### ISSUE TITLE
Terraform is missing cloud-sql client permissions for service accounts

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#578]
### TL;DR
Service Accounts associated with Cloud run are missing a required Cloud-sql client permission that was available before.

The following config seems to have got removed causing cloud run services ro fail : 

resource "google_project_iam_member" "exposure-cloudsql" {
  project = data.google_project.project.project_id
  role    = "roles/cloudsql.client"
  member  = "serviceAccount:${google_service_account.exposure.email}"
}

**Comment by sherifkozman** [comment]
@mikehelmick i submitted a PR with the fix if it will help.
#579

**Comment by sethvargo** [comment]
I commented on the PR, but the Cloud Run services should _not_ need this permission. They communicate with Cloud SQL over a local VPN, and thus the Cloud SQL proxy (which is what requires the IAM permission) is no longer required for this setup.
