### ISSUE TITLE
Implement authorized app prefix matching

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#586]
### TL;DR

For development purposes - it would be nice to allow the authorized app allow-list to match AppPackageName/BundleID by prefix

### Design

**Proposal**

likely needs column in database to indicate if prefix match is allowed.

The cache is currently by exact match. This would involve adding the ability to to an exact match and then a prefix match.

/kind enhancement

**Comment by sethvargo** [comment]
Radix trees! (somehow every Go project I work on inevitably needs a radix tree)
