### ISSUE TITLE
logging request

### ISSUE THREAD

**Issue by laurentsimon** [google/exposure-notifications-server#588]
we're logging the request in [publish.go#L121](https://github.com/google/exposure-notifications-server/blob/master/internal/publish/publish.go#L121) if there's a server config problem.

If someone gets access to the log, they may ask PHA which device/user generated these.

The risk is low, since it's a config error.

I wanted to double-check with you if you think that's OK or not.

**Comment by mikehelmick** [comment]
It's logging the error from the lookup, which would contain the AppPackageName/BundleID and not anything else from the request.

I'll add a comment there to clarify what is actually being logged.

/assign
