### ISSUE TITLE
what is BypassHealthAuthorityVerification

### ISSUE THREAD

**Issue by laurentsimon** [google/exposure-notifications-server#589]
Is this [flag used for testing](https://github.com/google/exposure-notifications-server/blob/master/internal/publish/publish.go#L151)?

Or is it used for the self-reporting case? If for self-reporting, are we sure the data field is populated after calling [VerifyDiagnosisCertificate()](https://github.com/google/exposure-notifications-server/blob/master/internal/publish/publish.go#L149)?

I did not see (I may have missed) any particular flag being set in the database record for a self-reported upload vs a HA-vetted upload. Are we flagging those in any way?

**Comment by mikehelmick** [comment]
This is just meant for testing.

Currently there is no server available to actually issue these certificates, so for end to end tests we are bypassing verification.

/assign

**Comment by mikehelmick** [comment]
Also - self-reporting is an issue for public health authorities. If they are willing to sign a JWT for a self report - then this server will accept it.

/close
