### ISSUE TITLE
Audience claim guideline

### ISSUE THREAD

**Issue by laurentsimon** [google/exposure-notifications-server#590]
do we provide guidance about what the [Audience claim](https://github.com/google/exposure-notifications-server/blob/f165fa56b432ad25400e7c2b54640a98c6cb7447/internal/verification/database/health_authority_db_test.go#L43) should be set to?

**Comment by mikehelmick** [comment]
/assign

It's up to the server operator. This should be added to the configuration docs.

/cc @crwilcox in case he wants to take this on.
