### ISSUE TITLE
is TEK db always local

### ISSUE THREAD

**Issue by laurentsimon** [google/exposure-notifications-server#591]
is the [TEK db](https://github.com/google/exposure-notifications-server/blob/f165fa56b432ad25400e7c2b54640a98c6cb7447/internal/verification/phaverify.go#L74) always local?

If we allow the db to live on a different host, do we warn them about the danger, i.e. do we tell them to secure the transport between the host and the db?

**Comment by mikehelmick** [comment]
We should assume that the DB is never on localhost.

Our default configuration - https://github.com/google/exposure-notifications-server/tree/master/terraform

Sets up PostgreSQL SSL certificate based authentication with the certs stored in secret manager and accessed by the service account that the server runs as.

Let us know if you think further documentation is warranted.

**Comment by laurentsimon** [comment]
Seems pretty good. Please close the issue.
