### ISSUE TITLE
is ThruDate updatable?

### ISSUE THREAD

**Issue by laurentsimon** [google/exposure-notifications-server#592]
Is the [ThruDate](https://github.com/google/exposure-notifications-server/blob/9e35fa5d4893d8479a067398be1b1eb2ed7308fb/internal/admin/healthauthority/form.go#L36) field updatable?

When the admin performs key rotation, they ought to be able t change the expiry time of the previous key. Maybe this is done automatically?

**Comment by mikehelmick** [comment]
Yes, it is updatable. See attached admin UI.

Typically, I would expect that keys are created w/ a blank THRU time.
When a user presses the "revoke" button, the thru time is set to now.

![image](https://user-images.githubusercontent.com/92319/84215283-a2a9f200-aa7a-11ea-988d-07e69dcac7f5.png)

**Comment by laurentsimon** [comment]
great. Please close the issue.
