### ISSUE TITLE
revocation certificate

### ISSUE THREAD

**Issue by laurentsimon** [google/exposure-notifications-server#597]
according to the [design doc](https://docs.google.com/document/d/1XS63ghPfrlVqNeAIM6d5eGhHiB3Shmk8hEdSp13f0-8/), the server should return a certificate which can be used later to delete TEKs. I did not find the implementation.

Beware that the doc suggests using AES-GCM and we can only encrypt 2^32 messages (i.e., certificates) with the same key. Since the server may support self-reported upload, we cannot really stop someone from submitting many request... or can we?

So we may want to use a different AEAD and/or implement key automatic rotation. A different AEAD would simplify the implementation if we select one that has an 'infinite' bound on the number of messages that can be encrypted: I think Xchacha20-Poly1305 or AES-GCM-SIV have better properties than AES-GCM for this. Will need to double check depending on which solution we select, if any.

**Comment by mikehelmick** [comment]
The issuance of revocation certifications is currently on hold for this server as we believe our automated, time-based data deletion is sufficient.

**Comment by laurentsimon** [comment]
I see. Shall we update the design doc
<https://docs.google.com/document/d/1XS63ghPfrlVqNeAIM6d5eGhHiB3Shmk8hEdSp13f0-8>
to
reflect this?

**Comment by mikehelmick** [comment]
I'm going to close this. There's nothing actionable on this repo at this time. The referenced doc isn't public at this time.

/close
