### ISSUE TITLE
Export config - groups

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#608]
### TL;DR

Allow for multi-period export config to be explicit in the server.

For example, daily exports combined with 4 hour exports.

All of a clean mapping for a device to understand which export files to process to get complete coverage in the event of being offline for multiple days.

Currently, the understanding of the index.txt is rather opaque.

/kind enhancement
/assign

**Comment by gurayAlsac** [comment]
I can hold onto this for time being. We may not need "catch up" files after all if we get the right sort of flexibility into the api.

**Comment by mikehelmick** [comment]
keep alive

**Comment by gurayAlsac** [comment]
After v1.5 we won't need the notion of catch-up files as the api can be called with multiple whole batches, so we probably don't need to support more complexity in grouping generated files by frequency. If servers find they need to do this for pre-v1.5 devices, some simple prefix conventions might be sufficient to distinguish.
