### ISSUE TITLE
Migrate binary assumes url-escaped connection string

### ISSUE THREAD

**Issue by ultimateboy** [google/exposure-notifications-server#613]
### TL;DR
If you get an obscure error while trying to run migrate, most likely you have too secure of a password and the special characters need url escaped.

Depending on exactly where your special character is, the error message will be slightly different, but it should look something like this:
```
error: parse "postgres://username@servername:pa#sword": invalid port ":pa#sword" after host
```

To fix, simply url-escape the connection string.

This is purely an informational issue and can be closed. Just trying to provide an entry point for others who might run into this issue.

**Comment by ultimateboy** [comment]
Cross linking issue from migrate queue: https://github.com/golang-migrate/migrate/issues/396

**Comment by sethvargo** [comment]
/assign

We can't actually encode the _entire_ string, but we can encode the password.
