### ISSUE TITLE
Handle null output region

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-server#623]
### TL;DR
The `output_region` in ExportConfig can be null. When null, the `scanOneExportConfig` function returns an error that it cannot unmarshal `NULL` in `*string`.

**Expected behavior**
No error.

**Observed behavior**
Error.

### Reproduction

1.  Create an ExportConfig with no output_region:

    ```text
    INSERT INTO ExportConfig (
      bucket_name, filename_root, period_seconds, from_timestamp
    ) VALUES
      ('my-bucket', 'folder', 5, '2020-06-11 00:00:00');
    ```

1. Call method

**Comment by mikehelmick** [comment]
hmm, that column should be not null I think.

@gurayAlsac ?

**Comment by gurayAlsac** [comment]
We have enforcement in the tool where we typically create these configs from:
https://github.com/google/exposure-notifications-server/blob/186c92778fe3791dc4e29b26b8e967e54aea0b26/tools/export-config/main.go#L53

But we I believe we have the field as nullable in the schema:
```
main=> \d exportconfig
                                              Table "public.exportconfig"
       Column       |           Type           | Collation | Nullable |                     Default                     
--------------------+--------------------------+-----------+----------+-------------------------------------------------
...
 output_region      | character varying(5)     |           |          | 
```

No harm treating null as empty string or making non nullable I suppose.

**Comment by mikehelmick** [comment]
the admin console also enforces at least an empty string, but not null.

Is it valid for this to be empty?
If it is empty and import regions is also empty, do you end up with no data?

**Comment by gurayAlsac** [comment]
Region isn't (yet - depending on where we land with roaming and upcoming stuff) used from the file, so output_region can probably be null. input_region only applies an additional filter, so if its null it'll just use all keys in the db, so it too can probably be null:
https://github.com/google/exposure-notifications-server/blob/186c92778fe3791dc4e29b26b8e967e54aea0b26/internal/publish/database/exposure.go#L148

**Comment by mikehelmick** [comment]
right, but if input regions is 0 and output regions is null - do you get 0 keys or ALL keys?
