### ISSUE TITLE
export-create-batches creating an empty index file

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#635]
After checking all the export configs and running through temp generated keys, the export batches service doesnt create any batch keys but only an empty index file.

Out log shows the following : `Failed to create batches for config 1: fetching most recent batch for config 1: scanning result: can't scan into dest[0]: cannot assign NULL to *time.Time, continuing to next config`

@gurayAlsac any pointers ?

**Comment by sethvargo** [comment]
@gurayAlsac that error looks like we have another field in the database than can be null.

**Comment by gurayAlsac** [comment]
Hmm, odd. That error comes from https://github.com/google/exposure-notifications-server/blob/e3bc7086720018e92fcd120dcad78153b5affa90/internal/export/database/export.go#L383 where the batch creation attempts to pick up at the last created batch (thus querying for max(end_timestamp) from ExportBatch table). The thing is that is a non-nullable column:
https://github.com/google/exposure-notifications-server/blob/186c92778fe3791dc4e29b26b8e967e54aea0b26/migrations/000001_initial.up.sql#L64
And the case where no rows are returned is explicitly handled.

Would you be able to share any more details about the context of your setup (contents of ExportConfig or ExportBatch) or steps to repro from a clean slate? Were there any manual insertions of data?

**Comment by sherifkozman** [comment]
@gurayAlsac There was no manual insertion of data , i am sharing screenshots of the testing export config and will be happy to share access to the project if needed.

![Screenshot 2020-06-16 16 39 46](https://user-images.githubusercontent.com/666788/84838730-02ab1600-aff0-11ea-878f-fc2e89eda1a0.png)
