### ISSUE TITLE
What does BYPASS_DEVICECHECK do?

### ISSUE THREAD

**Issue by nahuelhds** [google/exposure-notifications-server#636]
### Question
I was looking into the code implemented by AGESIC (Uruguay) and I've seen two constants that are weird to me. One is `BYPASS_SAFETYNET` and I've seen that is a debugging flag as said at #96 

I assume that `BYPASS_DEVICECHECK` is something similar, is that right?

**Comment by sethvargo** [comment]
Hi @nahuelhds 

These are old artifacts from when the service used Android SafetyNet and Apple's DeviceCheck to verify requests came from real Android/iOS devices. We've since removed that. These variables are no longer required or used in the latest server implementation.

Please let us know if you have any additional questions.

/close

**Comment by mikehelmick** [comment]
@nahuelhds  - I want to point out the replacement for this functionality.

We have described a verification system
    https://developers.google.com/android/exposure-notifications/verification-system

that allows for the diagnosis to be conveyed to the key server.

This repository already implements the verification protocol
    https://github.com/google/exposure-notifications-server/blob/master/docs/design/verification_protocol.md

And we have sample code for issuing these certificates
   https://github.com/google/exposure-notifications-server/blob/master/tools/example-verification-signing/main.go

**Comment by nahuelhds** [comment]
Thanks for all the info, guys

**Comment by nahuelhds** [comment]
I assumme that Agesic should pull these changes as well in order for them to remove these references too, right?

**Comment by mikehelmick** [comment]
yes - for now, I recommend continuing to fetch upstream commits as we're still actively working on the project.
