### ISSUE TITLE
One-click Deploy or Deploy from marketplace

### ISSUE THREAD

**Issue by TJMusiitwa** [google/exposure-notifications-server#643]
Hello there, 
I think it would be great to have a one-click deployment option or to have a ready to go option set up on Google cloud marketplace that could then be configured as necessary with say the dbnames, passwords etc and be ready to go.  

However if this isn't something that's a possibility, a minor explanation would be great to help understand why. 
Thanks

**Comment by mikehelmick** [comment]
Hello - we have one step deploy in the terraform directory. Is that sufficient?

**Comment by TJMusiitwa** [comment]
I will give the Terraform deployment a shot and hope all goes well. 

Any heads up I should be aware of while deploying with Terraform such as pre-deploy tasks on Google cloud and the like?
Thanks

**Comment by mikehelmick** [comment]
The readme in this directory should have complete instructions

https://github.com/google/exposure-notifications-server/tree/main/terraform

Note that terraform is used for the initial deployment. After that there are a series of scripts in the `scripts` directory that are used to build, deploy, and promote releases.

**Comment by jixiangox** [comment]
cloudsql_tier         = "db-custom-1-3840"
cloudsql_disk_size_gb = "16"

never success with this less powerful config but default.
Terraform plan out looks good to me, error logs show value is invalid

**Comment by mikehelmick** [comment]
@crwilcox - thoughts on that instance config?
