### ISSUE TITLE
Proposal: migrations docker image should contain the migrations instead of being mounted in at runtime

### ISSUE THREAD

**Issue by ultimateboy** [google/exposure-notifications-server#654]
### TL;DR

The migrations docker image is expected to be run by volume-mounting in the migration files. This unnecessarily complicates creating deployable build artifacts as the migration files need to be handled separately from the docker images.

### Design

**Proposal**

I propose that we bake the migration files directly into the migrate docker container. This provides for a consistent build-tagging scheme and deployment process, without having to worry about mounting in files from the repository at runtime.

Without the cloud-sql-proxy, this ends up looking about like this:
```
FROM golang:1.14-alpine AS builder

# Install deps
RUN apk add --no-cache git

# Install migrate
RUN go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate

COPY . .

FROM alpine
RUN apk add --no-cache ca-certificates

COPY --from=builder /go/bin/migrate /usr/local/bin/migrate
COPY --from=builder /go/migrations /migrations

ENTRYPOINT ["/usr/local/bin/migrate"]
```

**Comment by sethvargo** [comment]
The migrate container is just supposed to be the set of tools needed to perform migrations (independent of this project actually). It makes the build/deploy process more complex as now you need to know which migrate container contains your migrations for the current build.

**Comment by ultimateboy** [comment]
@sethvargo How would that be any different than knowing which exposure server container to run? You always want the "current build" and that's what makes the current setup difficult. I have to package the docker containers and then package the migrations files, tag them similarly, and then make the deployment smarter to know it also has to grab the deployments. If everything was baked into the docker image, you just run it. Sure, you have to know which version to run, but that's true with every single other container.

**Comment by sethvargo** [comment]
Hmm I see. I think this is a "GCP vs Azure" thing 😄 . When we run our migrations, we submit the build to our CI server _with the source at that time_, so all the migration files are included.

I think you're right, we should be versioning the migrations with the containers.
