### ISSUE TITLE
signing exposure keys

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#655]
Although signature information settings exists using a KMS resource, all TEKs are still showing that they are signed by Google managed keys over GCS.

How can we debug trace the root cause for this?
I am also attaching the Signature config sample.
@mikehelmick 

![Screenshot 2020-06-22 08 13 03](https://user-images.githubusercontent.com/666788/85304486-a9fcd280-b460-11ea-92bb-625e7a0e6165.png)
![Screenshot 2020-06-22 08 12 42](https://user-images.githubusercontent.com/666788/85304492-abc69600-b460-11ea-9bcd-24771ae0068b.png)

**Comment by mikehelmick** [comment]
In the GCS browser?

The gooogle managed key there is for encryption at rest. You can also specify your own key for encryption at rest (Customer Managed Encryption Keys).

For signing - you need to actually unzip the file and verify the signature of the .bin file using the public key for the key specified.

**Comment by sherifkozman** [comment]
@mikehelmick checking the exported bin file , it doesnt seem to be signed with the key that was set in export config. is there a way to verify if the process during export actually occured in signing those files?

**Comment by mikehelmick** [comment]
Is the signature info selected on your export config? 

This just defines available keys. The actual key to use is dependent on the export config.

**Comment by sherifkozman** [comment]
@mikehelmick we are referencing the signer key that is created through deployment in terraform.

Attached is a screenshot of the export config.
![Screenshot 2020-06-22 12 24 18](https://user-images.githubusercontent.com/666788/85327179-5d76be80-b483-11ea-8827-cd06bf918902.png)

**Comment by mikehelmick** [comment]
That's still the signature info screenshot - wrong image?

**Comment by gurayAlsac** [comment]
The configuration would be what's in the ExportConfig table, with corresponding model object of same name:
https://github.com/google/exposure-notifications-server/blob/8e9c93fb130cd825f76b5552d52f2b20b01ba5fb/internal/export/model/export_model.go#L35

If you haven't already configured an ExportConfig you can use this tool to do so:
https://github.com/google/exposure-notifications-server/blob/master/tools/export-config/main.go

And if you want to see what key an export was signed with, you can use the techniques described in https://github.com/google/exposure-notifications-server/tree/master/examples/export

**Comment by sherifkozman** [comment]
@mikehelmick @gurayAlsac The signature is selected in export already.

![Screenshot 2020-06-22 12 47 40](https://user-images.githubusercontent.com/666788/85329034-9a908000-b486-11ea-8044-23d4efea014a.png)

**Comment by mikehelmick** [comment]
Thanks for confirming. Next step would be to check the logs.

A successful signing would emit this message:
https://github.com/google/exposure-notifications-server/blob/8e9c93fb130cd825f76b5552d52f2b20b01ba5fb/internal/export/worker.go#L212

And if it failed, the error would be bubbled up and logged here:
https://github.com/google/exposure-notifications-server/blob/8e9c93fb130cd825f76b5552d52f2b20b01ba5fb/internal/export/worker.go#L79

If you're successfully getting export files that aren't signed then that likely indicates a bug that needs to be addressed. 

Also - going through the steps that @gurayAlsac suggested seems like a good idea.

**Comment by gurayAlsac** [comment]
I believe to use a different key provider for signing files (e.g., the AWS KMS implementation in https://github.com/google/exposure-notifications-server/blob/master/pkg/secrets/aws_secrets_manager.go) you'll need to modify your server setup to explicitly call `WithKeyManager()`:
https://github.com/google/exposure-notifications-server/blob/1b409114bbc1edb43d25978222f4897d1f259573/internal/serverenv/env.go#L98

That'll then let the export creation code pull the signing key from the different key provider in 
https://github.com/google/exposure-notifications-server/blob/8e9c93fb130cd825f76b5552d52f2b20b01ba5fb/internal/export/worker.go#L199

@sethvargo to check me.

**Comment by sherifkozman** [comment]
we keep everything GCP focused so we dont have to deviate on anything.
however as per the error , it seems there is an issue with the resource ID and i believe it may not be picking the version value!
we are using the following values for test : 

Signing Key : projects/xxxxxx/locations/us-central1/keyRings/export-signing/cryptoKeys/signer
Signing Key Version 1

![Screenshot 2020-06-22 13 03 54](https://user-images.githubusercontent.com/666788/85332601-18578a00-b48d-11ea-92a9-9e9154c6cae2.png)

**Comment by gurayAlsac** [comment]
Ah, you'll definitely want to include the version in the resource id. E.g.
`projects/.../locations/us/keyRings/.../cryptoKeys/region-us/...KeyVersions/1`

**Comment by sethvargo** [comment]
The default is AWS KMS, and you can configure the others with envvars

**Comment by sherifkozman** [comment]
@sethvargo @gurayAlsac adding the version number within the Signing key resource and signing works fine now.

However, I assumed having a Signing Key version input field would append the version number to the resources ID for GCP KMS.

What would be the use of the Signing Key version if it has to be explicitly mentions in the resource ID ?

**Comment by gurayAlsac** [comment]
Ah I see the confusion. There's a version of the key in your KMS of choice, but also a version as you've provided to Apple/Google, and they need not necessarily be the same. The admin ui was asking about the latter, and that's what will get populated into the verification_key_version field in the proto:
https://github.com/google/exposure-notifications-server/blob/8e9c93fb130cd825f76b5552d52f2b20b01ba5fb/internal/pb/export/export.proto#L55
