### ISSUE TITLE
Clarification of protobuf fields

### ISSUE THREAD

**Issue by lmartensson** [google/exposure-notifications-server#670]
I'd like to make sure I understand what some of the fields in the TemporaryExposureKeyExport mean. 
https://github.com/google/exposure-notifications-server/blob/035195440ec9e72a9bf4236e686388f22a5bfd7a/internal/pb/export/export.proto

In TemporaryExposureKeyExport:
  // Time window of keys in this batch based on arrival to server, in UTC seconds.
  optional fixed64 start_timestamp = 1;
  optional fixed64 end_timestamp = 2;
1. Does this tell us for what time period these keys were active, or when they arrived to the server?
If the former, it's relative to arrival on server?  Why?
If the latter, why end time?
An example here would be very helpful.

In TemporaryExposureKey:
  // The interval number since epoch for which a key starts
  optional int32 rolling_start_interval_number = 3;
2. What would this look like? This is not seconds from epoch?

  // Increments of 10 minutes describing how long a key is valid
  optional int32 rolling_period = 4
3. So, if the value of this is 1, it meansthat  thekey is valid for 10 minutes?
4. I thought this would be the TemporaryExposureKey and that it is always valid for 24 hours. Or does this refer to the RPIs that are generated from the TEK, even though the key itself in this message is the TEK?

Thanks!

**Comment by gurayAlsac** [comment]
1. It is based on arrival to the server. The idea is that the server exports keys as it becomes aware of them and generates immutable files corresponding to the keys that came in from start/end timestamp and these files could be cached.

2. Interval number is `is discretized ... 10 minute intervals that are enumerated starting from Unix
Epoch Time` and associated to when the RPI (Rotating Proximity Identifiers) was active for. See 
https://blog.google/documents/69/Exposure_Notification_-_Cryptography_Specification_v1.2.1.pdf
https://developers.google.com/android/exposure-notifications/exposure-notifications-api#tek

3. Correct. A rolling period of 1 means the key is valid only for one ten minute interval following its start.

4. RPI always expires after one interval. Typically TEKs last the full day, but in the case that a key has been released, it is immediately expired and RPIs generated from it after this time are not valid. This is to prevent replay attack if key is released early in day, uploaded to server, and gets exported to other devices within the same day.
