### ISSUE TITLE
Define release process

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#671]
Things are still progressing fairly rapidly.

Define a release process for tagging this and the exposure-notifications-verification-server repositories on the same release cadence.

/assign

**Comment by sethvargo** [comment]
Are you thinking auto-build and deploy on tag, or just a regular "we tag on significant changes"?

**Comment by mikehelmick** [comment]
probably not auto.

More so - I want to be able to say v0.1 of the ENS and v0.1 of the ENVS know how to talk to each other.
Here is the exposure API that supports and here is the export API that supports.

And then in between versions we don't have to guarantee HEAD compatibility at all times.

**Comment by sethvargo** [comment]
Cool totally reasonable. I had (have) some ideas on auto, but I agree that it's probably too soon.

**Comment by mikehelmick** [comment]
Proposal

* pr template will be updated to capture release notes
* weekly release cadence
* releases will drop on tuesday
* Release will create a branch and a tag
* TAG'd release will roll up the release notes since the last tag
