### ISSUE TITLE
index.txt crosses export configs

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#672]
### TL;DR

When there are multiple export configs on a single instance, the index.txt file seems to cross the streams as it were.

For example, this is a sample from an export that should only contain "CH" region TEKs

```
exposureKeyExport-CH/1593446400-1593446700-00001.zip
exposureKeyExport-US/1592240400-00001.zip
```

**Expected behavior**

The different export configs have separate index.txt files

**Observed behavior**

They were merged

**Comment by crwilcox** [comment]
@gurayAlsac looked at the configs and it seems we are collecting all in regions right now, so this makes sense. 

```
main=> select filename_root, output_region, input_regions from exportconfig ;
    filename_root     | output_region | input_regions 
----------------------+---------------+---------------
 exposureKeyExport-US | US            | 
 exposureKeyExport-CH | CH            | {}
(2 rows)
```

I propose we collect input US output US, input CH, output CH, and output ALL input {}

**Comment by crwilcox** [comment]
Clarification: if no input region specified it should be output region

**Comment by mdsummers** [comment]
When the filename root differs between export configurations, it seems that index.txt files still refer to files from other export configurations (and therefore in different filename roots).

**Comment by mikehelmick** [comment]
originally, output region was just `region`

when I introduced the input region, the intent was that if that was an empty array, then the output region would be used.

I think an implicit "all" is potentially dangerous as it makes it really easy to over-export keys.
