### ISSUE TITLE
Is there a reason not to cache export bundle files?

### ISSUE THREAD

**Issue by mdsummers** [google/exposure-notifications-server#673]
### Question
Metadata on .zip export bundles sets `cache-control: no-cache, max-age=0`. 

Is there a reason not to cache these files? Should they ever change?

### Context
Invocations of `s.env.Blobstore().CreateObject` in internal/export/worker.go set cachable: false for index and bundle files.

**Comment by mdsummers** [comment]
Relates to https://github.com/google/exposure-notifications-server/pull/494

The index stands to change and makes sense not to cache. The change also set caching on bundle files.

**Comment by gurayAlsac** [comment]
Looks like a bug:
```
$ gsutil ls -L gs://exposure-notification-export-lmuvk/exposureKeyExport-US/index.txt | grep cache
        Cache-Control:      no-cache, max-age=0
$ gsutil ls -L gs://exposure-notification-export-lmuvk/exposureKeyExport-US/1592245500-00001.zip | grep cache
        Cache-Control:      no-cache, max-age=0
```

The intention was to have export files themselves be cacheable (as they are immutable) and the index not be cached.
