### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#677]
/assign

**Comment by mikehelmick** [comment]
main branch has been created - it is even w/ the master branch

**Comment by sethvargo** [comment]
@mikehelmick I think we should tag before the full rename

**Comment by mikehelmick** [comment]
Tag as 'v0.1' ?

**Comment by sethvargo** [comment]
works for me. then tag future as v0.2

**Comment by mikehelmick** [comment]
Releases created on both repositories w/ v0.1 tag

**Comment by mikehelmick** [comment]
Leaving this issue open and tagged for a while so that folks are aware

**Comment by mikehelmick** [comment]
old 'master' branch has been deleted

**Comment by mikehelmick** [comment]
this is done - doc publishing has ben fixed.
