### ISSUE TITLE
Interface with verification service discovery

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#679]
### TL;DR

For health authority verification,

instead of storing public keys in the database, integrate with verification server discovery.

Dependent on the outcome of https://github.com/google/exposure-notifications-verification-server/issues/93

/kind enhancement
/assign

**Comment by mikehelmick** [comment]
not stale

**Comment by sethvargo** [comment]
Is this a dupe of GH-911?

**Comment by mikehelmick** [comment]
yes, it's a dupe
