### ISSUE TITLE
Deployment fails with Cloud Run Error

### ISSUE THREAD

**Issue by vbGoz** [google/exposure-notifications-server#684]
Deployment fails with Cloud Run Error:
`ERROR: (gcloud.run.deploy) Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.`

**Comment by giautm** [comment]
You should check log on Cloud Run, It can't start because something wrong on that service.

**Comment by sethvargo** [comment]
What do the Cloud Run logs show?

**Comment by vbGoz** [comment]
Logs do not have much additional info either. Here's what they look like:

```
starting build "ad0104cb-1585-4215-9776-7e69412c05ad"

FETCHSOURCE
BUILD
Pulling image: gcr.io/google.com/cloudsdktool/cloud-sdk:293.0.0-alpine

                   ***** NOTICE *****

Alternative official `docker` images, including multiple versions across
multiple platforms, are maintained by the Docker Team. For details, please
visit https://hub.docker.com/_/docker.

                ***** END OF NOTICE *****

293.0.0-alpine: Pulling from google.com/cloudsdktool/cloud-sdk
cbdbe7a5bc2a: Already exists
161a6449b7ec: Pulling fs layer
474f70c22f44: Pulling fs layer
161a6449b7ec: Verifying Checksum
161a6449b7ec: Download complete
474f70c22f44: Verifying Checksum
474f70c22f44: Download complete
161a6449b7ec: Pull complete
474f70c22f44: Pull complete
Digest: sha256:7d0cae28cb282b76f2d9babe278c63c910d54f0cceca7a65fdf6806e2b43882e
Status: Downloaded newer image for gcr.io/google.com/cloudsdktool/cloud-sdk:293.0.0-alpine
gcr.io/google.com/cloudsdktool/cloud-sdk:293.0.0-alpine
Deploying container to Cloud Run service [export] in project [figtracing] region [us-central1]
Deploying...
Creating Revision.................................................................................failed
Deployment failed
ERROR: (gcloud.run.deploy) Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.
ERROR
ERROR: build step 0 "gcr.io/google.com/cloudsdktool/cloud-sdk:293.0.0-alpine" failed: step exited with non-zero status: 1
```

**Comment by sethvargo** [comment]
Hi @vbGoz those are the Cloud _Build_ logs. To get the Cloud _Run_ logs, go to Cloud Run in the console (find it in the sidebar or use the search box). Then click on your service (it should have a big red circle indicating it failed), then click on logs to view the logs.

**Comment by vbGoz** [comment]
@sethvargo Here's the error I see:

```
2020-07-04 18:05:34.957 PDTsetup.Setup: unable to connect to database: creating connection pool: failed to connect to `host=localhost user= database=`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)

**Comment by vbGoz** [comment]
I found the confine.go file with the host and port configuration, but changing it didn't help:

```
2020-07-05 08:38:44.545 PDTsetup.Setup: unable to connect to database: creating connection pool: failed to connect to `host=0.0.0.0 user= database=`: dial error (dial tcp 0.0.0.0:8080: connect: connection refused)
```

```
2020-07-05 08:46:55.260 PDTsetup.Setup: unable to connect to database: creating connection pool: failed to connect to `host=0.0.0.0 user= database=`: dial error (dial tcp 0.0.0.0:5432: connect: connection refused)
```

**Comment by sethvargo** [comment]
Hi @vbGoz can you tell me more about how you're deploying? Did you use the Terraform configurations?

**Comment by vbGoz** [comment]
Yes, I used Terraform configurations.

**Comment by sethvargo** [comment]
Terraform has to do the first deployment to set those variables.

**Comment by vbGoz** [comment]
Thank you @sethvargo for your quick responses. I truly appreciate it.

I re-tried the terraform setup and followed the guide at:
https://github.com/google/exposure-notifications-server/tree/main/terraform

I see the following warning for the apply command:

```
$ terraform apply

Warning: Value for undeclared variable

The root module does not declare a variable named "project" but a value was
found in file "terraform.tfvars". To use this value, add a "variable" block to
the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.


Warning: Value for undeclared variable

The root module does not declare a variable named "generate_cron_schedule" but
a value was found in file "terraform.tfvars". To use this value, add a
"variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by sethvargo** [comment]
Are you sure you're inside the `terraform/` directory on the latest pull? The module _does_ define a variable named "project" and "generate_cron_schedule".

**Comment by vbGoz** [comment]
Thank you! My bad, I believe while trying to debug other issues. I overwrote some of the configs.

I did a fresh clone and re-ran the terraform instructions and apply fails with the following:

```
Error: Error waiting to create Connector: Error waiting for Creating Connector: Error code 7, message: Operation failed: Google APIs Service Agent (<PROJECT_NUMBER>@cloudservices.gserviceaccount.com) needs editor role in the project.
```

I verified that `<PROJECT_NUMBER>@cloudservices.gserviceaccount.com` already has an editor role for the project.

**Comment by sethvargo** [comment]
Can you share more of the Terraform output logs? Can you share a screenshot of your IAM console where the Service Agent has Editor permissions please?

**Comment by vbGoz** [comment]
[https://drive.google.com/file/d/1mOIQsExVxcvCaV5-of7Qqps6Q5sJ0Tae/view?usp=sharing](Permissions)

[https://drive.google.com/file/d/1IKyl3IBMQ0UO5_GtQ8Q7rUvC-BfitvtB/view?usp=sharing](Logs)

**Comment by sethvargo** [comment]
Hmm. Do you have any organization policies or restrictions on your project (like VPC-SC, org policies, etc)?

**Comment by vbGoz** [comment]
No, I don't have the project connected to any org, it is under my personal google account.

**Comment by sethvargo** [comment]
Hmm I'm really not sure to be honest. I just tried again in a new project and it worked fine. You could try a new project, or revoke and re-add the permisisons:

```
gcloud projects add-iam-policy-binding project_id
  --member serviceAccount:project_number@cloudservices.gserviceaccount.com
  --role roles/editor
```

**Comment by vbGoz** [comment]
I tried a new project but still ran into the same issue. It looks like my issue is exactly same as:
https://github.com/google/exposure-notifications-server/issues/639
I am trying `vpc_access_connector_max_throughput` default value as 300 now.

**Comment by vbGoz** [comment]
@sethvargo It worked with 300 value.
