### ISSUE TITLE
Proper Tutorial for deployment and everything .

### ISSUE THREAD

**Issue by atikrahman-ew** [google/exposure-notifications-server#685]
### Question

The documentation from google is always scatter and is not clear at all . Is there Any tutorial that covers everything ????

**Comment by sethvargo** [comment]
Hi @atikrahman-ew there's some documentation in this repository in the `docs/` folder. Specifically, you might be interested in:

- [Deployment Options](https://github.com/google/exposure-notifications-server/blob/a820290c22f0c973da3af3c2d2d7c41218a80b04/docs/server_deployment_options.md)
- [Deployment Guide](https://github.com/google/exposure-notifications-server/blob/a820290c22f0c973da3af3c2d2d7c41218a80b04/docs/getting-started/deploying.md)

Are there specific things you believe are missing from the guide?

**Comment by atikrahman-ew** [comment]
> Hi @atikrahman-ew there's some documentation in this repository in the `docs/` folder. Specifically, you might be interested in:
> 
> * [Deployment Options](https://github.com/google/exposure-notifications-server/blob/a820290c22f0c973da3af3c2d2d7c41218a80b04/docs/server_deployment_options.md)
> * [Deployment Guide](https://github.com/google/exposure-notifications-server/blob/a820290c22f0c973da3af3c2d2d7c41218a80b04/docs/getting-started/deploying.md)
> 
> Are there specific things you believe are missing from the guide?

Hi @sethvargo  i know about this but those are scatter . i wanted to know if theres any single document how to deploy the api and test everything .

**Comment by sethvargo** [comment]
Hi @atikrahman-ew thank you for your reply. I'm not entirely sure what you're asking for. The Deployment Guide I linked above is a single document that tells you how to deploy the API. The Deployment Options explain the different components of the system (it's pluggable).

**Comment by mikehelmick** [comment]
There is some additional documentation that covers more of the overall ecosystem located at https://developers.google.com/android/exposure-notifications/exposure-notifications-api

The other things I would recommend are

- https://github.com/google/exposure-notifications-server/tree/main/terraform - shows how to deploy the server
- https://google.github.io/exposure-notifications-server/server_functional_requirements - talks about what the sever actually does

**Comment by atikrahman-ew** [comment]
Hi Guys I have successfully Deployed from terraform setting .

Now i need to know how to call those on api and setting up on demo project . I am lost there completely .
@mikehelmick @sethvargo  Appreciated if you help please .

**Comment by mikehelmick** [comment]
To configure the server, you need to run the admin console. You run this locally, see https://google.github.io/exposure-notifications-server/getting-started/deploying#configuring-the-server

There are 2 key pieces

1. Configure the authorized app to enable uploads

1. Configure exportconfig to create exports

The API for uploading keys is defined here, https://github.com/google/exposure-notifications-server/blob/main/pkg/api/v1alpha1/exposure_types.go#L58

**Comment by atikrahman-ew** [comment]
@mikehelmick 
Thank you very much .As you suggested 
![Capture](https://user-images.githubusercontent.com/29091506/87240622-e65a9780-c43c-11ea-808e-fa344454cac9.PNG)

i have successfully run admin console and add an auth app. But on the the android demo project where should i found the server url ? can you guide a bit on that . So far Great Help . Appreciate it .

**Comment by mahabub-parallax** [comment]
> @mikehelmick
> Thank you very much .As you suggested
> ![Capture](https://user-images.githubusercontent.com/29091506/87240622-e65a9780-c43c-11ea-808e-fa344454cac9.PNG)
> 
> i have successfully run admin console and add an auth app. But on the the android demo project where should i found the server url ? can you guide a bit on that . So far Great Help . Appreciate it .


**I am also stack in this stage**.  can anyone help me

**Comment by mikehelmick** [comment]
The server url can be found by visiting the Cloud Run section of the Cloud Console: https://console.cloud.google.com/run

Look for the "exposure" service and click into the details to find the URL.

**Comment by atikrahman-ew** [comment]
@mikehelmick  Got the url thank you so much brother .
 God bless you . 
Our google demo project application runs and says not authorized ?? any last help for this ?

**Comment by mikehelmick** [comment]
2 possibilities

1) Make sure the apppackagename that the app is sending is the same as you have configurd
2) You may need to set "bypass health authority verification" unless you are also running a verification server : https://github.com/google/exposure-notifications-verification-server

**Comment by atikrahman-ew** [comment]
Hi @mikehelmick 

![solve1](https://user-images.githubusercontent.com/29091506/87399756-a846aa80-c5d9-11ea-92dc-d7afe163ac4b.PNG)

here is the ss of android default app adding .

Kindly Do look the bellow 
![WhatsApp Image 2020-07-14 at 1 56 04 PM](https://user-images.githubusercontent.com/29091506/87400124-3a4eb300-c5da-11ea-890b-94203550ac74.jpeg)
![WhatsApp Image 2020-07-14 at 1 56 13 PM](https://user-images.githubusercontent.com/29091506/87400129-3c187680-c5da-11ea-93ce-0c627e4f9651.jpeg)
![WhatsApp Image 2020-07-14 at 1 56 08 PM](https://user-images.githubusercontent.com/29091506/87400132-3cb10d00-c5da-11ea-855e-5f4578ddb910.jpeg)

**Comment by mikehelmick** [comment]
without seeing the server logs- you most likely need to set "health authority verification disabled" to `true`

The exact unauthorized reason would be in the Cloud Run server logs.

**Comment by mikehelmick** [comment]
We need to take a pass over the docs.

**Comment by sherifkozman** [comment]
@mikehelmick Can you elaborate a bit about how the Health Authority creation and JWT configs fit into the verification server setup, the documentation on that side is scarce as we are moving into testing HA verified requests between both implementations.

**Comment by mikehelmick** [comment]
@sherifkozman - Specifically, how to set up the verification and the key server to trust one another? or something else?

**Comment by sherifkozman** [comment]
@mikehelmick that's true , i assume this is where the Health Authority config over the ENS plays a role

**Comment by sherifkozman** [comment]
@mikehelmick did you have the time to check that or pointer towards how is it set between both servers ?

**Comment by mikehelmick** [comment]
Right now - the verification server uses a single verification signing key, configured by the env vars.
* this will change in the future w/ the new multi-tenant features

To link a verification server to the key server (using the `./tools/admin-console`)

Create a health authority
![image](https://user-images.githubusercontent.com/92319/88999888-b91a4000-d2aa-11ea-8d52-dd42d88214bf.png)

The issuer and audience need to match what is configured at the verification server. Ideally the key server operator defines the 'aud' and the verification server operator defines the 'iss'

After the HA is saved, you can add a key

![image](https://user-images.githubusercontent.com/92319/89000039-275f0280-d2ab-11ea-8054-799a0a63c0b3.png)

The version is the keyId as defined by the verification server

When the key is set up, it should look like this

![image](https://user-images.githubusercontent.com/92319/89000195-9b99a600-d2ab-11ea-8716-0bdebd2640be.png)

Then go create the authorized app, and select that health authority

![image](https://user-images.githubusercontent.com/92319/89000280-d7cd0680-d2ab-11ea-957e-5fa90661f502.png)

@sherifkozman  - let me know if that's what you're looking for.

**Comment by sherifkozman** [comment]
@mikehelmick What you just posted is the admin tool of the Exposure notifications server not the verification server if i am not mistaken. The verification server doesnt have ( ./tools/admin-console)

I guess my question how is that is that linked or used when generating a verification token on the verification server side.
If we are to turn on "Health Authority verification Disabled = false" where would the generated values in the above screenshots be used on the other verification server?

**Comment by mikehelmick** [comment]
the trust is established in the other direction. The "key server" (this repo) is configured to trust verification certificates as issued by a verification server.

**Comment by sherifkozman** [comment]
@mikehelmick does this mean that the certificate used in the verification server would be the one used in creating they authority config in the key server? Is that an accurate assumption?

**Comment by sherifkozman** [comment]
@mikehelmick For the public key when setting a new Health Authority over the ENS , would that be the token signer or the certificate signer key from the verification server?

**Comment by mikehelmick** [comment]
It's the certificate signer that is the key that needs to be shared w/ the key server.

**Comment by sherifkozman** [comment]
@mikehelmick great that worked fine,  i believe the issue was in the issuer value which is preset by default into diagnosis-verification-example

**Comment by mikehelmick** [comment]
We're going to be making the aud/iss fields configurable in the verification server UI.

**Comment by sethvargo** [comment]
@mikehelmick I think we can close this out?

**Comment by mikehelmick** [comment]
yeah

/close
