### ISSUE TITLE
Invalid Project ID on all services

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#696]
After upgrading the codebase after two weeks all services are reporting an invalid project ID value over all logs as follows  :

2020-07-07 06:14:26.850 PDT
2020/07/07 13:14:26 Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = Invalid project ID

Similar trace in export service : 
GET200 235 B 105 ms Google-Cloud-Scheduler https://xxxxxxxxxx-uc.a.run.app/create-batches
2020-07-07 06:18:09.750 PDT
2020/07/07 13:18:09 Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = field [name] has issue [Invalid project resource name]

**Comment by sethvargo** [comment]
This is likely related to changes in https://github.com/google/exposure-notifications-server/commit/5cb95f73ffdcf23aa424906d7a983607de53848f#diff-cbb25aea043ef5888a4f0283ee00649a to support multiple observability tools. Can you try setting `PROJECT_ID` or `GOOGLE_CLOUD_PROJECT` on your Cloud Run services' environment and see if that issue goes away? If so, we can update the logic to "find" the project ID automatically.

**Comment by mikehelmick** [comment]
There are 2 options

1) disable the stackdriver exporting

2) set the PROJECT_ID env-var (what #697 ) does + grant stackdriver write permissions to the SAs. PR incoming for that piece I believe.

/assign @sethvargo
