### ISSUE TITLE
Posting Keys from previosly working clients results error 400

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#705]
Recenetly submitting exposure Keys from clients that were succesffully working before started giving : 
Error 400 : unable to read request data: exposure keys have overlapping intervals 
Any pointers on how to trace that and the root cause ?

**Comment by mikehelmick** [comment]
if you set [this flag](https://github.com/google/exposure-notifications-server/blob/main/internal/publish/config.go#L50) to true, it will allow that upload to work.

We're still in process for upgrading the server for the "v1.5" model, see #663 

In this new model - there will be 2 keys for the last day, one that ends earlier and one that continues for the rest of the day.

**Comment by sherifkozman** [comment]
@mikehelmick This worked fine for now, thanks

**Comment by sherifkozman** [comment]
Hello @mikehelmick even after lifting the embargo over the Keys and setting DEBUG_RELEASE_SAME_DAY_KEYS=true for the exposure service we are still getting error 400

**Comment by mikehelmick** [comment]
Same error message?

Can you share the server logs?

And can you share the data that is being uploaded? You can redact the keys, just need to see the timing information.

**Comment by sherifkozman** [comment]
So we are getting a bunch of errors of overlapping Keys through the mobile app that was previously working.
Yesterday they were generating Error 400 with "exposure keys have overlapping intervals" today they are being accepted with the same warning.

[keys.txt](https://github.com/google/exposure-notifications-server/files/4897612/keys.txt)

**Comment by mikehelmick** [comment]
I pulled out just the timing information from the file.

```
    - rollingPeriod : 90
    - rollingStartNumber : 2657088
    - rollingPeriod : 89
    - rollingStartNumber : 2657088
    - rollingPeriod : 89
    - rollingStartNumber : 2657088
    - rollingPeriod : 88
    - rollingStartNumber : 2657088
    - rollingPeriod : 144
    - rollingStartNumber : 2656944
    - rollingPeriod : 133
    - rollingStartNumber : 2656944
    - rollingPeriod : 116
    - rollingStartNumber : 2656944
    - rollingPeriod : 113
    - rollingStartNumber : 2656944
    - rollingPeriod : 112
    - rollingStartNumber : 2656944
    - rollingPeriod : 112
    - rollingStartNumber : 2656944
    - rollingPeriod : 112
    - rollingStartNumber : 2656944
    - rollingPeriod : 112
    - rollingStartNumber : 2656944
    - rollingPeriod : 99
    - rollingStartNumber : 2656944
    - rollingPeriod : 94
    - rollingStartNumber : 2656944
    - rollingPeriod : 94
    - rollingStartNumber : 2656944
    - rollingPeriod : 144
    - rollingStartNumber : 2656800
    - rollingPeriod : 123
    - rollingStartNumber : 2656800
    - rollingPeriod : 120
    - rollingStartNumber : 2656800
    - rollingPeriod : 144
    - rollingStartNumber : 2656656
    - rollingPeriod : 144
    - rollingStartNumber : 2656512
    - rollingPeriod : 144
    - rollingStartNumber : 2656368
    - rollingPeriod : 144
    - rollingStartNumber : 2656224
```

As far as I know, this situation shouldn't be happening. I've asked someone from the android team to take a look.

**Comment by mikehelmick** [comment]
/assign
/kind bug

conferred w/ the android folks - I'll get a fix out to the server to support this new functionality today.

**Comment by sherifkozman** [comment]
@mikehelmick This issue is not yet resolved with the latest patch. We are still recieving error 400 over POST requests.
For Testing purposes we have set the following too : 

        - name: DEBUG_RELEASE_SAME_DAY_KEYS
          value: 'true'
        - name: MAX_KEYS_ON_PUBLISH
          value: '30'
        - name: MAX_SAME_START_INTERVAL_KEYS
          value: '14'

**Comment by mikehelmick** [comment]
What’s the error message and log messages?

**Comment by sherifkozman** [comment]
The Server doesnt show any detail error log only 400 as per the screenshot.
The Odd part is multiple devices using the same test app, some of those get 400 and some get 200 with successful exposoure insertion.
<img width="1177" alt="Screen Shot 2020-07-09 at 6 30 58 PM" src="https://user-images.githubusercontent.com/666788/87106469-5d601800-c212-11ea-89f7-151db88db9cd.png">

**Comment by mikehelmick** [comment]
The error would likely be one line above that.

Are you capturing the http response body at the client? That would have details as well.

I’ll try and get additional log details added tonight.

**Comment by mikehelmick** [comment]
Added some additional logging along this code path: https://github.com/google/exposure-notifications-server/pull/708
Sent out for code review.

**Comment by mikehelmick** [comment]
Hi @sherifkozman  -

Can you deploy the additional logging and let me know what you see?
We can debug further from there if necessary.

**Comment by sherifkozman** [comment]
@mikehelmick The latest logging change paid off , now we can see things clearer and start acting accordingly.
Here is a sample of why we are getting 400
<img width="973" alt="screen_shot_2020-07-10_at_7 11 33_am" src="https://user-images.githubusercontent.com/666788/87178703-6ee90480-c292-11ea-9080-70dc08d0df13.png">

**Comment by mikehelmick** [comment]
ah - perfect. I just sent a PR for a tool that will help w/ interval conversions #709 

This timing is close, it is under a day too old

```
exposure-notifications-server on 🌱 intervalto [$?] via 🐹 v1.14.2 
❯ go run ./tools/interval --interval=2655072 --chart=false
interval 2655072 is at: 2020-06-24 17:00:00 -0700 PDT

exposure-notifications-server on 🌱 intervalto [$?] via 🐹 v1.14.2 
❯ go run ./tools/interval --interval=2655157 --chart=false
interval 2655157 is at: 2020-06-25 07:10:00 -0700 PDT
```

In the server, you can tune the max age by setting
https://github.com/google/exposure-notifications-server/blob/main/internal/publish/config.go#L48

**Comment by mikehelmick** [comment]
Going to close this out as I don't think there's anything to "fix" in the code

**Comment by sherifkozman** [comment]
confirmed

**Comment by sherifkozman** [comment]
@mikehelmick i want to confirm that the attached error is related to the v1.5 implementation that is not yet complete?
Cause all exposure submission tests are broken so far because of this.
![Screenshot 2020-07-15 10 49 45](https://user-images.githubusercontent.com/666788/87578255-02eb0f80-c689-11ea-84e4-758a4f139081.png)

**Comment by sherifkozman** [comment]
@mikehelmick done and working :) thanks

**Comment by mikehelmick** [comment]
great! Sorry again for the breakage, v1.5 was a complicated transition.
