### ISSUE TITLE
Error in setting up CLEANUP_TTL to delete older export files

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#711]
Trying to abide by the max file limit for IOS and Android we have reset the export config to a min of 24 hours to generate less files.
The index file still contains references for the older files which we tried to clear by setting the CLEANUP_TTL to a lower value of 24 hours so we can get rid of the older batch files but the clean jobs always result the below error : "error processing cutoff time: cleanup ttl is less than configured minimum ttl"

Checking the code base the "CLEANUP_TTL" seems to be set in 3 different services "export" "clean up exposure" and "clean up export"

Please advice

**Comment by mikehelmick** [comment]
I think that shortening the cleanup period is the wrong approach. Consider the impact of a device that has been offline for several days and needs to catch up.

Instead, your app should "remember" which .zip files it has processed of those in the index.txt file and only process the new ones.

There are two cleanup jobs.

- `cmd/cleanup-export` for cleanup up of the old files
- `cmd/cleanup-exposure` for cleanup of the exposure table in the database

They both use the same [CLEANUP_TTL](https://github.com/google/exposure-notifications-server/blob/main/internal/cleanup/config.go#L43) env var.

There is a [minTTL](https://github.com/google/exposure-notifications-server/blob/main/internal/cleanup/cleanup.go#L35) in effect that you are running into. This is to prevent mis-configuration and accidental deletion of things that may not have made it into an export yet.

**Comment by sherifkozman** [comment]
@mikehelmick i totally agree for a production environment, but during development while configs are being tested (i.e setting a 4 hours export config) created hundreds of files that a mobile device is unable to process due to the 15-20 files limit and those files will only be cleared out after 14+1 days (360h)

**Comment by sherifkozman** [comment]
@mikehelmick any ideas on how we can get rid of the older files created quicker and in a cleaner way ?

**Comment by mikehelmick** [comment]
the only way to do that would be to add a flag to remove this backstop.

**Comment by sherifkozman** [comment]
you mean in the code it self not an actual variable availble correct ?
or i would reset the entire database and start fresh ?

**Comment by mikehelmick** [comment]
code change to give you a new flag to set.

https://github.com/google/exposure-notifications-server/pull/714 will give you that

/assign

**Comment by sherifkozman** [comment]
i ran it off your personal branch and it worked fine deleted all old files as expected. However the index file is not updated and still have references to the old files, is this normal ?

**Comment by mikehelmick** [comment]
index.txt will be regenerated next time an export is generated and won't contain the old files.

**Comment by sherifkozman** [comment]
@mikehelmick after the latest update the following started surfacing , are they related ?

![Screenshot 2020-07-13 13 35 11](https://user-images.githubusercontent.com/666788/87352960-c7c5d080-c510-11ea-873b-bbd5b1814c48.png)

**Comment by mikehelmick** [comment]
that is related to #663 

it means the app is uploading keys that were previously uploaded are being uploaded again (which is not necessary).

In the new model it will be possible to upload a key for a second time and change it's report type.

When I finish the work on #663 the old way of uploading a key without changes will continue to work. Sorry for the temporary breakage. I wanted to break this up into multiple changes and not a giant massive change.

**Comment by sherifkozman** [comment]
@mikehelmick i wanted to confirm that new export batch has been create and the index file was updated yet still containing the references of the older files that were deleted. Any pointers ?

**Comment by mikehelmick** [comment]
That is unexpected.

/assign @gurayAlsac - Can you take a look?

**Comment by sherifkozman** [comment]
I have temporarly cleaned the index.txt referencing only exisiting files and kept a copy of the old one

**Comment by mikehelmick** [comment]
If export generation didn't clean up the file, they will be put back next time. 
I'm guessing there is a bug in selecting files from the exportfiles table through the exportbatch table.

**Comment by sherifkozman** [comment]
i agree that with the next batch the file will get back to the same state, this is a very temp solution as our testing is blocked by the number of files that client has to parse through though they dont exist.

**Comment by sherifkozman** [comment]
@gurayAlsac any thoughts related to the index.txt cleaning issue ?

**Comment by gurayAlsac** [comment]
There are two separate things here: (1) the TTL for when export files themselves get deleted (which is what https://github.com/google/exposure-notifications-server/pull/714/files touched) and is a configuration in the cleanup server, (2) the TTL for how long we look back in the ExportFile table to include things in the index file and is a configuration in the export server.

Two separate configs, same great name:

1. https://github.com/google/exposure-notifications-server/blob/1aef0fbe22aef93ec86f5432dd9d0317418eba15/internal/cleanup/config.go#L43
2. https://github.com/google/exposure-notifications-server/blob/1aef0fbe22aef93ec86f5432dd9d0317418eba15/internal/export/config.go#L53

Second is passed in to export index creation here:
https://github.com/google/exposure-notifications-server/blob/1aef0fbe22aef93ec86f5432dd9d0317418eba15/internal/export/worker.go#L275

Used in the `where` clause of the query here:
https://github.com/google/exposure-notifications-server/blob/1aef0fbe22aef93ec86f5432dd9d0317418eba15/internal/export/database/export.go#L650

**Comment by sherifkozman** [comment]
This explains why i found the same ENV variable in 3 different places! 
So now we clean up the files but not how the index is created as it looks back at the export...
will that be fixed ?

**Comment by gurayAlsac** [comment]
Have you set the `CLEANUP_TTL` config on the export server itself?

**Comment by sherifkozman** [comment]
i think it was applied over clean services, i can set it over the export server and run it if this will fix things and put them in sync @gurayAlsac

**Comment by gurayAlsac** [comment]
Try that, and reopen if you're still seeing index issues. The configuration story in general is pretty hairy and has lots of rough little edges like this. https://github.com/google/exposure-notifications-server/issues/728 might help to make it a little better.

**Comment by sherifkozman** [comment]
@gurayAlsac so we tried it by setting CLEANUP_TTL to 72h , it worked for a couple days getting the index sorted out. After we removed the env variable the entire list of older files were re added to the index about a few hundred entries of deleted files.

**Comment by gurayAlsac** [comment]
Right - WAI. The index file is driven solely by the contents of db and that env var, and doesn't check whether the files exist, or the state of the separate cleanup server. Perhaps there's a separate feature request here (add redundant check to ensure no deleted files are present) but I'm not sure if it would be high priority.

**Comment by mikehelmick** [comment]
@gurayAlsac - should we make files in the DB as "DELETED" when the cleanup-export job runs? and then exclude them.

would remove an env var that needs to be in sync

**Comment by gurayAlsac** [comment]
We should already be doing that. We update a file as deleted here:
https://github.com/google/exposure-notifications-server/blob/1208580e92e3a9f23d85eb570fbdff8d1f6e7a00/internal/export/database/export.go#L775

And on the export/index creation side, we already filter for only status `COMPLETED` and filter out `DELETED`. But we do it on the whole ExportBatch:
https://github.com/google/exposure-notifications-server/blob/1208580e92e3a9f23d85eb570fbdff8d1f6e7a00/internal/export/database/export.go#L653

So its possible that if one file of a batch fails deletion the entire batch doesn't get marked as deleted and it gets included in the index. And that might be more likely with more frequent file generation or in a test env w/ lower quota.

It should be a simple change to also filter for export file status and not just batch status.

But TBH I had imagined that most server impl's would make use of TTLs on the underlying object stores (https://cloud.google.com/storage/docs/lifecycle, https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html) and possibly even simple triggers in the db to guarantee cleanup.
