### ISSUE TITLE
test: Create an integration test for interfacing with the verification server

### ISSUE THREAD

**Issue by stati0n** [google/exposure-notifications-server#712]
### TL;DR
Create an integration test for interactions with the verification server.  The verification server can be mostly mocked.

**Comment by stati0n** [comment]
This is going to need a positive and negative case, one where the exposure is verified, and one where it is not verified.

**Comment by chaodaiG** [comment]
https://github.com/google/exposure-notifications-server/pull/829 added the scenario of exposure is verified, but not the case of exposure not verified yet, so there is still some work left to do

**Comment by argetlam-cs** [comment]
#868 added the scenario for the exposure not yet verified

**Comment by chaodaiG** [comment]
Cool
/close
