### ISSUE TITLE
Azure Storage credentials cannot be resolved from a secrets store - they are assumed to be directly in the environment

### ISSUE THREAD

**Issue by nmiodice** [google/exposure-notifications-server#715]
### TL;DR
The credentials for Azure Storage accounts are not able to be pulled from KeyVault (using the `secret://` prefix) because they are pulled directly from the environment. The code can be found [here](https://github.com/google/exposure-notifications-server/blob/main/internal/storage/azure_blobstore.go#L39-L67).

### Design

**Proposal**
The values could be more configurable if resolved using the [resolver](https://github.com/google/exposure-notifications-server/blob/ad7e1e00d20858f2f8a40a85c48143bdd9baf113/internal/setup/setup.go#L126) strategy that is currently being used for other secrets, like `DB_PASS`

**Alternatives considered**

Yes; none of them seem as idiomatic as the proposed design

**Resources**
https://github.com/google/exposure-notifications-server/blob/main/internal/storage/azure_blobstore.go#L39-L67

**Additional information**

No

**Comment by sethvargo** [comment]
I'm fine supporting auth via the environment, but in talking through the use case on chat, I'm not convinced this is a good pattern.

**Comment by jpflueger** [comment]
After further investigation I was able to get Managed Identity authentication working for Azure Blob Storage. I can't edit the design proposal so I'll add an updated version here.

## Design 
### Proposal
If the AZURE_STORAGE_ACCOUNT_KEY environment variable is not set, use the Managed Identity endpoint to request an access token for the managed identity that can be used to access the Storage Blob Container. 

### Alternatives considered
- Resolving the secrets via `secret://{kv-name}/{kv-secret}/{kv-secret-version}`. This would be possible but would result in "using [the] secret manager for privilege escalation". It was generally considered cleaner to use the pod's identity to access the storage container.

### Resources
https://github.com/google/exposure-notifications-server/blob/main/internal/storage/azure_blobstore.go#L39-L67

### Additional Information
No

**Comment by sethvargo** [comment]
> After further investigation I was able to get Managed Identity authentication working for Azure Blob Storage.

Dope!

> If the AZURE_STORAGE_ACCOUNT_KEY environment variable is not set, use the Managed Identity endpoint to request an access token for the managed identity that can be used to access the Storage Blob Container.

Seems reasonable and matches how the GCP one works.

I left two comments on the PR, but otherwise I think this is great!
