### ISSUE TITLE
Update federation to support v1.5

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#717]
### TL;DR

Federation APIs need to support key revision and extended date, see #663 

/kind enhancement

**Comment by mikehelmick** [comment]
Also needs to be updated to support the traveller bit in addition to revised keys #793

**Comment by mikehelmick** [comment]
/assign

Plan
- Deprecate the existing federation implementation.

- Implement an exporter-importer job that can read another system's export files 

This is also in service of #928

**Comment by jendakol** [comment]
Hi @mikehelmick,
what does it mean to `Deprecate the existing federation implementation`? We're in CZ currently about to implement support for [European Federation Gateway Service](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/blob/master/docs/software-design-federation-gateway-service.md) and the existing `Traveler` flag in both publish request and DB could be quite useful for that. Do you plan to remove it? Do you plan to support some other federation, possibly/hopefully the one mentioned above?
Thanks!

**Comment by mikehelmick** [comment]
We have an existing gRPC based federation mechanism that was not updated as the protocol changed. That is what we plan to deprecate.

The traveler flag is not being removed.

#965 is an existing feature request for EFGS support. 

We are currently working on a federation mechanism that can work without the source server having to implement anything, by using just the public export files from that server.

@jendakol - if you want to see this sever implement EFGS, please chime in on #965 - we would also accept PRs to this repository.

**Comment by mikehelmick** [comment]
The federation by means of importing export files won't work due to the data padding we employ.

This would create a potentially unbounded growth function, causing the generated data to be imported into primary storage and re-exported.

Instead, we will first update the existing gRPC interface to be compatible w/ v1.5
