### ISSUE TITLE
Smoke test terraform deployment

### ISSUE THREAD

**Issue by chaodaiG** [google/exposure-notifications-server#723]
### TL;DR

Create smoke tests that could test terraform deployment, as well as automated tests for ensuring terraform deployment work

### Design

**Proposal**

**Comment by chaodaiG** [comment]
@sethvargo  and @stati0n, I have created this issue tracking the discussion of this topic. I could be wrong but I'm considering it being a prerequisite for testing Cloud Run

**Comment by stati0n** [comment]
It shouldn't be a hard blocker for Cloud Run.  We could orchestrate a deployment to Cloud Run ourselves via a Cloud Build.

**Comment by chaodaiG** [comment]
> It shouldn't be a hard blocker for Cloud Run. We could orchestrate a deployment to Cloud Run ourselves via Cloud Build.

That's true for services, but for other resources like database, gcs etc. will need to be configured as what's been done by terraform. Or alternatively, we could deploy services using in mem databases?

**Comment by stati0n** [comment]
We could.  I'm willing to say it's a prereq if we think it's enough work to work around it.

**Comment by chaodaiG** [comment]
> We could. I'm willing to say it's a prereq if we think it's enough work to work around it.

Makes sense. I will create another issue gathering requirement for testing Cloud Run

**Comment by chaodaiG** [comment]
Created #727 for discussing Cloud Run tests

**Comment by chaodaiG** [comment]
Done in https://github.com/google/exposure-notifications-server/pull/948

/close
