### ISSUE TITLE
Rate limit for exposure API 

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#729]
Is there an intention to apply a rate limit function similar to the [Verification server ](https://github.com/google/exposure-notifications-verification-server/pull/111)to mitigate possible attacks ?

**Comment by sethvargo** [comment]
This server design intentional obscures any user-identifiable information, including IP addresses. I don't think we plan to add rate limiting, especially with the new PHA verification flow. @mikehelmick thoughts?
