### ISSUE TITLE
Running over AWS

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#741]
There are multiple references for supporting different AWS components such as S3 and AWS KMS, but to be able to run the containers on a non GCP cloud provider new builder scripts need to be coded, is that correct.

I tried running sample containers that were previously built and the crashed trying to find GCP application-default-credentials.

Is that the case and would it make more sense to keep things as is and consider Anthos GKE on AWS.
The Goal is to cater for HAs who have restricted requirements running workloads over specific providers while we dont have to redo lots of re-work.

**Comment by sethvargo** [comment]
Hi @sherifkozman 

Yes, that's correct. We really only have expertise in Google Cloud, so those are the configurations we provide (via Terraform). If you want to run on another cloud provider, you need to set the appropriate configuration values via environment variables (e.g. SECRET_MANAGER, KEY_MANAGER). This is documented in [Configuring Components](https://github.com/google/exposure-notifications-server/blob/main/docs/getting-started/deploying.md#configuring-components).

**Comment by sherifkozman** [comment]
Thanks @sethvargo ,would you think Anthos for AWS is a happy medium retaining all GCP configs (mostly) as is while extending work load locations onto other providers?

**Comment by sethvargo** [comment]
The Cloud Run bits will definitely work, but I'm not sure if we support Cloud SQL via Anthos yet, so you'd need to use RDS or run the database as a container inside Anthos GKE.

**Comment by sherifkozman** [comment]
There are different options I would think of, either RDS, whitelisting the AWS cluster to access cloud sql or use a similar vpn tunnel between AWS and GCP similar to the setup user in migrate for compute between AWS and GCP

**Comment by sethvargo** [comment]
Yea, there's definitely a wealth of options. I think the challenge might be that we (the Google team) lack expertise on those other cloud platforms, so we may not be able to help debug things.

**Comment by sherifkozman** [comment]
Thanks for confirming, we are exploring best and fastest routes to accommodate to requests without having to rework a lot of the work.

Most of all the automation of releasing new updates and the builder/deployment work. 

Terraform scripts for AWS or azure won't be the only part needs changing if an HA decides to launch over a different cloud provider, hence the Anthos option is a sweet spot

**Comment by mikehelmick** [comment]
I have tested running the system on Anthos in the past, there is nothing in the code itself that would prevent you from running on any container serving infrastructure, including Anthos on AWS.

It is possible to run the code without needing Google application credentials, but that requires appropriate config.

If the HA that you are working with needs to be run on an alternate cloud, please have them make that request through their Google devrel partner. It's possible that we can  partner with an interested, authorized HA to make this happen, but we have not officially received such a request.

From a practical standpoint, the Cloud Run deployment option is the lowest cost, lowest maintenance, lowest operational burden solution we could build. That should be factored in when making a cloud platform choice.

/close
