### ISSUE TITLE
exposure service can't create metricDescriptors in SD

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-server#745]
### TL;DR
Exposure in Cloud Run is logging this all the time
```
Failed to export to Stackdriver: rpc error: code = PermissionDenied desc = Permission monitoring.metricDescriptors.create denied (or the resource may not exist).
```

I have the newest version deployed, including having correct ENV var PROJECT_ID specified and SA has the correct role from terraform

I have Stackdriver enabled, it works for other workload on this GCP project.

**Comment by sethvargo** [comment]
Can you make sure:

1. The service is using the exposure service account
1. The exposure service account has the `monitoring.metricWriter` role

?

**Comment by marekaf** [comment]
cloud run revisions detail: <img width="535" alt="Screenshot 2020-07-19 at 19 48 22" src="https://user-images.githubusercontent.com/16442967/87881329-cefd4a80-c9f8-11ea-9407-a6886f27be61.png">

IAM: <img width="1087" alt="Screenshot 2020-07-19 19 51 01" src="https://user-images.githubusercontent.com/16442967/87881384-30bdb480-c9f9-11ea-8212-5937de8ee99f.png">

**Comment by sethvargo** [comment]
The full email is blacked out - does it match the email from the Cloud Run screenshot? If it does, I'm really not sure.

**Comment by marekaf** [comment]
> The full email is blacked out - does it match the email from the Cloud Run screenshot? If it does, I'm really not sure.

Yes, it does. I wanted to black out the first screenshot too, oops.

**Comment by marekaf** [comment]
@sethvargo 
I created a new GCP project, deployed with terraform everything from scratch, added something in the web admin and ran the exposure-client/main.go and now the exposure service is logging this 
```
Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured for the metric.: timeSeries[0-9]
```
which I've seen already in other svcs' logs. Any ideas?

**Comment by sethvargo** [comment]
That's a known issue (https://github.com/google/exposure-notifications-server/issues/699). We haven't had a chance to fix it yet.
