### ISSUE TITLE
terraform: invalid database_flags for CloudSQL

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-server#746]
### TL;DR
Hello 👋 
I'm getting
```
google_sql_database_instance.db-inst: Creating...

Error: Error, failed to create instance en-utwrv: googleapi: Error 400: Value requested is not valid., invalidFlagValue
```
because of the db flag max_connections

If I delete it
```
-    database_flags {
-      name  = "max_connections"
-      value = "100000"
-    }
```
I can proceed to create the db.

Since `max_connections` are BETA and this resource is not using `google-beta` provider, can that be the cause of the error?

**Expected behavior**
I expected the db to be provisiones without any errors.

**Observed behavior**
I got the above-mentioned error

**Additional information**
I'm trying to run the CloudSQL in europe-west1 if that makes any difference.

Thanks!

**Comment by sethvargo** [comment]
This error is because the instance size you chose can't accommodate that many connections. We could make the max_connections a variable, or we could document the restriction.

**Comment by sethvargo** [comment]
https://cloud.google.com/sql/docs/quotas#postgresql

**Comment by marekaf** [comment]
Aha! Thanks!
It'd be great if that was a documented variable. The error message is not super helpful here.

**Comment by jixiangox** [comment]
Combination of region changed and db-inst (standard one) is not workable. The err logs:

Error: Error, failed to create instance en-hrebk: googleapi: Error 400: Value requested is not valid., invalidFlagValue

  on database.tf line 22, in resource "google_sql_database_instance" "db-inst":
  22: resource "google_sql_database_instance" "db-inst" {
