### ISSUE TITLE
Upgrade dependency for apache thrift dependency due to security vulnerabilities

### ISSUE THREAD

**Issue by whaber** [google/exposure-notifications-server#749]
### TL;DR

Upgrade dependency for apache thrift to 13.0 dependency due to security vulnerabilities in 12.0

Knows vulns in v12:
* High: Out-of-bounds Read in github.com/apache/thrift 
* High: Loop with Unreachable Exit Condition (Infinite Loop) in github.com/apache/thrift 

**Expected behavior**

Did dependency security scan and found a version of a library in use with known security vulnerabilities

No libraries in use with known security vulnerabilities

### Reproduction

Scanned with dependency scanner in GitLab
**Screenshots**
![image](https://user-images.githubusercontent.com/41373231/87945101-45885f80-ca6e-11ea-82bb-313d6c5d7db5.png)

**Comment by sethvargo** [comment]
We're not directly using apache thrift. Looking at the module tree, it appears to be used by a transitive dependency of opencensus:

```text
$ go mod graph | grep thrift
go.opencensus.io@v0.20.1 github.com/apache/thrift@v0.12.0
github.com/go-kit/kit@v0.10.0 github.com/apache/thrift@v0.13.0
go.opencensus.io@v0.19.2 github.com/apache/thrift@v0.12.0
go.opencensus.io@v0.20.2 github.com/apache/thrift@v0.12.0
go.opencensus.io@v0.19.1 git.apache.org/thrift.git@v0.12.0
```

I attempted to upgrade to a new version, but it looks like upstream hasn't upgraded yet.

@mikehelmick thoughts?

**Comment by odeke-em** [comment]
@mikehelmick, thanks for the tag! Sure, I am happy to help. I'll take this on.

**Comment by sethvargo** [comment]
This has been fixed.
