### ISSUE TITLE
Centralize integration tests to avoid duplication

### ISSUE THREAD

**Issue by chaodaiG** [google/exposure-notifications-server#751]
A load test for cleaning up exported keys at scale was added in https://github.com/google/exposure-notifications-server/pull/713, which contains duplicated code with https://github.com/google/exposure-notifications-server/blob/e341b531d8ec2f82bbf9019af8f6c30cac886d10/internal/integration/integration_test.go. The reason for this duplication was discussed in https://github.com/google/exposure-notifications-server/pull/713#discussion_r456787696.

Creating this issue tracking the future improvement of centralize this logic so that duplicated code could be reduced, and ideally merge them into a single test.

**Comment by chaodaiG** [comment]
Created a draft PR with the best optimization that I could come up with https://github.com/google/exposure-notifications-server/pull/754. The time it takes for creating 100 batches of exports is ~210 seconds

**Comment by mikehelmick** [comment]
there’s also some duplication w. the unit tests in internal/publish/publish_test.go - although I don’t want those tests lessened as we get good code coverage numbers and assurances from those tests.

**Comment by sethvargo** [comment]
This seems to have been fixed as the file in question no longer exists and I can't find dupe code anymore.
