### ISSUE TITLE
Converting key_data to byte array after download

### ISSUE THREAD

**Issue by mattThousand** [google/exposure-notifications-server#768]
@mikehelmick when the client downloads an `export.bin` file containing keys with keydata properties such as `keydata: "rb[\220\255?\202\3115\355QTE\266\23"`, how should the keydata string be converted to a byte array? (asking for debugging purposes, we'd like to confirm that specific keys are located in specific files on the server to ascertain why we did or did not receive an exposure notification after processing that file). We're able to convert keys locally in swift with `[UInt8](data)` but it is not clear how to parse the strings contained in the `export.bin` files

**Comment by gurayAlsac** [comment]
The key_data field isn't of string type, it's protobuf `bytes`: 
https://github.com/google/exposure-notifications-server/blob/dfe02eb3a54ed4d5133931bc6defde175bddbe7d/internal/pb/export/export.proto#L75

Depending on the language you are using that might have a different primitive type:
https://developers.google.com/protocol-buffers/docs/proto#scalar

You can see how the underlying api parses it here:
https://github.com/google/exposure-notifications-internals/blob/a0394e69c51aa118f5000b8a2c2f15f1f9aedb7d/exposurenotification/src/main/java/com/google/samples/exposurenotification/data/fileformat/TemporaryExposureKeyConverter.java#L33

I think `protoc -decode` dumps out a trickier octet format that might be harder to work with (e.g., if you are trying to quickly print out a key from one place to manually check against another) so easiest might be to work through protobuf libraries to do the comparisons. Perhaps you can build a little CLI tool.

**Comment by mikehelmick** [comment]
The device side apps do not need to interpret this data. You're free to, but there's no need to. Handling the bundle to the OS is all that is necessary.

**Comment by mikehelmick** [comment]
Also - this tool can be used to unmarshal and print out an export file

https://github.com/google/exposure-notifications-server/blob/main/tools/export-analyzer/main.go
