### ISSUE TITLE
Export directory

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#774]
Add the ability to generate an export directory that shows all exports available from the sever, the regions they cover and export frequency.

**Comment by jeremyfaller** [comment]
So, I've been doing some thinking about this. My conclusions are as follows:

1. As these endpoints will be hit daily by traveling users, we need to weigh the bandwidth costs of metadata vs just downloading. For some jurisdictions, (eg, let's say small island nations), it might make sense to not have much metadata at all, and just return the codes. I think it's important that whatever system, we should try to respond properly to http `HEAD` requests so apps could forgo downloading the metadata, and just look at update times.
2. There are so many corner cases I am not capable of designing for right now. As such, simpler is probably better than more complex.

With these two points in mind, I think I've come to the following design. Starting with the following structures:

```
type Region struct {
  Name string `json:"name"`
  URL string `json:"url"` // link to download JUST this region's URL
  NextUpdate time.Time `json:"next_update"`
  UpdateFrequencyMin int `json:"frequency_min"`
}

type EndPointResources struct {
  Name string `json:"name,omitempty"`
  LocalURL string `json:"local_url"` // URL needed for only local users.
  TravelingURL string `json:"traveling_url,omitempty"` // URL for all possible export data. (union of all region data.)
  Regions []Region `json:"regions,omitempty"`
}
```

This is a minimally functional first pass at the metadata structure.

**`/export-info{?#with_regions}.GET`** returns a `EndPointResources`. To save on bandwidth, this can be requested with an optional URL param `with_regions` that will return the region list. Non-traveling users can omit that parameter to just get the short info.

All of the URLs returned, also respond to `HEAD` requests, setting `Last-Modified`. Mobile apps can possibly save on bandwidth by only issuing a `HEAD` request, and then backing off if nothing's changed.

Thoughts on this?

**Comment by mikehelmick** [comment]
we may revisit this in the future
