### ISSUE TITLE
exposure services fail to run after update

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#799]
After updating to the latest codebase the exposure services fails to run missing a KMS ID
*publish.NewHandler: revisiondb.New: no KMS key ID passed in to revision.New*

has there been any update to the terraform service that requires a new ENV to be added ?

**Comment by mikehelmick** [comment]
Yes - there is a new symmetric encryption key required to power the revision token feature.

This has all been added to the terraform, running that should provision the keys.

You may need to add the new env vars manually, depending on if things have drifted or not.

REVISION_TOKEN_AAD is a secret - series of generated random bytes, the terraform will create this for you and put it in secret manager.
REVISION_TOKEN_KEY_ID is the crypto key ID, again terraform will create an initial version for you.

Once that's there, the sever will generate it's own AES encryption key, wrap it w/ the KMS key and store it in the database.

All new env vars for this change

https://github.com/google/exposure-notifications-server/blob/main/internal/publish/config.go#L59

let me know if that helps

/assign

**Comment by sherifkozman** [comment]
@mikehelmick Thanks this is very helpful.
Also this started showing up in responses which is more descriptive than earlier, yet would this be related to hmac calculation on the client side or that the verification server code base might be a bit old.
Given that the issuer is a match so as the version and certificate signing ?

**Comment by mikehelmick** [comment]
What started showing up in responses?

**Comment by sherifkozman** [comment]
sorry it was missed from my previous message : 
1- for Apps with : Revision Token Enforcement Disabled & Health Authority Verification Disabled = true
Response contains :  attempt to revise key not in revision token

2- For apps with verification disabled = false 
Responses : {"revisionToken":"","insertedExposures":0,"error":"Internal Server Error","padding":""} and logs show " error writing exposure record: attempt to revise key not in revision token."

**Comment by mikehelmick** [comment]
The revision token is part of the security protocol around verification and the fact that now keys can be revised:
 https://github.com/google/exposure-notifications-server/issues/663

If you want to send the same TEK later on a subsequent publish request, you must send the revisionToken that was returned on the initial upload.

If you have revision token enforcement disabled - and still getting an error, that would be a bug.

/kind bug

**Comment by sherifkozman** [comment]
so far that is the case @mikehelmick , we had to roll back all updates to a previous state as things were at stall.

**Comment by mikehelmick** [comment]
This should only be occurring when trying to upload the same set of TEKs (or at least overlapping)

Can you confirm that?

**Comment by sherifkozman** [comment]
That might be the case, however I believe it's best to wait until the recent issues on the verification server side are resolved so we can try a code update once more and confirm if the behavior remains the same

**Comment by mikehelmick** [comment]
ok - so make sure on a publish request that you are now capturing the publish response
   https://github.com/google/exposure-notifications-server/blob/main/pkg/api/v1alpha1/exposure_types.go#L91

And storing the "revisionToken" field.

The next time publish is called from the same device, the revision token must be passed in the publish request, unchanged.

The revision token itself is an encrypted structure of TEKs that that particular device has previously uploaded and is allowed to upload again.

**Comment by mikehelmick** [comment]
@sherifkozman - I verified revision tokens are working as intended.

I put together a tool that simulates what a mobile client would do (plus also issues the verification codes)
https://github.com/google/exposure-notifications-verification-server/pull/167

**Comment by sherifkozman** [comment]
We pulled in the latest updates and still the exposure service fails to run :
Different errors though : 
unable to read revision keys: unable to read keys: committing transaction: commit unexpectedly resulted in rollback1
publish.NewHandler: revision.New: reading revision key cache: unable to read keys: committing transaction: commit unexpectedly resulted in rollback1

**Comment by mikehelmick** [comment]
Did you run the DB migrations?

Sounds like a missing table

**Comment by sherifkozman** [comment]
Works perfect , i totally forgot we had a migration issue previously.
For the sake of clarification , for envs that are releated to secrets and KMS , would it be better to define the resource ID by a specific version or we define only the root resource ID and it will pick the latest version?

**Comment by mikehelmick** [comment]
For KMS

- if it's an asymmetric key, you want to specify the exact version
- for symmetric key, you just use the top level resource ID and the active version is selected for encryption and non disabled versions are used for decryption
- for Secrets - use the exact version ID you want
