### ISSUE TITLE
Invalid Report type error with a valid JSON Payload

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#842]
With recent updates we started getting a 401 error with invalid report type although transmission risk value is set correctly.

Running the same payload vs an older codebase seems to work find.

sample TeK : 
    "temporaryExposureKeys": [
        {
            "key": "UXmeJEJRoJndICMVdVspUw==",
            "rollingPeriod": 144,
            "rollingStartNumber": 2661264,
            "transmissionRisk": 0
        }

@mikehelmick

**Comment by mikehelmick** [comment]
ReportType only comes from the verificationPayload - can you share the claims in the verification certificate? or the rest of the request?

**Comment by mikehelmick** [comment]
Specifically: https://github.com/google/exposure-notifications-server/blob/main/pkg/api/v1/verification_types.go#L66
