### ISSUE TITLE
Keys verification

### ISSUE THREAD

**Issue by augard** [google/exposure-notifications-server#855]
### Question
Hi,
we are trying to get to work our key server (from main) with verification server (https://github.com/google/exposure-notifications-verification-server). Even when we have everything configured in admin we always get error "failed to parse: no rows in result set". We try to check everything, but we didn't find reason why it don't want to accept the VerificationPayload.

`publish API error: {RevisionToken: InsertedExposures:0 ErrorMessage:unable to validate diagnosis verification: error looking up issuer: diagnosis-verification-example : get health authority: failed to parse: no rows in result set Code:health_authority_verification_certificate_invalid Padding:}
`

**Comment by sethvargo** [comment]
Hi @augard - have you configured a health authority and verification server too? You need to register the verification server to the main server so it trusts signatures. Alternatively, for testing, you can bypass the verification server by setting `bypass_health_authority_verification` to `true` for the row in the `AuthorizedApp` table.

**Comment by augard** [comment]
Yes, i think we have everything configured on both servers. I know about that settings, but we need to get it working with verification to on. 

What setting it's need to have configured on verification server?

Thanks

**Comment by sethvargo** [comment]
Are you running the admin console GUI? (It's in this repo). If so, can you send me a screenshot of your configuration please? More info [is here](https://github.com/google/exposure-notifications-server/blob/main/docs/getting-started/publishing-temporary-exposure-keys.md#server-access-configuration).

**Comment by augard** [comment]
Yes, i sent you our configuration to your email address.

**Comment by mikehelmick** [comment]
The iss and aud fields currently come from envionment variables on the verification server (this will be moved into per-realm DB settings in the near future). Those fields must line up with your health authority configuration on the key server.

In the error message, this indicates that the key sever has no health authority configured with the issuer of `diagnosis-verification-example `

**Comment by augard** [comment]
Hi, thanks that was one issue, now how we can get key for health authority? It's one of keys created with command
```
gcloud kms keys create token-signing --location=us --keyring=signing --purpose=asymmetric-signing --default-algorithm=ec-sign-p256-sha256
gcloud kms keys create certificate-signing --location=us --keyring=signing --purpose=asymmetric-signing --default-algorithm=ec-sign-p256-sha256
```
?

**Comment by mikehelmick** [comment]
The `certificate-signing` key is the one used to sign certificates to allow upload to the key server.

**Comment by augard** [comment]
We now get error: `unable to validate diagnosis verification: crypto/ecdsa: verification error`

Do we need regenerate the keys after we changed env variables on verification server?

**Comment by mikehelmick** [comment]
If you changed the verification certificate signing key on the verification server, then yes, you need to update the configuration of this server to match.

That error indicates that (1) the public key is invalid or (2) the verification certificate itself has an issue / is incomplete.

You can use https://jwt.io to validate your verification certificates are parsable JWTs (including validating the signature)

**Comment by augard** [comment]
The tool helped a lot. Now it verified successfully. Thanks!
