### ISSUE TITLE
unable to validate diagnosis verification: HMAC mismatch

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#858]
We have been testing against 2 different verification servers one that is proviosned by @mikehelmick yet we still get the same error : 

unable to validate diagnosis verification: HMAC mismatch, publish request does not match disgnosis verification certificate.

we have tested 2 different servers with different JWT configs 

Any clues?
@sethvargo

**Comment by sethvargo** [comment]
Hi @sherifkozman - can you share more about how your constructing the requests?

**Comment by mikehelmick** [comment]
debugged w/ @sherifkozman 

Client was either sending the hmac secret or hmac value twice and not separating the tool.

For in illustrative example of how a client should operate, see https://github.com/google/exposure-notifications-verification-server/blob/main/tools/e2e-test/main.go

/close
