### ISSUE TITLE
Keyset validation will drop all keys if start interval of any key is out of bounds

### ISSUE THREAD

**Issue by hvisser** [google/exposure-notifications-server#862]
Our app is not using this project, but we ran into a similar issue as the one I'm reporting here and I thought I'd flag it.

### TL;DR
We've observed that mobile clients (iOS 13.5 confirmed) can return TEKs with a start interval that is way older than 14 days, mixed in with valid keys. The validation in https://github.com/google/exposure-notifications-server/blob/702c0796ecf6ab1a6816aaa2dfe422fed39fce9d/internal/publish/model/exposure_model.go#L299 seems to abort the transformation if any key is invalid, hereby rejecting the entire batch.

I'm not an expert at go or this project so I might be wrong 🙏 

**Expected behavior**
The invalid key is filtered out, but processing is continuing

**Comment by hvisser** [comment]
So after looking at this for a while and deciding to create an issue I now realise that this function is called _per key_ and that invalid keys are in fact effectively dropped. So never mind me then 😅

**Comment by mikehelmick** [comment]
The errors do cascade up, so one bad key metadata will cause the whole batch to be rejected.

I’ve reached out to both the iOS and Android develoeprs to verify if they expect this to happen in production devices or not. My previous understanding was not.

**Comment by hvisser** [comment]
We definitely saw this on one or more production 13.5 iOS device. My own device I hardly ever turn on as an Android developer and it was posting keys as old as June and July. It appears that iOS is keeping 14 keys vs 14 days worth of keys or something like that.

**Comment by mikehelmick** [comment]
I confirmed that iOS does indeed return keys older than 14 days and that Android devices (at least on newer releases) will not. I'll have a fix for this to have partial success at the server shortly.
