### ISSUE TITLE
creating export configs with different bucket names and similar filename root results error

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-server#866]
### TL;DR
Creating 2 different export configs for different GCS bukcet but same filename root results error

**Screenshots**
![Screen Shot 2020-08-12 at 5 08 42 PM](https://user-images.githubusercontent.com/666788/90080169-c7ab2300-dcbe-11ea-89a1-81412f41c46b.png)

**Comment by sethvargo** [comment]
@gurayAlsac do you think it's okay to remove this uniqueness constraint?

**Comment by mikehelmick** [comment]
can't remove it, but could make it unique over bucket + root filename.

which should be a safe DB migration.

**Comment by sethvargo** [comment]
Well, we'd have to:

1. Create a new index that's unique on [bucket, filename]
1. Delete the existing index

AFAIK, it's not possible to "update" the fields an index is indexing

**Comment by sherifkozman** [comment]
I would wanna add there is an additional behaviour i spotted when fileroot value is left blank a new directory is being created within GCS with the value of "/" so index isnt actually created at the root of the GCS bucket

**Comment by gurayAlsac** [comment]
Agree w/ @mikehelmick that the constraint can be made unique over both filename root and bucket.

Out of curiosity, what's the use case for exporting to different buckets/same roots?

**Comment by mikehelmick** [comment]
@gurayAlsac - different buckets could be under different billing accounts.

**Comment by gurayAlsac** [comment]
Ah gotcha! So if someone were running a multi-tenant key server and wanted to isolate the resource consumption, but have respective apps use the same prefix schemes. Makes sense.
