### ISSUE TITLE
Failed to create files for batch

### ISSUE THREAD

**Issue by juantopx** [google/exposure-notifications-server#876]
Creating index file for batch 17: creating file /index.txt in bucket exposure-notification-export-cxxdc: storage.Writer.Close: googleapi: Error 400: Bucket is requester pays bucket but no user project provided., required.

**Comment by sethvargo** [comment]
Hi @juantopx - how have you configured your bucket? I don't believe we support "requestor pays" right now.

**Comment by juantopx** [comment]
Now Works Good... I create new bucket with same user to create a new version of export cloud run..
Works..

But file index.txt is Zero Size..

**Comment by mikehelmick** [comment]
There needs to be some data in the exposures table that would be picked up by the export (this means matching the exportonconfig region and in the correct time window).

If you don't have any data in the database, try running the generate server(`cmd/generate`) to place data in the databse.

**Comment by juantopx** [comment]
I run cmd/generate and output is this::

{"severity":"EMERGENCY","timestamp":"2020-08-16T15:53:45.201749538-04:00","caller":"generate/main.go:42","message":"setup.Setup: unable to create observability provider: unknown observability exporter type stackdriver","stacktrace":"main.main\n\t/root/exposure-notifications-server/cmd/generate/main.go:42\nruntime.main\n\t/root/.go/src/runtime/proc.go:203"}
exit status 1

**Comment by mikehelmick** [comment]
If you deployed to Google Cloud Platform via the provided terraform, the [generate service](https://github.com/google/exposure-notifications-server/blob/main/terraform/service_generate.tfl) is part of that deployment.

By default, it is deployed as a private service. You can use authenticate yourself [using curl](https://cloud.google.com/run/docs/authenticating/developers) or schedule this service to be invoked by cloud scheduler.

**Comment by mikehelmick** [comment]
Also - if you have an application that is uploading temporary exposure keys, that will also get data into the database.

**Comment by juantopx** [comment]
I make> using curl
and also> execute cloud scheduler "generate-worker"
and log in export is > Wrote index file "index.txt" with 0 entries (triggered by batch 25) 
index.txt  Size 0

**Comment by juantopx** [comment]
Sorry, have some solution

**Comment by juantopx** [comment]
I can't resolve this issue

**Comment by mikehelmick** [comment]
Hello - 

Can you share the details of your exportconfig? Screenshots from the admin console program or DB rows are fine. 

And then also the health authority configuration from admin console.

You can send screenshots to the email address in the README.md file on this repo

**Comment by juantopx** [comment]
https://docs.google.com/document/d/1GwAeEk8LExAXgdP9zNrSt8mRNCLUtUnOCMSIFPtN3ZU/edit?usp=sharing

**Comment by mikehelmick** [comment]
I requested access to that document

**Comment by juantopx** [comment]
Sorry, I add Editor Access to Document

**Comment by juantopx** [comment]
Last LOG Error >>>
2020-08-18 16:15:00.304 EDTFailed to create batches for config 1: fetching most recent batch for config 1: latest export batch end: starting transaction: read tcp 169.254.8.1:46756->10.60.0.2:5432: read: connection reset by peer, continuing to next config

**Comment by mikehelmick** [comment]
Are the any long lines around that? that's a DB connection reset.

**Comment by juantopx** [comment]
More of 20

**Comment by juantopx** [comment]
Another ERROR is

Failed to create files for batch: creating export file 1 for batch 240: unable to get signer for key projects/aig-expo-dev-05/locations/us-central1/keyRings/export-signing: KeyManager.NewSigner: failed to fetch public key: rpc error: code = InvalidArgument desc = Resource name 'projects/aig-expo-dev-05/locations/us-central1/keyRings/export-signing' does not match pattern 'projects/([^/]+)/locations/([a-zA-Z0-9_-]{1,63})/keyRings/([a-zA-Z0-9_-]{1,63})/cryptoKeys/([a-zA-Z0-9_-]{1,63})/cryptoKeyVersions/([a-zA-Z0-9_-]{1,63})'..

**Comment by juantopx** [comment]
This server> https://export-7ichwhq52q-uc.a.run.app

**Comment by mikehelmick** [comment]
Thanks for sharing that - for the signing key, you need to specify the full version of the key to use, so it is probably

`projects/aig-expo-dev-05/locations/us-central1/keyRings/export-signing/versions/1`

**Comment by juantopx** [comment]
I make the change.. 

Now the error is >

2020-08-18 18:15:00.812 EDTerror writing exposure record: starting transaction: read tcp 169.254.8.1:53020->10.60.0.2:5432: read: connection reset by peer
2020-08-18 18:15:00.815 EDTGET500404 B12 msGoogle-Cloud-Scheduler https://generate-7ichwhq52q-uc.a.run.app/

**Comment by mikehelmick** [comment]
any additional log information?

this could be an issue w/ the database credentials configuration or with the serverless VPC configuration.

**Comment by juantopx** [comment]
I recreate new version of service generate (sql conection not exist in the original) and make test...

**Comment by juantopx** [comment]
This is the output now >

2020-08-18 19:30:54.837 EDTGenerated 14 exposures
2020-08-18 19:30:54.848 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.848 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.848 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.848 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.848 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.849 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.849 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.849 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.849 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.849 EDTattempt to revise key not in revision token.
2020-08-18 19:30:54.849 EDTattempt to revise key not in revision token.

**Comment by mikehelmick** [comment]
ok - the revision error is a known issue

but you should have 14 exposures in the exposures table now

**Comment by juantopx** [comment]
But the file> https://storage.googleapis.com/prueba_a001/exposureKeyExport-PA/index.txt

is empty !!!

**Comment by mikehelmick** [comment]
Did you modify the generate service to put keys in the right region? Adding `?region=PA` to your request

**Comment by juantopx** [comment]
?region=PA

Only for clarify, this change is in ANDROID or Servers?

**Comment by mikehelmick** [comment]
That change is just on the server, specifically in how you invoke the generate service.

To further debug this, we'll need information like you posted in the doc you shared previously.

What I need to see

1) Rows in the exposure table including the assigned region code and created_at field.
2) Rows in exportconfig table
3) complete logs from an export service `/do-work` invocation.

Some things you can do to cycle your tests faster, set these environment variables

### `exposure` service
* `TRUNCATE_WINDOW=5m`

### `export` service
 * `TRUNCATE_WINDOW=5m`
 * `MIN_WINDOW_AGE=1s`

**Comment by mikehelmick** [comment]
Those changes will let you upload a TEK and see it in an export file within 10 minutes instead of 2 hours.
These settings should not be that low in production.

**Comment by juantopx** [comment]
I share Positive Result from 2 diferent devices >>

INSERT INTO "exposure" ("exposure_key", "transmission_risk", "app_package_name", "regions", "interval_number", "interval_count", "created_at", "local_provenance", "sync_id", "health_authority_id", "report_type", "days_since_symptom_onset", "revised_report_type", "revised_at", "revised_days_since_symptom_onset", "revised_transmission_risk", "traveler") 
VALUES
	('SrBM51rxJQTAKEfMsOKHnQ==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662560, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('JQKXO0D1O5puvB5jxhuCSw==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662704, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('T7xJYiMgWiqdsGnlrji/Ng==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662848, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('J2x9skyLooYXm/48zACVNQ==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662992, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('uxOcBc3t+gsE+9tBXtmZ/w==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2663136, 144, '2020-08-21 00:00:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('zJJs5K0G3WPe3dThGwOikA==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662416, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('DYvMSvCmWi8vij2x07nLbg==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662560, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('Cv06i+GWFZqTMfmQiX5/6w==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662704, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('2MWBh3I2Vfj8WlgneF+BLw==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662848, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('BYF8PW9jnwAi3hMlnUumZA==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2662992, 144, '2020-08-20 21:50:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false'),
	('TUerJsCovqpEOjhHHEf3JQ==', 1, 'pa.gob.aig.exposure.covid', '{PA}', 2663136, 144, '2020-08-21 00:00:00+00', 'true', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, 'false');

**Comment by juantopx** [comment]
2020-08-20 18:00:05.336 EDT Generating exposure 1 of 10
2020-08-20 18:00:05.357 EDT error writing exposure record: unable to check for existing records
2020-08-20 18:00:05.359 EDT GET500344 B27 msGoogle-Cloud-Scheduler https://generate-7ichwhq52q-uc.a.run.app/

**Comment by juantopx** [comment]
EDT GET 403 msChrome 84 https://generate-7ichwhq52q-uc.a.run.app/
The request was not authenticated. Either allow unauthenticated invocations or set the proper Authorization header. Read more at https://cloud.google.com/run/docs/securing/authenticating

2020-08-20 18:45:00.289 EDTerror writing exposure record: unable to check for existing records
2020-08-20 18:45:00.291 EDTGET500344 B33 msGoogle-Cloud-Scheduler https://generate-7ichwhq52q-uc.a.run.app/

**Comment by mikehelmick** [comment]
Those are logs from the generate service - can you share logs from the export service.

**Comment by juantopx** [comment]
Processing export batch 878 (root: "exposureKeyExport-PA", region: PA), max records per file 30000
Failed to create files for batch: creating export file 1 for batch 878: unable to get signer for key projects/aig-expo-dev-05/locations/us-central1/keyRings/export-signing/versions/1: KeyManager.NewSigner: failed to fetch public key: rpc error: code = InvalidArgument desc = Resource name 'projects/aig-expo-dev-05/locations/us-central1/keyRings/export-signing/versions/1' does not match pattern 'projects/([^/]+)/locations/([a-zA-Z0-9_-]{1,63})/keyRings/([a-zA-Z0-9_-]{1,63})/cryptoKeys/([a-zA-Z0-9_-]{1,63})/cryptoKeyVersions/([a-zA-Z0-9_-]{1,63})'..
2020-08-20 20:16:00.951 EDTNo more work to do
2020-08-20 20:16:00.952 EDTPOST200297 B114 msGoogle-Cloud-Scheduler https://export-7ichwhq52q-uc.a.run.app/do-work
2020-08-20 20:17:00.996 EDTNo more work to do
2020-08-20 20:17:00.998 EDTPOST200296 B22 msGoogle-Cloud-Scheduler https://export-7ichwhq52q-uc.a.run.app/do-work
2020-08-20 20:18:00.304 EDTNo more work to do

**Comment by mikehelmick** [comment]
Thanks - can you go into the cloud console and verify that key version exists?

https://console.cloud.google.com/security/kms

And if it does exist, the service account that the export service is running as must have permission to be a signer/verifier for that key

**Comment by juantopx** [comment]
1 | Enabled | Elliptic Curve P-256 keySHA256 Digest | 8/4/20, 12:24 AM | Generated |   |  
-- | -- | -- | -- | -- | -- | --

**Comment by mikehelmick** [comment]
in that case it is most likely that the service account does not have permissions to access the key. 

This is the permission that is needed.

If you used the terraform to set this up, the service account should begin with `en-export-sa@`

**Comment by juantopx** [comment]
en-export-invoker-sa@*******************.gserviceaccount.com

Now assign ROLE for Verify and Read

**Comment by juantopx** [comment]
2020-08-20 22:40:00.996 EDT GET200235 B69 msGoogle-Cloud-Scheduler https://export-7ichwhq52q-uc.a.run.app/create-batches
2020-08-20 22:41:01.079 EDT Processing export batch 908 (root: "exposureKeyExport-PA", region: PA), max records per file 30000
2020-08-20 22:41:01.090 EDT No records for export batch 908
2020-08-20 22:41:01.262 EDT Wrote index file "exposureKeyExport-PA/index.txt" with 0 entries (triggered by batch 908)
------------------------
No Secret Error but index.txt Zero Size

**Comment by mikehelmick** [comment]
Did you add more records in the export table first?

You can delete / recreate batches if you delete all records from the exportbatch table.

**Comment by juantopx** [comment]
Yes, always clear table exposure , exportbatch and create 1 or 2 POSITIVE RESULTS from 2 diferent devices

**Comment by gurayAlsac** [comment]
Generating a bug report might help us debug further. The initial issue
(creating batch files) seems resolved.

Would you be able to work with your Partner Developer Relations contact to
troubleshoot this issue?
