### ISSUE TITLE
Health check endpoint for Exposure API

### ISSUE THREAD

**Issue by andrebriggs** [google/exposure-notifications-server#881]
### TL;DR
We would like to be able to send synthetic requests to the exposure API (publish) just to make sure the API is running. This requires getting a 200 HTTP code back with having to send legitimate key data and correspond with the verification server first.

### Design

**Proposal**
Another endpoint on `exposure`  that simply returns 200 http code. 

**Alternatives considered**

Going through the overhead of creating legitimate key data with large payload sizes, and pre-work to establish trust with the verification server. Also polluting the DB with fake data.

**Comment by sethvargo** [comment]
This is one of the reasons we recommend chaff requests. Are you having trouble with the chaff requests?

**Comment by icco** [comment]
We have `/health` on all of the binaries of the verification server for this cause.
