### ISSUE TITLE
Cost evaluation

### ISSUE THREAD

**Issue by georules** [google/exposure-notifications-server#882]
### Question

The current overall cost estimation is based on `1,250 new cases daily`.  It seems that the 7-day average of daily new cases is closer to 50,000 cases daily in the US.  Should we update this documentation to reflect this case load, or perhaps, make some note as to why 1,250 cases daily was selected as the example calculation?

https://github.com/google/exposure-notifications-server/blob/main/docs/getting-started/estimating-costs.md#calculating-the-overall-cost

https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/cases-in-us.html

**Comment by sethvargo** [comment]
Hi @georules 

The original estimate was based on 0.01% infection rate. It should be trivial to adjust the numbers to higher or lower values based on locality and risk. The network, storage, and database are the largest cost, but only the network and storage scale linearly with use.
