### ISSUE TITLE
export-analyzer

### ISSUE THREAD

**Issue by puskaiz** [google/exposure-notifications-server#888]
### Question

The export-analyzer tool checks if the keys are in the future (14 days) - lines 88, 89 and 108 - https://github.com/google/exposure-notifications-server/blob/main/tools/export-analyzer/main.go. 
Is this the expected behavior? Or it should check if the keys are in 14 days past?

Shouldn't it also use the file date to calculate the floor and ceiling?

**Comment by mikehelmick** [comment]
looks like a negative sign got removed

The file date / name doesn't have prescribed semantic value, so that is why the max key age is a flag.

/kind bug
/assign

**Comment by puskaiz** [comment]
Will You add the negative sign?

What if I want to check a 2 days old file? floor and ceiling are calculated from 'now'.

**Comment by mikehelmick** [comment]
Would an optional flag for "now adjustment" help?

**Comment by puskaiz** [comment]
I think it is needed. Thanks.
