### ISSUE TITLE
Additional partial success support

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#893]
Allow for partial success in this scenario.
Assuming 2 regions are on a shared server.

* User uploads likely diagnosis with AppA, and gets revision token indicating as such
* User changes regions and installs a different app, AppB
* 5 days later, user gets a positive test in their new region. Currently key upload would fail because AppA doesn't hold the revision token for days -6 to -14
  * In this case, accept the 5 keys that haven't been seen before. Issue a new revision token for just those

/kind enhancement

**Comment by sethvargo** [comment]
This all makes sense if the third bullet meant to say "fail because **AppB** doesn't hold the revision token for days -6 to -14". Is that correct @mikehelmick?

**Comment by mikehelmick** [comment]
The 3rd large bullet describes current behavior -the sub-bullet describes desired behavior
