### ISSUE TITLE
More specific errors on certificate failures

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#903]
Currently all verification certificate issues result in the same error code, 'health_authority_verification_certificate_invalid'

Change this to be more specific

/kind enhancement

**Comment by jeremyfaller** [comment]
Does this require a rev on the API version? (just asking...)

**Comment by sethvargo** [comment]
We could change the error _message_ without revving the API. I think changing the code should rev the API though.

**Comment by mikehelmick** [comment]
sorry - Seth is right on the intention here, keep the error code, but provide a more specific reason to the developer in the message

**Comment by jeremyfaller** [comment]
As I read the code, I only see codepaths that result in meaningful messages. Without any further info, I think this is obsolete.

(Note, I also read the blames on most of the files, and again, I don't see any recent changes that would be relevant. I don't think there's work to be done here unless you have noted examples for when this bit us.)

**Comment by mikehelmick** [comment]
thanks - I'll take a second look and see if I can jog my memory

**Comment by sethvargo** [comment]
I just took a run through and can't see anywhere. I think we did this as part of the api errors refactor.

/close
