### ISSUE TITLE
retry logic for SQL transactions

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-server#922]
Hi,
we are experiencing a lot of 4xx (404, 401) from mobile app / curl clients on key uploads in the past weeks

Client is getting in about 50% of the cases:
```
{“error”:“Internal Server Error”,“code”:“internal_error”}
# or
{"error":"error loading health authority config: authorizedapp: failed to read a.b.c from database: get authorized app: starting transaction: write failed: write tcp 169.254.8.1:47284-\u003e10.1.0.2:5432: write: connection reset by peer","code":"unable_to_load_health_authority"}
```
Eventually it always ends up with a 200 success, but the error rate is very high.

with very minimal load (15 db connections maximum) 

server is logging these
```
db=main,user=notification LOG: could not receive data from client: Connection reset by peer
```

Even though it looks like some network between Cloud Run and CloudSQL might be a bit laggy / unreliable sometimes, from this code I assume there is no retry logic implemented. We are currently implementing retry logic on clients and I'll try to debug the CloudSQL connection but it'd be helpful if the server had some kind of retry logic as well. Wdyt? 
https://github.com/google/exposure-notifications-server/blob/d9c3fd849921fc7d54126f2e7952b45154504dda/internal/authorizedapp/database/authorized_app.go#L152

Thanks!

**Comment by mikehelmick** [comment]
Can you either update past [this commit](https://github.com/google/exposure-notifications-server/commit/f9f169285e7aa0e9da09a7110b0a695a340ab929) or set `DB_POOL_HEALTH_CHECK_PERIOD` to `1m` on your services?

We believe this should precent the connection resets.

**Comment by marekaf** [comment]
I'll try to set the ENV var. Thanks for the quick response!

**Comment by mikehelmick** [comment]
looks like there are 2 items that need to be set

https://github.com/google/exposure-notifications-server/commit/b1c4a0d9e3db0091a2246360c11af56a7ec18a2c

**Comment by mikehelmick** [comment]
see that commit, you can set those manually or upgrade and get the defaults

**Comment by mikehelmick** [comment]
We cut release v0.5.1 that contains all of these settings as default.

Please let us know if this is still occurring after you’ve updated past that point. Thanks!

**Comment by marekaf** [comment]
@mikehelmick thanks for the support, after setting everything you proposed, it seems like we stopped getting 4xx errors due to this healthcheck issue (we started getting them for different reason but that should be solved too). We'll be upgrading soon past the v0.5.1 so that should be resolved too.
Thanks again!
