### ISSUE TITLE
Check routing

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#930]
We have a report that on the exposure service

`/` serves v1alpha1
`/v1/publish` serves v1
`/v1/publish/` serves v1alpha1

/kind bug

**Comment by icco** [comment]
What's the proper functionality here?

**Comment by mikehelmick** [comment]
I think that `/v1/publish/` should 404

**Comment by sethvargo** [comment]
I've confirmed this behavior. Working on a fix.

/assign

**Comment by nmiodice** [comment]
*Not asking for a change here, just a curious reader*

Is there a reason to return 404 instead of publish the `v1` API @mikehelmick?

**Comment by mikehelmick** [comment]
This totally could go either way. I have a personal preference for being exact on things like this.
