### ISSUE TITLE
Error on terraform apply on vpcaccess.googleapis.com service

### ISSUE THREAD

**Issue by besingamkb** [google/exposure-notifications-server#932]
### Question

I am trying to deploy exposure server on our own gcp account. I am pretty new to gcp and terraform. And I got stuck on the error after I execute `terraform apply`. Our gcp account have been enabled billing. And I have follow every steps from the <a href="https://google.github.io/exposure-notifications-server/getting-started/">official docs</a> and <a href="https://github.com/google/exposure-notifications-server/tree/main/terraform">deploying with terraform</a> then I got until the errors below. 

```
null_resource.migrate (local-exec): Finished Step #1 - "migrate"
null_resource.migrate (local-exec): PUSH
null_resource.migrate (local-exec): DONE
null_resource.migrate (local-exec): -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

null_resource.migrate (local-exec): ID                                    CREATE_TIME                DURATION  SOURCE                                                                                            IMAGES  STATUS
null_resource.migrate (local-exec): 16082944-ccd9-4c81-bdd1-741514d590ed  2020-08-30T16:32:31+00:00  1M52S     gs://gaen-project-name_cloudbuild/source/1598805146.595107-09c406fd75a34731976a71eb5e92cc9c.tgz  -       SUCCESS
null_resource.migrate: Creation complete after 2m1s [id=1281597494475427654]

Error: Error running command './../scripts/build': exit status 1. Output: ✋ Uncommitted local changes!




Error: Request "Enable Project Service \"vpcaccess.googleapis.com\" for project \"gaen-project-name\"" returned error: failed to send enable services request: googleapi: Error 400: Another activation or deactivation is in progress for the following service(s): 
vpcaccess.googleapis.com and project gaen-project-name., failedPrecondition

  on main.tf line 27, in resource "google_project_service" "services":
  27: resource "google_project_service" "services" {
```
Below is the command that I have executed so far.
```
// history
   66  git clone git@github.com:google/exposure-notifications-server.git
   67  cd exposure-notifications-server/
   68  git checkout tags/v0.5.1
   69  git status
   70  unset GOOGLE_APPLICATION_CREDENTIALS
   71  export PROJECT_ID="gaen-project-name"
   72  gcloud auth login && gcloud auth application-default login
   73  cd terraform/
   74  echo "project = \"${PROJECT_ID}\"" >> ./terraform.tfvars
   75  echo 'generate_cron_schedule = "*/15 * * * *"' >> ./terraform.tfvars
   76  cat terraform.tfvars
   77  gsutil mb -p ${PROJECT_ID} gs://${PROJECT_ID}-tf-state
   78  cat <<EOF > ./state.tf
terraform {
  backend "gcs" {
    bucket = "${PROJECT_ID}-tf-state"
  }
}
EOF

   79  terraform init
   80  history
   81  terraform apply

```
Any thoughts how can I continue with?

**Comment by sethvargo** [comment]
Hi @besingamkb 

My guess is that you're seeing that error because of the error above. It looks like you have uncommitted local changes in your repo, which is preventing the migrations from running.

**Comment by besingamkb** [comment]
@sethvargo thanks i think it works. but I got a new error now. 

`Error: Error creating Connector: googleapi: Error 409: Requested entity already exists`

**Comment by sethvargo** [comment]
Hmm @besingamkb - did you ctrl+c or interrupt Terraform? That error is happening because the VPC connector already exists. You can try deleting it in the UI and re-running Terraform.

**Comment by besingamkb** [comment]
hi @sethvargo i haven't interrupt terraform. can you point me out where should I go and delete it? because on my serverless VPC access overview page I dont see anything..

![Screenshot_325](https://user-images.githubusercontent.com/6380139/91771813-37556380-ec16-11ea-855d-b0b3e597fda3.png)

**Comment by sethvargo** [comment]
Can you share the full error output? Are you sure you're in the correct GCP project?

**Comment by besingamkb** [comment]
here is what I am getting now and yes I am on the same GCP project.

```
  # google_vpc_access_connector.connector will be created
  + resource "google_vpc_access_connector" "connector" {
      + id             = (known after apply)
      + ip_cidr_range  = "10.8.0.0/28"
      + max_throughput = 1000
      + min_throughput = 200
      + name           = "serverless-vpc-connector"
      + network        = "default"
      + project        = "aex-gaen-server-ph"
      + region         = "asia-east1"
      + self_link      = (known after apply)
      + state          = (known after apply)
    }

Plan: 23 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_vpc_access_connector.connector: Creating...

Error: Error creating Connector: googleapi: Error 409: Requested entity already exists

  on main.tf line 71, in resource "google_vpc_access_connector" "connector":
  71: resource "google_vpc_access_connector" "connector" {


Releasing state lock. This may take a few moments...

```

![Screenshot_326](https://user-images.githubusercontent.com/6380139/91777629-f748ad80-ec22-11ea-929b-806a0ee1eb04.png)

**Comment by sethvargo** [comment]
Can you run with `TF_LOG=debug`, put the output in a gist, and paste the link here?

**Comment by besingamkb** [comment]
sorry for late reply @sethvargo  i'll inform you later i just got an crash issue after I terminate a `terraform apply` using ctrl + c

**Comment by sethvargo** [comment]
Can you please share the logs?

**Comment by besingamkb** [comment]
Hi @sethvargo here is the log file you requested. https://gist.github.com/besingamkb/442c39ce0a614b86d3a3cc485bf6dd4a I ended up creating new project because of the crash I encounter on the previous project `aex-gaen-server-ph`. The new project name i created is  named `gaen-ph`

below is the history for the new created project on gcp.
```
  118  git clone git@github.com:google/exposure-notifications-server.git gaen-ph
  119  cd gaen-ph/
  120  unset GOOGLE_APPLICATION_CREDENTIALS
  121  echo $PROJECT_ID
  122  export PROJECT_ID="gaen-ph"
  123  echo $PROJECT_ID
  124  gcloud auth login && gcloud auth application-default login
  125  cd terraform/
  126  echo "project = \"${PROJECT_ID}\"" >> ./terraform.tfvars
  127  echo 'generate_cron_schedule = "*/15 * * * *"' >> ./terraform.tfvars
  128  gsutil mb -p ${PROJECT_ID} gs://${PROJECT_ID}-tf-state
  129  cat <<EOF > ./state.tf
terraform {
  backend "gcs" {
    bucket = "${PROJECT_ID}-tf-state"
  }
}
EOF

  130  git status
  131  git tags -l
  132  git tag -l
  133  git checkout tags/v0.6.0
  134  git status
  135  git commit -am "region changes"
  136  export TF_LOG=DEBUG
  137  export TF_LOG_PATH=~/terraform-gaen-ph.log
  138  terraform init
  139  git status
  140  terraform apply
```

**Comment by sethvargo** [comment]
Hi @besingamkb 

I don't see any errors or failures in that log output.

**Comment by besingamkb** [comment]
@sethvargo i have updated the gist can u check again?. i'll try to change the TF_LOG=TRACE and see if it show more than debug

**Comment by sethvargo** [comment]
I think your gist may be getting truncated. I only see 7k lines and none of them contain the `[ERR` string.

**Comment by besingamkb** [comment]
@sethvargo oh yes here is the raw link of the log https://gist.githubusercontent.com/besingamkb/442c39ce0a614b86d3a3cc485bf6dd4a/raw/50c7d27f3ea463c605f00d870a4f0dbfc32fc342/gistfile1.txt

**Comment by sethvargo** [comment]
Do you already have a network using `10.8.0.0/28` (or overlapping)?

**Comment by besingamkb** [comment]
i dont think so but im not sure. I dont see any data on VPC Network > Serverless VPC Access. Should I create it manually?

**Comment by sethvargo** [comment]
You can try creating it manually. I'm curious if you'll see the same error in the UI.

**Comment by besingamkb** [comment]
I got this when creating it manually
![Screenshot_330](https://user-images.githubusercontent.com/6380139/91886484-fadc4300-ecbb-11ea-9602-762fb4785a39.png)

I also got the same error
```
Error: Error creating Connector: googleapi: Error 409: Requested entity already exists

  on main.tf line 71, in resource "google_vpc_access_connector" "connector":
  71: resource "google_vpc_access_connector" "connector" {
```

**Comment by sethvargo** [comment]
Can you try deleting it from the UI now? I think your connector is in a partial state and I'm hoping deleting it from the UI deletes it. After that, wait about a minute before trying Terraform again.

**Comment by besingamkb** [comment]
it still got the error. here's the updated raw terraform.log https://gist.githubusercontent.com/besingamkb/442c39ce0a614b86d3a3cc485bf6dd4a/raw/c702bb28e270565a2767113ba7d5517943f1d822/gistfile1.txt

do you think it might be the region? because I set the region in asia-east-1 and asia-east-2

**Comment by besingamkb** [comment]
actually i tried change the `network_location` from asia-east-1 to asia-east-2. and I a different error now. 

```
Error: Error waiting to create Connector: Error waiting for Creating Connector: Error code 13, message: An internal error occurred: Failed to create a VPC Access connector. Please delete the connector manually.

  on main.tf line 71, in resource "google_vpc_access_connector" "connector":
  71: resource "google_vpc_access_connector" "connector" {

```

and I see this on the serverless VPC access page
![Screenshot_331](https://user-images.githubusercontent.com/6380139/91889262-22cda580-ecc0-11ea-95ce-713c400d03b3.png)

**Comment by besingamkb** [comment]
@sethvargo actually i dont have an organization on my gcp account as of the moment

**Comment by sethvargo** [comment]
Hmmm. I wonder if that's a requirement for VPC connectors. @mikehelmick do you know?

**Comment by chaodaiG** [comment]
Sounds like related to the region, could you try `us-central1` instead?

**Comment by besingamkb** [comment]
i tried creating new project again on gcp .. now I didnt change any region and I got this error..

```
Error: Error waiting to create Connector: Error waiting for Creating Connector: Error code 7, message: Operation failed: Google APIs Service Agent (<PROJECT_NUMBER>@cloudservices.gserviceaccount.com) needs editor role in the project.

  on main.tf line 71, in resource "google_vpc_access_connector" "connector":
  71: resource "google_vpc_access_connector" "connector" {

```

**Comment by sethvargo** [comment]
It's very possible that our configurations require an organization.

**Comment by marekaf** [comment]
It works for us for a projects both inside and outside org (our prod is inside org, old dev is outside org for legacy reasons). I do remember having some troubles with it too when trying to bootstrap everything on one `terraform apply`. I think I had to apply everything, wait for this error, manually delete the connector and apply again (took 2-3 applies before it work), I suspect some weird dependency outside of allowing `"vpcaccess.googleapis.com"` API and waiting for it be ready.

**Comment by sethvargo** [comment]
I'm not sure the best path forward. I'm unable to reproduce this, and we haven't had other users report this, which leads me to believe it's some kind of configuration with your org or account.

**Comment by besingamkb** [comment]
I am contacting my manager to get gsuite for organization. can we still open this issue i'll update once I got organization ready

**Comment by sethvargo** [comment]
If you have a gsuite account, I believe you have to have an organization. It should be the domain for your gsuite account.

**Comment by besingamkb** [comment]
> It works for us for a projects both inside and outside org (our prod is inside org, old dev is outside org for legacy reasons). I do remember having some troubles with it too when trying to bootstrap everything on one `terraform apply`. I think I had to apply everything, wait for this error, manually delete the connector and apply again (took 2-3 applies before it work), I suspect some weird dependency outside of allowing `"vpcaccess.googleapis.com"` API and waiting for it be ready.

i have tried this several times now. i'll keep trying i hope i got it work on my end too.

**Comment by besingamkb** [comment]
i have made some progress here. what I did is I add `vpc_access_connector_max_throughput= 300` on `terraform.tfvars` that I have read here https://github.com/google/exposure-notifications-server/issues/639

It finally create a serverless VPC access that is not on the bad state and the error got different. please see below..

```
Error: Error waiting to create Service: resource is in failed state "Ready:False", message: Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.

  on service_cleanup_export.tf line 67, in resource "google_cloud_run_service" "cleanup-export":
  67: resource "google_cloud_run_service" "cleanup-export" {



Error: Error creating Service: googleapi: Error 409: Resource 'default-2018-11-05' already exists.

  on service_cleanup_exposure.tf line 61, in resource "google_cloud_run_service" "cleanup-exposure":
  61: resource "google_cloud_run_service" "cleanup-exposure" {



Error: Error creating Service: googleapi: Error 409: Resource 'default-2018-11-05' already exists.

  on service_export.tf line 73, in resource "google_cloud_run_service" "export":
  73: resource "google_cloud_run_service" "export" {



Error: Error creating Service: googleapi: Error 409: Resource 'default-2018-11-05' already exists.

  on service_exposure.tf line 73, in resource "google_cloud_run_service" "exposure":
  73: resource "google_cloud_run_service" "exposure" {



Error: Error creating Service: googleapi: Error 409: Resource 'default-2018-11-05' already exists.

  on service_federationin.tf line 61, in resource "google_cloud_run_service" "federationin":
  61: resource "google_cloud_run_service" "federationin" {



Error: Error creating Service: googleapi: Error 409: Resource 'default-2018-11-05' already exists.

  on service_federationout.tf line 61, in resource "google_cloud_run_service" "federationout":
  61: resource "google_cloud_run_service" "federationout" {



Error: Error creating Service: googleapi: Error 409: Resource 'default-2018-11-05' already exists.

  on service_generate.tf line 61, in resource "google_cloud_run_service" "generate":
  61: resource "google_cloud_run_service" "generate" {



Error: Error creating Service: googleapi: Error 409: Resource 'default-2018-11-05' already exists.

  on service_keyrotation.tf line 73, in resource "google_cloud_run_service" "key-rotation":
  73: resource "google_cloud_run_service" "key-rotation" {



```

**Comment by besingamkb** [comment]
it is working on my end now. 

this works for me. adding this into the terraform.tfvars `vpc_access_connector_max_throughput= 300`
