### ISSUE TITLE
generate service should be disabled in production?

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-server#955]
### Question
Hello 👋 
Do I understand it correctly that `generate` service is being used only to generate sample exposure keys and thus should be disabled for production use? 

Thanks!

**Comment by sethvargo** [comment]
It's safe to run in production and adds more privacy preserving features to the system.

**Comment by marekaf** [comment]
Do you mind adding that to the docs? Thanks.

**Comment by sethvargo** [comment]
Hi @marekaf - can you point to the documentation that says this?

**Comment by marekaf** [comment]
> Hi @marekaf - can you point to the documentation that says this?

https://google.github.io/exposure-notifications-server/getting-started/deploying here's a 
```
generate | cmd/generate | Sample service that generates data
```
