### ISSUE TITLE
Stackdriver custom metrics do not appear in SD monitoring

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-server#987]
Hello 👋 
We are currently using `v0.3.0` key server and I'd like to query `publish-exposures-written` metric from SD Metrics Explorer.
I have the default `OBSERVABILITY_EXPORTER=stackdriver` and in SD logs I see `"!METRIC! Type = publish-exposures-written cumulative = true" ...`, however these do not appear in SD metrics. Also, I see no error logs in trying to write to SD. 

Any chance this is a bug that was solved in newer versions than v0.3? 

Thanks!

**Comment by icco** [comment]
Yup! So a bunch of the metrics are fixed in the latest version, and the next release should have all of the metrics exported. See https://github.com/google/exposure-notifications-server/pull/984
