### ISSUE TITLE
/healthz endpoint for exposure service

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-server#988]
Hi 👋 

I need to prevent scaling to 0 / cold starts on exposure service.

AFAIK Cloud Run does not support this yet (but it is in the roadmap for GA) and the "recommended" way is a Cloud Scheduler workaround https://github.com/ahmetb/cloud-run-faq#how-to-keep-a-cloud-run-service-warm 
I tried setting up Scheduler with HTTP trigger but it doesn't feel right to call `/v1/publish` endpoint. I'd rather call something like `/healthz` and get 200.  Is there any "dummy" endpoint like that on exposure service? Would it make sense to implement it?

Would it make sense to implement this Cloud Scheduler workaround in terraform as an optional resource too? 

Thanks!

**Comment by icco** [comment]
/health is implemented for this purpose. https://github.com/google/exposure-notifications-server/issues/881 was where this was requested and links to the pull request where it was implemented.

**Comment by icco** [comment]
If it's missing or not working on any binaries, let us know, but should be good to go.

**Comment by mikehelmick** [comment]
re: preventing scaling to 0.

Can you elaborate on why?

**Comment by marekaf** [comment]
@mikehelmick when it scales to 0, uploading exposure keys fails and needs to be retried on mobile app client. On a retry, new cloud run instance is already warmed up and can serve the upload request.

**Comment by mikehelmick** [comment]
I've observed cold start times typically < 2 seconds.

What kind of timeout do you have on the client? How is this manifesting?

Want to see if theres any changes we should make in general.

**Comment by marekaf** [comment]
I'll try to find out, I don't have access to the client, I'll ask the teams reponsible. Thanks!

**Comment by icco** [comment]
@marekaf any updates?

**Comment by marekaf** [comment]
> @marekaf any updates?

Hi, we rolled out some detailed logging on the clients quite late, we had to create a hotfix using cloud scheduler to prevent scaling to zero so we have no way to test this now. Now as the hotfix is in place, we have no way to test this unfortunately. We'll bump the server version tomorrow. I think this can be closed for now.

**Comment by icco** [comment]
Ack.
